### ISSUE TITLE
Set current directory independently of other calls

### ISSUE THREAD

**Issue by miguelmorin** [djcb/mu#1492] opened 2019-09-26 16:02 UTC
## Expected or desired behavior

I have two Emacs init files, one common to two computers and one specific to each. Each init file opens some files with `find-file`. I start `mu4e` at the end of one of the init files with `(mu4e)`. After running the second init file, mu4e may lose focus and I return to it with `M-x mu4e`. I index with `U` and expect it to index normally.

## Actual behavior

When the call to `(mu4e)` is the last one in my **last** init file, then indexing works OK. If it's the last in my **first** init file, then I get this error:

```
Setting current directory: No such file or directory <some path>
```

where `<some path>` equals, for example, `<some parent dir>/<some dir>` with the fourth command in my **last** init file in this way:

```el
(dolist (f '(
	     "<some dir>/<some filename>"
	     "<some other dir>/<some other filename>"
             ; more paths here
	     ))
  (let ((default-directory "<some parent dir>"))
    (find-file (expand-file-name f))))
```

Because it's set four commands after `mu4e` and it's picking the path in the middle of an ELisp command, I believe that the problem is that `mu4e` is started asynchronously and is picking up whatever default directory is set at that time.

If I go back to `mu4e` and do `M-x find-file`, I am prompted for that same directory `<some path>`.

I am able to index if I call `(mu4e)` as the very last thing in the init file, after all the other calls.

After refactoring my init files into a single file, the bug does **not** happen and indexing works as expected, which I found quite surprising.

The behavior is consistent in all cases and the error message happens always in the case I described. I have my init files in version control and can return to it, e.g. stacktrace or messages that I may have missed.

## Versions of mu, mu4e/emacs, operating system etc.

> mu4e-mu-version is a variable defined in ‘mu4e-meta.el’.
> Its value is "1.2.0"

Emacs: Version 26.2 (9.0)

OS: macOS 10.14.6

**Comment by djcb** [comment] 2020-02-26 20:00
Hmmm, don't think I quite understand -- your emacs (mu4e) passes the paths (which ones do you mean? maildir? muhome) to mu, and that should be independent of the current directory, unless you pass relative paths I suppose (and you shouldn't). Moreover, mu4e doesn't touch `default-directory` when it starts.

Anyway in the recent 1.3.x series this works quite differently; you only ever pass muhome (i.e., `mu4e-mu-home`, the rest is handled internally.

Closing this - feel free to open a ticket if you can reproduce with 1.3.x, and please make a minimal reproducible example if you can - Thanks!

**Closed by djcb** 2020-02-26 20:00 UTC

**Comment by miguelmorin** [comment] 2020-03-12 16:55
I store emails in `~/Maildir` and set my paths with, for example, `(setq mu4e-sent-folder   "/account-name/Sent Items")`.

Yes, I will try with `mu4e 1.3.x` when it's in release if I have the same problem.

**Comment by gyhor** [comment] 2020-03-17 09:57
I think I have the same issue. I pulled the last version ( 2020-03-17) and now mu4e complaints, that the ".local/share/mail/sent" directory does not exist.
But I don't have that directory because in my multi-account setup I use different directories for every account(configuration with mu4e-context).

I dont' know why in last version the variables are ignored.

**Comment by djcb** [comment] 2020-03-17 10:17
@gyphor: are you using  the `mu4e-maildir` variable? Or what variable is "ignored"?

**Comment by gyhor** [comment] 2020-03-17 10:39
parts of my configuration
``` emacs

     (mu4e :variables
           mu4e-installation-path "/usr/share/emacs/site-lisp/mu4e"
           mu4e-use-maildirs-extension nil
           mu4e-maildirs-extension-default-collapse-level 2
           mu4e-maildirs-extension-hide-empty-maildirs nil
           mu4e-maildirs-extension-use-bookmarks nil 
           mu4e-enable-notifications t
           mail-user-agent 'mu4e-user-agent
           mu4e-maildir "/home/xxxx/.local/share/mail"
           ;; needed so you don't reply to your self
           mu4e-user-mail-address-list '("xxxx@yahoo.de" "xxxx@xxxx.de" )
           mu4e-compose-dont-reply-to-self t
           mu4e-view-show-images t
           mu4e-enable-mode-line t
           mu4e-compose-in-new-frame t
           mu4e-headers-include-related t
           mu4e-headers-visible-lines 20
           mu4e-use-fancy-chars t
           ;; enable inline images
           mu4e-view-show-images t
           mu4e-attachment-dir  "~/Downloads"
           mu4e-view-prefer-html t
           mu4e-get-mail-command "mbsync -a"
           mu4e-update-interval 180
           mu4e-headers-auto-update nil
           mu4e-compose-signature-auto-include nil
           mu4e-compose-format-flowed t
           message-kill-buffer-on-exit t
           mu4e-change-filenames-when-moving t

           ;; show full addresses in view message (instead of just names)
           ;; toggle per name with M-RET
           mu4e-view-show-addresses 't
           ;; don't ask when quitting
           mu4e-confirm-quit nil
           )
     )

;...*snip*

; default values
(setq mu4e-trash-folder  "/xxxx/Trash"
      mu4e-sent-folder "/xxxx/Sent"
      mu4e-drafts-folder "/xxxx/Drafts"
      )

;...*snip*
; context for different accounts
(setq mu4e-contexts
      `(
        ,(make-mu4e-context
          :name "work"
          :enter-func (lambda () (mu4e-message "Switch to the work context"))
          :match-func (lambda (msg)
                        (when msg
                          (string-match-p "^/4tek" (mu4e-message-field msg :maildir))))
          :leave-func (lambda () (mu4e-clear-caches))
          :vars '((user-mail-address     . "xxxx")
                  (user-full-name        . "xxx")
                  (mu4e-sent-folder      . "/xx/Gesendete Elemente")
                  (mu4e-drafts-folder    . "/xxx/Entw&APw-rfe")
                  (mu4e-trash-folder...

```

**Comment by gyhor** [comment] 2020-03-17 10:40
yes, I am using the `mu4e-maildir` variable

**Comment by gyhor** [comment] 2020-03-17 10:48
after deleting the variable `mu4e-maildir` and disabling `mu4e-use-maildirs-extension nil` I don't get the message, that ".local/share/mail/sent" directory does not exist.

**Comment by djcb** [comment] 2020-03-17 10:55
If you see `NEWS.org` (`N` in the mu4e main menu) you'll see that that `mu4e-maildir` is no longer used. Neither is `mu4e-user-mail-address-list`, btw.

**Comment by gyhor** [comment] 2020-03-17 11:19
Thank you for info. 
If the change breaks the backwards configuration it would be nice if there is a warning in the changelog.
