### ISSUE TITLE
[mu bug] Repeated database corruption

### ISSUE THREAD

**Issue by peterhoeg** [djcb/mu#2706] opened 2024-05-14 08:56 UTC
**Describe the bug**
I have been experiencing repeated database corruption on 2 different machines (a desktop and a laptop). I don't know if this is a xapian issue or mu-specific  but it's been happening for a while now since the 1.11.x version of mu.

The message about corruption is different from time to time. It just happened again which is why I'm opening this issue and this time the message is:

```
xapian-check xapian/
docdata:
blocksize=8K items=792095 firstunused=75954 revision=1474 levels=2 root=73078
B-tree checked okay
docdata table structure checked OK

termlist:
blocksize=8K items=1584190 firstunused=143755 revision=1474 levels=2 root=143383
B-tree checked okay
termlist table structure checked OK

postlist:
blocksize=8K items=3771042 firstunused=203935 revision=1474 levels=3 root=155464
xapian-check: DatabaseCorruptError: Block overwritten - run xapian-check on this database
```

As far as I recall, the error has always been with the `postlist` although the messages differ.

**To Reproduce**
There are no specific steps to reproduce - this has been happening once a week or so for quite some time.

**Environment**
NixOS 24.05, Emacs 29.3, latest mu (1.12.5 presently), Xapian 1.4.25

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment] 2024-05-14 10:16
I've seen this occasionally... what Xapian version are you using?

**Comment by peterhoeg** [comment] 2024-05-14 11:13
I should have added that in earlier, apologies.

It's 1.4.25

All dependencies are shown below.

<details>

```
/nix/store/gm61h1y42pqyl6178g90x8zm22n6pyy5-libunistring-1.1
/nix/store/ddfzjdykw67s20c35i7a6624by3iz5jv-libidn2-2.3.7
/nix/store/nrwkk6ak3rgkrxbqhsscb01jpzmslf2r-xgcc-13.2.0-libgcc
/nix/store/apab5i73dqa09wx0q27b6fbhd1r18ihl-glibc-2.39-31
/nix/store/k927dryij6k8ga8slxs39pjdsmsny8c8-gcc-13.2.0-libgcc
/nix/store/p3ffjixpnfgkqh20nsrc13vrj3yfi0nj-gcc-13.2.0-lib
/nix/store/0fn1lbdb83gx7n917akp76djfkkc00x2-cld2-unstable-2015-08-21
/nix/store/117avr6c47nih6gy28wid7yr89xvp94s-libgpg-error-1.48
/nix/store/14b6spahplg5gsk3qna7g2vanqrji3pk-libksba-1.6.6
/nix/store/2bbjyrnwajslpr4kyyf5k0snv3cs5kw7-libgcrypt-1.10.3
/nix/store/nw1bnjadmzk9hnd4nbvxmqlh074vr16j-zlib-1.3.1
/nix/store/2lzvm03ybzp2zbvhj1y283087ghjw0k8-kexec-tools-2.0.28
/nix/store/jrrnf6kak9fbfm910506ppws50d33p9f-ncurses-6.4
/nix/store/2xjpd6ikhjajmdik680cvd8md6cikkp3-readline-8.2p10
/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26
/nix/store/xs3y3icbd26gxr617m1alhjba12pkm92-util-linux-minimal-2.39.3-lib
/nix/store/2zna3wb0sd0rx6xqjmihaqy1wjzczzyb-xapian-1.4.25
/nix/store/7mnvfrpsbivkxyfbmqczdq5pbb1n59j1-zstd-1.5.6
/nix/store/n87dnp3cw99gssql0xk9yycrhrg50gir-xz-5.4.6
/nix/store/33dl0i8mjh76kanigvkgmwyxp04mv436-kmod-31-lib
/nix/store/3iiml9pwff4y6zsis1gp4apbry1h1wfr-xz-5.4.6-bin
/nix/store/wwg6376ymkhpjxy6c3w9gkbhv6l2gmqy-libxcrypt-4.4.36
/nix/store/3q6f0k00yg2ddra93ybism3hy1ha3azk-util-linux-minimal-2.39.3-login
/nix/store/8f10pxi30lvkdjrkzfw5gzz4rzia8163-openssl-3.0.13
/nix/store/q7640gaa4r0jmjsysa2i7ckai7zr9pkr-keyutils-1.6.3-lib
/nix/store/pjmhai9as695ph4ykrx6990pj7xwhpyx-libkrb5-1.21.2
/nix/store/qkpxz2s5aq6lly1lbmaa2ggwmnlslwna-db-5.3.28
/nix/store/4mlz8w1m4420s89sy1rg6d997mbkznsb-cyrus-sasl-2.1.28
/nix/store/q4k8gmw2gpncglwdvz9fmqqwnynsb143-bzip2-1.0.8
/nix/store/5giwsjx504zrgzl7cjzxm0s1423wndif-bzip2-1.0.8-bin
/nix/store/5gzyfqc5vzm4gyijkyxw8bl8i91zfk77-gmp-with-cxx-6.3.0
/nix/store/hffrnc162j2j1rvrdnfiy8jflcxzf9mn-json-c-0.17
/nix/store/xzmgdglbldim3k39pjn16vrgxb3i72as-publicsuffix-list-0-unstable-2024-01-07
/nix/store/g6as2fdsiar8wzkkyiaj62z4knmxaxwl-libpsl-0.21.5
/nix/store/nn2ri4n3klfz71f3aiwycykz9c8xqm9p-libssh2-1.11.0
/nix/store/qa2j4ql5vb7n1zyi8ai5acivsjkg0l8m-brotli-1.1.0-lib
/nix/store/wi6w7jbnskypgc1dd3asv8p6rmw12ih8-nghttp2-1.61.0-lib
/nix/store/his3qhkzxg1s2j34spm27w2f4mvh2y84-curl-8.7.1
/nix/store/5s0glc9fcb902kabb16yl1ak20xnp16w-tpm2-tss-4.1.0
/nix/store/5w1acngnkxqsbidwbfbrrrhrzyjik3d5-libffi-3.4.6
/nix/store/7fmplwm445l3qhp2ck9p8bcbz1aaj5qp-dns-root-data-2023-11-27
/nix/store/v4jrk736s8a8mk3vcf50hx1l0dwa4bdz-libcap-2.69-lib
/nix/store/8f64rn26nd0cyy0brblzyn064fmcmy79-systemd-minimal-libs-255.4
/nix/store/rkj3k7pflfvjf7shraqvb1qd9s2dz1zs-gmp-with-cxx-6.3.0
/nix/store/adalw59bvrk2fg2fl662xnc4y2bqn438-nettle-3.9.1
/nix/store/sqgnfysp5n513gh4qqcs69yx9gxylzmv-libevent-2.1.12
/nix/store/dq7kpdqsxm7z7p26f7ppc8bjyfpwqm03-unbound-1.19.3-lib
/nix/store/nqd74akpcgp1xfaqbdlfsim807ixnfbc-libtasn1-4.19.0
/nix/store/v48dbyr8cmci56xp91m50z6x65mqws9x-p11-kit-0.25.3
/nix/store/a8j5yhyqcqahvrm6p99gkqs1yjmv9wcn-gnutls-3.8.5
/nix/store/sik7a8dic5lxhm4cp9npibk97x9jcxwf-pcre2-10.43
/nix/store/d0amq09n85152751g6zspl60mrjbadvz-libselinux-3.6
/nix/store/bcms6vbac6jyffwyj8y630brpy1il4ks-glib-2.80.0
/nix/store/yb39i0a63bx8kx2bgmx1p4dx1hcwmnzh-attr-2.5.2
/nix/store/y4psv76i8pllhnsd1dg7zbqsj8a2sz64-acl-2.3.2
/nix/store/ddypgcb25zgi0gwvklxlzazjrh9s63dg-coreutils-9.5
/nix/store/wy37jk2hirzqzx0666w1849kjdgzdam6-gnugrep-3.11
/nix/store/g1zh8pzpgkyl7ja4bbi4syjnif18xasp-zstd-1.5.6-bin
/nix/store/hragmx5p3izmwinv4441hj5706sxy4xs-gzip-1.13
/nix/store/bjzji701dz67bfrrwx9smqqyy1pnf2c9-kbd-2.6.4
/nix/store/bwcl7y02qj8mxhwpqflz56wjkaaxmq22-pcsclite-2.1.0-lib
/nix/store/gbx1y99nzj2vj03vn23mbnsfx8dwf9kd-sqlite-3.45.3
/nix/store/hdqqlyrv0gwvxnwpayvl7y8glmx81m44-libsodium-1.0.19
/nix/store/in8kwd36w4fcqd8xizr2r8qy1dx0rbx6-libtool-2.4.7-lib
/nix/store/fdiy11m9nkph9hrl2k0ibl4xmra9icmp-util-linux-minimal-2.39.3-swap
/nix/store/q66l12afk5bly0aprvdxjkjrsz2dbma8-glibc-2.39-31-getent
/nix/store/g11dc1qynwyvbqpf40d81f9205w48m76-getent-glibc-2.39-31
/nix/store/hx4sz22j1gij2gshi9w110x39zl7hpd8-libseccomp-2.5.5-lib
/nix/store/nnvsjd3f3dh9wdl4s9mwg5cfri8kds5j-bash-interactive-5.2p26
/nix/store/wyk82rbsdshy57l4y5zl5bfnyq03q85f-kmod-31
/nix/store/yi18kda2q14sqkimq75qpn2w1kk2g6d3-util-linux-minimal-2.39.3-mount
/nix/store/yhnhwqm09w9302rx24804i67jfp8ar4h-systemd-minimal-255.4
/nix/store/qvgz18lsxl233ph5kk3i1p7lv9wh6p8q-openldap-2.6.7
/nix/store/rs028f1bbm7i0qc3k2gd7j9rk6hywc45-libassuan-2.5.7
/nix/store/vlcly0k4fys9x3ad64faxcyz33a7c00h-libusb-1.0.27
/nix/store/zaf8aj5sl1ml9hcz9b32vyhvjs66wkxv-npth-1.7
/nix/store/fxyrm6pws83nmq89sbxlkaq3ln9kjbl6-gnupg-2.4.5
/nix/store/f59g2b8xbri3gplcai9p90y1p0i0c2yz-gpgme-1.23.2
/nix/store/qsd48ndjzzpy70y0clxjxs2f968lk0hq-gmime-3.2.14
/nix/store/z2ccqp8yipjdk8w2qw9fpgb88swa60h0-mu-1.12.5
```

</details>

**Comment by peterhoeg** [comment] 2024-05-15 09:04
Just happened again but with a different error:

```
Database couldn't be opened for reading: DatabaseCorruptError: Expected block 104050 to be level 3, not 0
Continuing check anyway
docdata:
blocksize=8K items=791426 firstunused=77160 revision=236 levels=2 root=6263
B-tree checked okay
docdata table structure checked OK

termlist:
blocksize=8K items=1582852 firstunused=142454 revision=236 levels=2 root=14600
B-tree checked okay
termlist table structure checked OK

postlist:
xapian-check: DatabaseCorruptError: Expected block 104050 to be level 3, not 0
```

**Comment by peterhoeg** [comment] 2024-05-23 15:19
And a different error again:

```
docdata:
blocksize=8K items=790419 firstunused=77826 revision=1773 levels=2 root=6812
B-tree checked okay
docdata table structure checked OK

termlist:
blocksize=8K items=1580838 firstunused=143486 revision=1773 levels=2 root=13888
B-tree checked okay
termlist table structure checked OK

postlist:
blocksize=8K items=3734630 firstunused=203197 revision=1773 levels=3 root=22505
xapian-check: DatabaseError: Block 45602 item 51: key >= right dividing key in level above
```

**Comment by peterhoeg** [comment] 2024-05-27 22:17
Is there anything I can do or any additional information that would be helpful?

**Comment by djcb** [comment] 2024-05-28 07:24
I'll let you know when I have something for testing. Hopefully this week.

**Comment by peterhoeg** [comment] 2024-05-28 17:28
I didn't mean to chase/rush you - I was just thinking if there was anything I could do to help.

There's a new error just now:

```
docdata:
blocksize=8K items=790760 firstunused=52993 revision=2499 levels=2 root=1389
B-tree checked okay
docdata table structure checked OK

termlist:
blocksize=8K items=1581520 firstunused=147135 revision=2499 levels=2 root=144033
B-tree checked okay
termlist table structure checked OK

postlist:
blocksize=8K items=3751217 firstunused=211301 revision=2499 levels=3 root=55552
xapian-check: DatabaseError: Block 206577 item 65: not in sorted order
```

**Comment by djcb** [comment] 2024-06-01 08:09
I think the problem is with multiple writers / transactions to the Xapian database. It's not really documented exactly what Xapian allows, but likely mu broke a few rules.

Anyway, there's `wip/djcb/store-worker` which ensures all writes and mu4e commands are handled in a single thread. Works fine for me, with a few (cosmetic) things I want to fix before merging into `master`. But, should hopefully address the errors you're seeing.

**Comment by peterhoeg** [comment] 2024-06-06 13:11
I am still seeing corruption with that branch (commit: 920dbb6a796b6b87da8d44fb491190f918efd7a9):



position:
blocksize=8K items=147226877 firstunused=510123 revision=2056 levels=3 root=445762
B-tree checked okay
docdata:
blocksize=8K items=791953 firstunused=78160 revision=2056 levels=2 root=270
B-tree checked okay
docdata table structure checked OK

termlist:
blocksize=8K items=1583906 firstunused=144285 revision=2056 levels=2 root=294
B-tree checked okay
termlist table structure checked OK

postlist:
blocksize=8K items=3751260 firstunused=204576 revision=2056 levels=3 root=95984
B-tree checked okay
Failed to unpack wdf
termfreq 496 != # of entries 58751
postlist table errors found: 2

position:
blocksize=8K items=147226877 firstunused=510123 revision=2056 levels=3 root=445762
B-tree checked okay
position table structure checked OK

spelling:
Lazily created, and not yet used.

synonym:
Lazily created, and not yet used.

Total errors found: 2



On a separate note, due to how things work on NixOS, changing mu also causes a rebuild of mu4e and mu4e doesn’t like the version tag you used 1.12.6-α. I had to patch it to 1.12.5.1 for mu4e to not blow up.

**Comment by peterhoeg** [comment] 2024-06-07 09:49
mu4e has also been hanging for with this branch when performing searches. Sending USR2 to the emacs process makes it respond again for a few minutes before hanging again, so I taken a screenshot of the errors rather than copying out the text as I simply wasn’t fast enough to “get it out” before emacs would hang again.



I have confirmed no errors on the DB by running xapian-check.

**Comment by djcb** [comment] 2024-06-08 15:29
Thanks for testing; yes, there's some issue the indexing in the indexing state machine, working on that. For now 1.12.5 is probably better for now...

 However, did you see database corruption with the branch with `xapian-check`? Your two messages seems a bit a contradictory. Thanks!

**Comment by peterhoeg** [comment] 2024-06-08 19:28
Sequence of events:

1. re-indexed with 1.12.5 after the most recent corruption
2. changed to your test branch
3. after some time, I saw the corruption issue mentioned in https://github.com/djcb/mu/issues/2706#issuecomment-2152425141
4. re-indexed with your test branch
5. I haven't seen any corruption issues, but still get the hang mentioned in https://github.com/djcb/mu/issues/2706#issuecomment-2154492275

**Comment by djcb** [comment] 2024-07-07 14:24
I don't know... I'm seeing it occasionally. 

I only started seeing it recently, perhaps after some system upgrade.  I suspect it's some unsafe access to the Xapian database, and some newer versions of Xapian are less forgiving. But.. this is all just speculation.

The "unsafest" time might be trying to use mu while indexing is underway; so not doing that may help. But who knows.

**Comment by peterhoeg** [comment] 2024-07-23 09:49
Just another data point - I have not seen any corruption issues for quite a while now without any changes to mu and/or xapian.

**Comment by peterhoeg** [comment] 2024-08-01 06:12
FWIW, I have just experienced the issue again - this time with 1.12.6:

```
$ xapian-check .cache/mu/xapian
docdata:
blocksize=8K items=797353 firstunused=83370 revision=325 levels=2 root=11949
B-tree checked okay
docdata table structure checked OK

termlist:
blocksize=8K items=1594706 firstunused=154369 revision=325 levels=2 root=151270
B-tree checked okay
termlist table structure checked OK

postlist:
blocksize=8K items=3806077 firstunused=215875 revision=325 levels=3 root=157358
xapian-check: DatabaseError: Block 152998 item 0: leaf key >= right dividing key in level above
```

**Comment by rhgg2** [comment] 2024-08-12 08:44
I have the same issue with 1.1.25, every month or so I have to reinit the database and reindex due to corruption (a different error message each time). Not sure exactly what version I was running before this, but probably 1.0.x. This is perhaps not a very useful comment, but it does at least show that this is not a unique problem to Peter!

**Comment by ndw** [comment] 2024-08-15 15:44
For better or worse, homebrew updated things on me when I wasn't paying attention. Now I'm running 1.12.6 and the crash is still happening, but `~/.cache/mu/mu.log` is no longer being updated. Did it move somewhere else?

**Comment by ndw** [comment] 2024-09-03 08:28
I find that I have to rebuild the index almost daily. I'm happy to try to provide some debugging information if someone tells me what would be useful. There's still no `mu.log` 😦

**Comment by djcb** [comment] 2024-09-03 20:53
Yeah, it's annoying. I'm trying some different approaches, but nothing working nicely yet...

**Comment by peterhoeg** [comment] 2024-09-05 18:47
If there is anything at all I can do in terms providing information or
trying something out, please don't hesitate to shout. As I'm not familiar
with neither the mu codebase nor xapian, digging into the code looks like
it would be a lot of work for very little gain.

**Comment by ndw** [comment] 2024-09-06 15:41
I had the "consume all disk space" bug again just a few minutes (and a reboot) ago. Nothing out of the ordinary that I could tell. "Searching..." stayed on the screen a long time. I thought "Uh oh" and tried "mu find ndw" on the command line. That seemed stuck as well. I attempted to `kill -9` the mu server process. That didn't work. Then I noticed it was chewing up disk space and I rebooted because actually running out is a real PITA. There's still no evidence of a `mu.log` anywhere :-( so I can't report anything else. Like @peterhoeg , I'm happy to try things. Unreliable email is making me itchy.

**Comment by djcb** [comment] 2024-09-16 20:36
Not sure about the "consume all disk space" issue; can't imagine how mu could cause that.  In any case, would be useful what file is getting big, what is writing to it and if possible trace it. 

Re logging, it might that mu logs to the system logger? It attempts to do that on some systems.

**Comment by djcb** [comment] 2024-09-16 20:45
@peterhoeg, @ndw 

As for trying things, there's an experimental branch `wip/djcb/xapian-single-thread`, which avoids threads when dealing with Xapian. I don't know if that's the problem, hence it's an experiment. Let me know if it makes a difference.

Note, as a user-visible difference, this won't allow you to do anything with mu4e while indexing. That could be improved upon later.

After building/installing/restarting emacs , you should see the mu4e main page with
```
* mu4e - mu for emacs version 1.12.6-st
```
(note the `-st` suffix).

**Comment by peterhoeg** [comment] 2024-09-17 07:40
I'm running with this now. Let's see if it makes a difference. 

For anyone using nix, this will do it:

```nix
{
  overlays = [
    (final: prev: {
      mu = prev.mu.overrideAttrs {
        src = prev.fetchFromGitHub {
          owner = "djcb";
          repo = "mu";
          rev = "wip/djcb/xapian-single-thread";
          hash = "sha256-ZNk9DtaDCnL9GwBcd8l/rphRZMhmCRYhuQQ3M+EU/74=";
        };
      };
    })
  ];
```

**Comment by djcb** [comment] 2024-09-17 07:46
Great!

I'd recommend checking the database is okay before trying, with `xapian-check`, i.e., `
```
xapian-check ~/.cache/mu/xapian
```
(changed path as needed)

which should report 'No errors found'. Otherwise, best to do a `mu init ....` / `mu index` first.

**Comment by ndw** [comment] 2024-09-17 08:28
Okay. I'm running the `-st` version as well.

Re: consuming all disk space, it's tricky to get details because the machine is a few minutes from locking up badly when it happens. But I'll try again if I see it again.

Re: the log file, it *used* to be in `~/.cache/mu` so I'm really not sure why it would be different now. I didn't change it on purpose. I thought maybe the Homebrew install did but (a) I couldn't see anything that looked likely in the `.rb` file and (b) the `-st` build I just made from sources isn't putting the log file there either. :-(

**Comment by peterhoeg** [comment] 2024-09-17 08:32
I did run the check ahead of time which reported no errors, but just to be safe, I blew away the index and rebuilt.

**Comment by wavexx** [comment] 2024-09-17 09:29
I'll add my datapoint here too. I had two corruptions in the span of a single day last week. During this time, nothing special happened: new mail got synched via isync, then reindex kicked in the background at some point. I then noticed when I switched back to mu4e at some point nothing worked due to the server crashing due to db corruption. So I rebuild mu from scratch from git, reindexed, and it happened again within a few hours, again doing nothing special. I had the same setup/version for weeks (I keep mu updated regularly from git). I had this before (extremely rarely), but this is the first time where I couldn't explain why this happened due to the fact that I had a perfectly fresh setup corrupting itself in a few hours.

I'll also try running the st version, although it was always so rare for me I'm not sure how I can effectively tell if that helps or not.

**Comment by djcb** [comment] 2024-09-17 11:41
@ndw: I think the latest versions of GLib (2.80, perhaps?) supports logging to syslog, and `mu` uses that in recent versions.

**Comment by markk** [comment] 2024-09-22 09:47
Update: I have disabled auto update and since then have not had any database corruption. This may be a coincidence, or perhaps some sort of recursive race on the database?

```
(setq mu4e-headers-auto-update nil)
```

**Comment by peterhoeg** [comment] 2024-09-22 14:37
On Sun, 22 Sep 2024 at 02:48 markk ***@***.***> wrote:

> Update: I have disabled auto update and since then have not had any database corruption.

I have it off, so it looks like that isn't the culprit.

**Comment by Chris00** [comment] 2024-10-05 16:17
Today, I've had
```
  Bookmarks

	* [bu] Unread messages                 0/0
	* [bt] Today's messages                0/0
	* [bw] Last 7 days                     0/0
	* [bp] Messages with PDFs              0/0
```
while there definitely are some emails of today.  Xapian check reports some corruption: 
```
xapian-check ~/.cache/mu/xapian/
docdata:
blocksize=8K items=212996 firstunused=18820 revision=61 levels=2 root=18810
B-tree checked okay
docdata table structure checked OK

termlist:
blocksize=8K items=425992 firstunused=33669 revision=61 levels=2 root=29300
B-tree checked okay
termlist table structure checked OK

postlist:
blocksize=8K items=1717590 firstunused=59404 revision=61 levels=2 root=5215
xapian-check: DatabaseError: Block 58072 item 1: not in sorted order
```
mu4e reports in its log
```
2024-10-05 18:12:07.412 <- (:error 113 :message failed to run query: failed to read database)
2024-10-05 18:12:07.412 !! [mu4e] Error 113: failed to run query: failed to read database
```
However, going to the inbox works file.  Quitting mu4e and executing the command by hand reports
```
mu find "flag:unread AND NOT flag:trashed AND NOT maildir:/Spam AND NOT maildir:/U/Junk"
error: failed to read database
hint: Try (re)creating using `mu init'
```

**Comment by Chris00** [comment] 2024-10-08 21:11
@djcb I suppose you are aware of this but since I did not see it mentioned: https://getting-started-with-xapian.readthedocs.io/en/latest/concepts/concurrency.html

**Comment by djcb** [comment] 2024-10-09 05:38
On Tuesday Oct 08 2024, Christophe Troestler wrote:

> @djcb I suppose you are aware of this but since I did not see it mentioned:
> https://getting-started-with-xapian.readthedocs.io/en/latest/concepts/concurrency.html

Thanks.

Yeah, I've read that, we've been using Xapian with threads for years;
but it seems something changed (on the Xapian side?) that made problems
more likely.

All database access it protected by locks, but there's still some state
information outside that, such as transactions. Or generated documents;
something to look into, post 1.12.x.

Kind regards,
Dirk.

-- 
Dirk-Jan C. Binnema                  Helsinki, Finland
***@***.***           w:www.djcbsoftware.nl
gpg: 6987 9CED 1745 9375 0F14 DA98 11DD FEA9 DCC4 A036

**Comment by peterhoeg** [comment] 2024-10-10 13:55
I've been running with the `st` branch on 2 machines for some time and I have not seen *any* of the corruption errors. I have also not noticed any performance regressions of any kind, however please keep in mind that I have not performed any benchmarks.

**Comment by markk** [comment] 2024-10-14 11:19
Confirmed this is working for me also since the merge of the single-thead branch.

**Comment by bramadams** [comment] 2024-10-21 15:57
> Okay. I'm running the `-st` version as well.
> 
> Re: consuming all disk space, it's tricky to get details because the machine is a few minutes from locking up badly when it happens. But I'll try again if I see it again.
> 
> Re: the log file, it _used_ to be in `~/.cache/mu` so I'm really not sure why it would be different now. I didn't change it on purpose. I thought maybe the Homebrew install did but (a) I couldn't see anything that looked likely in the `.rb` file and (b) the `-st` build I just made from sources isn't putting the log file there either. :-(

@ndw: Is the disk space consumption issue related to ~/.cache/mu/xapian/postlist.glass? I'm experiencing an issue related to that right now, see #2774. To reclaim disk space, did you remove that file or you just reran `mu init`?

**Comment by ndw** [comment] 2024-10-21 16:00
Quite possibly. This laptop gets *very* grumpy if you let its disk get completely full. I was unable to kill the process, so I ended up rebooting. I still haven't found the log file, but I've been running the single-thread branch for about a month and there haven't been any crashes. They were nearly daily before, so the anecdotal evidence that it's a multi-threading issue is strong.

**Comment by bramadams** [comment] 2024-10-21 16:27
OK, thanks, perhaps I'll try installing the single-threading version once I got some downtime.

Rebooting did not work in my case, ~/.cache/mu/xapian/postlist.glass was still there. Maybe I'll try re-running `mu init`, assuming that this is just cache data that can be re-generated.

**Comment by bramadams** [comment] 2024-10-21 16:36
Oh, that clarifies, thanks, will do that!

**Comment by djcb** [comment] 2024-10-28 10:23
Thank you all very much for the testing / reporting.  mu 1.12.7 has been released with the "fix", so I am closing this.

It's still a mystery why this started happening all of a sudden, but I suspect some change in Xapian made it less forgiving.

**Closed by djcb** 2024-10-28 10:23 UTC
Labels: bug, mu
