### ISSUE TITLE
error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6

### ISSUE THREAD

**Issue by jfkw** [djcb/mu#1577] opened 2020-02-20 22:39 UTC
## Expected or desired behavior

Use of mu4e mu4e-headers and actions such as mark read, delete, etc. to complete without encountering error messages.

## Actual behavior

```
Are you sure you want to execute 12 marks? (y or n) y
error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6
error in process sentinel: mu server process received signal 6
```

## Steps to reproduce

With apologies for the length, here are some `*Messages*` ouptut examples. Actions are being taken in the `mu43-headers` view to mark messages read, unread, or delete.

After reindexing with `mu index` but before erasing contents of `~/.config/.mu` and rebuilding with `mu init; mu index`. The missing file messages are correct, I verified there is no message file on disk with those names:

```
error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6

error in process sentinel: mu server process received signal 6

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')
[mu4e] Found 57 matching messages

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')
i is undefined

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582230550.15551_5.hostname,U=18826:2, (line was:'(move :docid nil :msgid "(redacted)@gmail.com" :flags "+S-u-N" :maildir nil :rename nil :no-view t)')

error in process filter: mu4e-error-handler: Error 11: failed to find message for view: something went wrong (line was:'(view :docid 20080 :msgid nil :extract-images nil :extract-encrypted nil)')

error in process filter: Error 11: failed to find message for view: something went wrong (line was:'(view :docid 20080 :msgid nil :extract-images nil :extract-encrypted nil)')

error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6

error in process sentinel: mu server process received signal 6
```

```
Are you sure you want to execute 26 marks? (y or n) y

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582040888.15232_37.hostname,U=18385:2, (line was:'(move :docid 19386 :msgid nil :flags "+S-u-N" :maildir nil :rename nil :no-view nil)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582040888.15232_37.hostname,U=18385:2, (line was:'(move :docid 19386 :msgid nil :flags "+S-u-N" :maildir nil :rename nil :no-view nil)')

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582040888.15232_42.hostname,U=18390:2, (line was:'(move :docid 19391 :msgid nil :flags "+S-u-N" :maildir nil :rename nil :no-view nil)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582040888.15232_42.hostname,U=18390:2, (line was:'(move :docid 19391 :msgid nil :flags "+S-u-N" :maildir nil :rename nil :no-view nil)')

error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6

error in process sentinel: mu server process received signal 6
next-line: End of buffer [2 times]
Are you sure you want to execute 2 marks? (y or n) y

error in process filter: mu4e-error-handler: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582040888.15232_29.hostname,U=18377:2, (line was:'(move :docid 19378 :msgid nil :flags "+S-u-N" :maildir nil :rename nil :no-view nil)')

error in process filter: Error 2: failed to move message: cannot read /path/to/INBOX/new/1582040888.15232_29.hostname,U=18377:2, (line was:'(move :docid 19378 :msgid nil :flags "+S-u-N" :maildir nil :rename nil :no-view nil)')
```

After a delete, init ,index cycle of `~/.cache/mu`, I haven't seen the missing file error yet, but errors take the form of:

```
[mu4e] Found 47 matching messages
Are you sure you want to execute 12 marks? (y or n) y
error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6
error in process sentinel: mu server process received signal 6
```

This error occurs for many but not all messages.

## Versions of mu, mu4e/emacs, operating system etc.

- mu4e a132f5c21ff6e65e008daa2d1167d439f6bd5185 managed via el-get,
- GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0) of 2020-02-14
- dev-libs/xapian-1.4.14
- OS Gentoo ~amd64

## Any other detail

This problem cropped sometime recently. Based on local reflog history, possibly in range b77b536d8165cb154ce3f80bd29205ced5961c7d..a132f5c21ff6e65e008daa2d1167d439f6bd5185

**Comment by theophilusx** [comment] 2020-02-20 23:25
I am also seeing this error fairly frequently, plus an occasional error 5. This appears to began to happen after commit 000c19e505dee

**Comment by djcb** [comment] 2020-02-20 23:36
As I wrote on the mailing-list:

Signal 6 is SIGABRT, which suggests mu is unhappy about something and decides to go belly up.

To understand what's going on, it would be useful to get some steps to reproduce and/or the final command mu4e sends to mu (`mu4e-toggle-logging`, see the manual).

And/or a backtrace. You can get those e.g. by attaching a debugger to a running mu (preferably a debug version) (ie. while running mu4e) and then reproduce the problem

```
$ gdb <path-to-mu-executable> -p $(pidof mu)
GNU gdb (GDB) Fedora 8.3.50.20190824-30.fc31
...
(gdb) continue
```

Now, do your thing with u4e and try to reproduce. Then:

```
Program received signal SIGABRT, Aborted.
0x00007f2a983f205b in pselect () from /lib64/libc.so.6
(gdb) backtrace
0x00007f2a983f205b in pselect () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f2a983f205b in pselect () from /lib64/libc.so.6
#1  0x00007f2a98874199 in rl_getc () from /lib64/libreadline.so.8
#2  0x00007f2a98874ab3 in rl_read_key () from /lib64/libreadline.so.8
...
```

and add the output here.

Alternatively, your system may already gather coredumps; e.g. the
systemd `coredumpctl` tool might have the dumps and allow you to produce
a backtrace as well.

**Comment by theophilusx** [comment] 2020-02-20 23:56
I will do a clean rebuild of mu and then see if I can get some data. The issue is intermittent i.e have not found a repeatable recipe or way to predict the error.  Will see if I get more errors after clean build and if I do, will attempt to attach gdb to mu process and see what I get.

**Comment by ravine-var** [comment] 2020-02-21 01:38
Commit c22eb434b742aa122e32d21bba9fede7135cf677 seems to be the problem, after reverting it, the mu server doesn't crash.

Here's a backtrace:

```
(gdb) bt
#0  0x00007f8d6da68ce5 in raise () at /usr/lib/libc.so.6
#1  0x00007f8d6da52857 in abort () at /usr/lib/libc.so.6
#2  0x00007f8d6daac2b0 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007f8d6dab374a in  () at /usr/lib/libc.so.6
#4  0x00007f8d6dab513c in _int_free () at /usr/lib/libc.so.6
#5  0x00007f8d6da0155e in  () at /usr/lib/libgpgme.so.11
#6  0x00007f8d6da034af in  () at /usr/lib/libgpgme.so.11
#7  0x00007f8d6da0098b in  () at /usr/lib/libgpgme.so.11
#8  0x00007f8d6da16053 in gpgme_release () at /usr/lib/libgpgme.so.11
#9  0x00007f8d6e584923 in  () at /usr/lib/libgmime-3.0.so.0
#10 0x00007f8d6e10a491 in g_object_unref () at /usr/lib/libgobject-2.0.so.0
#11 0x00007f8d6e58e2fd in g_mime_multipart_signed_verify () at /usr/lib/libgmime-3.0.so.0
#12 0x0000561c84f2f834 in mu_msg_crypto_verify_part (sig=0x561c8548b4f0, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT), err=0x7fff7f9cd7b0) at mu-msg-crypto.c:307
#13 0x0000561c84ed8a70 in check_signature (msg=0x561c85477b50, part=0x561c8548b4f0, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT)) at mu-msg-part.c:379
#14 0x0000561c84ed9544 in handle_mime_object
    (msg=0x561c85477b50, mobj=0x561c8548b4f0, parent=0x561c854845c0, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT), index=0x7fff7f9cd8b4, decrypted=0, func=0x561c84edccce <find_content_type>, user_data=0x7fff7f9cd900) at mu-msg-part.c:641
#15 0x0000561c84ed97b8 in mu_msg_part_foreach
    (msg=0x561c85477b50, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT), func=0x561c84edccce <find_content_type>, user_data=0x7fff7f9cd900) at mu-msg-part.c:671
#16 0x0000561c84edce33 in get_content_type_parameters (self=0x561c85477b50, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT), want_html=0) at mu-msg.c:525
#17 0x0000561c84edcf63 in mu_msg_get_body_text_content_type_parameters (self=0x561c85477b50, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT)) at mu-msg.c:555
#18 0x0000561c84edb94d in append_message_file_parts (gstr=0x561c854732c0, msg=0x561c85477b50, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT)) at mu-msg-sexp.c:521
#19 0x0000561c84edbde7 in mu_msg_to_sexp (msg=0x561c85477b50, docid=256, ti=0x0, opts=(MU_MSG_OPTION_VERIFY | MU_MSG_OPTION_USE_AGENT)) at mu-msg-sexp.c:630
#20 0x0000561c84eb2477 in view_handler(Context&, Mu::Command::Parameters const&) (context=..., params=std::vector of length 9, capacity 16 = {...}) at mu-cmd-server.cc:1133
#21 0x0000561c84eb27c2 in <lambda(const auto:16&)>::operator()<std::vector<Mu::Sexp::Node> >(const std::vector<Mu::Sexp::Node, std::allocator<Mu::Sexp::Node> > &) const
    (__closure=0x561c85438cd0, params=std::vector of length 9, capacity 16 = {...}) at mu-cmd-server.cc:1277
#22 0x0000561c84eb8bc0 in std::_Function_handler<void(const std::vector<Mu::Sexp::Node, std::allocator<Mu::Sexp::Node> >&), make_command_map(Context&)::<lambda(const auto:16&)> >::_M_invoke(const std::_Any_data &, const std::vector<Mu::Sexp::Node, std::allocator<Mu::Sexp::Node> > &)
    (__functor=..., __args#0=std::vector of length 9, capacity 16 = {...}) at /usr/include/c++/9.2.1/bits/std_function.h:300
#23 0x0000561c84efe85d in std::function<void (std::vector<Mu::Sexp::Node, std::allocator<Mu::Sexp::Node> > const&)>::operator()(std::vector<Mu::Sexp::Node, std::allocator<Mu::Sexp::Node> > const&) const (this=0x561c85438cd0, __args#0=std::vector of length 9, capacity 16 = {...}) at /usr/include/c++/9.2.1/bits/std_function.h:688
#24 0x0000561c84efd586 in Mu::Command::invoke(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Mu::Command::CommandInfo, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Mu::Command::CommandInfo> > > const&, Mu::Sexp::Node const&) (cmap=std::unordered_map with 14 elements = {...}, call=...) at mu-command-parser.cc:86
#25 0x0000561c84eb6beb in mu_cmd_server(MuConfig*, GError**) (opts=0x561c84f7a060 <MU_CONFIG>, err=0x7fff7f9cdec8) at mu-cmd-server.cc:1376
#26 0x0000561c84ec88f0 in mu_cmd_execute (opts=0x561c84f7a060 <MU_CONFIG>, err=0x7fff7f9cdec8) at mu-cmd.c:725
#27 0x0000561c84ea6368 in main(int, char**) (argc=1, argv=0x7fff7f9cdfd8) at mu.cc:121
```

**Comment by djcb** [comment] 2020-02-23 13:22
Thanks. I've made some changes, can you re-try with the latest? Thanks.

**Comment by ravine-var** [comment] 2020-02-23 16:44
I checked with HEAD at 934adae70ae6eda5236529d3c65009e7ba87309d and there are no crashes at my end anymore.

Thanks for the fix. !

**Comment by djcb** [comment] 2020-02-23 23:19
Oh, thanks! Closing this.

**Closed by djcb** 2020-02-23 23:19 UTC
