### ISSUE TITLE
mu4e can't find mbsync, pass commands

### ISSUE THREAD

**Issue by benthamite** [djcb/mu#2264] opened 2022-05-27 12:52 UTC
With `mu4e-get-mail-command` set to `mbsync -a`, `mu4e-update-mail-and-index` returns the error "zsh:1: command not found: mbsync". If full path is specified, `"/opt/homebrew/bin/mbsync -a"`, then the error returned is "sh: pass: command not found". I'm not sure why mu4e can't find mbsync or pass. On eshell, `which mbsync` returns `/opt/homebrew/bin/mbsync`, and `mbsync -a` synchronizes my email. I can also access my passwords fine from the pass major mode.

I started to experience this issue after migrating to a new computer. Everything else seems to be working fine. Another user reports similar issues [here](https://emacs.stackexchange.com/questions/64744/how-to-properly-set-mbsync-and-gpg-binaries-path-with-mu4e).

macOS Monterey 12.4
GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.5.0, Carbon Version 165 AppKit 2113.5) of 2022-05-25
Mu 1.6.10

**Comment by theophilusx** [comment] 2022-05-27 14:16
Pablo Stafforini ***@***.***> writes:

> With mu4e-get-mail-command set to mbsync -a, mu4e-update-mail-and-index returns the error "zsh:1: command not found:
> mbsync". If full path is specified, "/opt/homebrew/bin/mbsync -a", then the error returned is "sh: pass: command not found". I'm
> not sure why mu4e can't find mbsync or pass. On eshell, which mbsync returns /opt/homebrew/bin/mbsync, and mbsync -a
> synchronizes my email. I can also access my passwords fine from the pass major mode.
>
> I started to experience this issue after migrating to a new computer. Everything else seems to be working fine. Another user reports
> similar issues here.
>
> macOS Monterey 12.4
> GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.5.0, Carbon Version 165 AppKit 2113.5) of 2022-05-25
> Mu 1.6.10
>

From what you describe, this is almost certainly a path issue. When you
specify the full path to mbsync, it is finding it because it fails when
it tries to extract your password. This will be because it cannot find
the pass command (again, a path issue). It is finding mbsync because you
have specified a full path, but fails when trying to get your password
(after parsing the .mbsyncrc file) because the path does not include the
directory which has the pass command. 

What many people don't realise is that if you start Emacs from the dock
or spotlight, it does not run as a sub-process of your login shell. This
means that if your setting your path (for example, to add the homebrew
path) in your bashrc, .profile, .zprofile, .zshrc etc, it won't be seen by Emacs (or any of the processes it creates). 

The easiest way to fix this is to add the paths using the global setup
in /etc/paths.d. Just drop a file into that directory which has paths to
directories to add (full path). and these will be added to the shell
when it is spawned. 

Another solution is to not use the dock to start emacs. Instead, run
emacs from within a terminal (assuming that terminal is a child of a
login shell and you have set all necessary paths in your .profile or
.bashrc. You can probably try running Emacs from the terminal and see if
things work then. Provided your path is configured correctly, I suspect
it will.

**Comment by benthamite** [comment] 2022-05-27 19:13
Thank you for the answer. I suspected it may be a PATH issue, but noticed that this happened even when Emacs is launched from the terminal (which is how I normally run Emacs). I also have `exec-path-from-shell` installed, and when I `getenv` the value of PATH, I see exactly what is declared in `.zshenv` (`/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/homebrew/opt/sqlite/bin:/usr/local/sbin:~/.local/bin/`). So there's every indication that Emacs is using the PATH set up by the shell. In any case, just to test the hypothesis, I added `/opt/homebrew/bin/` to `/etc/paths.d` (both mbsync and pass are in that directory) but the issue persists.

**Comment by benthamite** [comment] 2022-05-27 20:44
Also: I just ran [org-gcal](https://github.com/kidd/org-gcal.el) and it was able to authenticate with pass, suggesting that it isn't a PATH issue or, perhaps, that it is a PATH issue involving something more complicated.

**Comment by djcb** [comment] 2022-05-27 21:15
The error(s) are telling you exactly what the problem is: the programs are not in your PATH. So, make sure those are set  in your emacs environment. Check with `M-x getenv`, and use `setenv` as needed. In any case, not a mu4e problem, so closing this. Good luck though!

**Closed by djcb** 2022-05-27 21:15 UTC
Labels: mu4e, support
