### ISSUE TITLE
Images do not load in message view until second time a message is shown

### ISSUE THREAD

**Issue by drielsma** [djcb/mu#650] opened 2015-08-13 13:58 UTC
STEPS TO REPRO:
1. Load the "Messages with images" query
2. Navigate to a message that has a largish (>= 100K) image attached

PROBLEM:
Not always, but about 50% of the time, the image doesn't load the first time the message is displayed.  If you load another message, then return to the first one, the image in the first message will usually load.

I do notice that really small images (not sure of the threshold, but say images of <50K) always load inline the very first time you display a message.

VERSION: 0.9.12 compiled from source at 4df503cfff82e79918333bdb683057bb913bd4a3

**Comment by tmalsburg** [comment] 2015-11-11 19:49
This is a duplicate of #477.  Perhaps move the info about size there and close this issue.

**Comment by djcb** [comment] 2015-11-17 09:19
Yeah, it's a dup of #447. 

Not sure if mu4e can do something about this; and a least with my recent emacs, I can't seem to reproduce anymore.

**Closed by djcb** 2015-11-17 09:19 UTC

**Comment by jgoerzen** [comment] 2017-10-14 21:19
I ran into this just now.  I'm at a loss as to how #477 would impact this; mu4e-mkdir?  Can someone help shed some light?

**Comment by jgoerzen** [comment] 2017-10-14 21:25
OK just to clarify for future visitors if your eye didn't catch the discrepancy in the history above: This is a dup of #447 as djcb indicated, not #477 as was linked above.
