### ISSUE TITLE
mu4e causes emacs to hang on reply

### ISSUE THREAD

**Issue by daphniz** [djcb/mu#1779] opened 2020-08-05 20:39 UTC
When I try to reply to certain messages, emacs says `Mark set' and hangs.  I'm afraid I don't have much useful information beyond that, at least not for now.

**Comment by djcb** [comment] 2020-08-09 07:07
Please add version info and an example message where this happens.

**Comment by xstrtok** [comment] 2020-08-14 11:07
Hi and sorry for hijacking.

Reporting that after the change from 1.2 → 1.4, I had the same problem (could not actually send emails due to timeouts when connecting to the mail server, emacs was blocked due to trying to connect).

Figured out I had thrown away the relevant functions when I was bringing my config up to date:

```lisp
(setq send-mail-function 'smtpmail-send-it
      message-send-mail-function 'smtpmail-send-it
      smtpmail-stream-type 'ssl)
```

@daphniz check if the above helps. In general, a function should be missing.

**Comment by daphniz** [comment] 2020-08-25 19:51
Turns out this happens when I reply to messages containing a
large number of consecutive underscores.  I also get a freeze by
creating a new message and typing many underscores.
________________________________

**Comment by djcb** [comment] 2020-09-20 09:41
Hmmm, that seems more of a general emacs problem... can you attach a (sufficiently censored) message where this happens?

**Comment by scemama** [comment] 2020-11-21 22:39
I just had the same problem.
It was due to the presence of `(modify-syntax-entry ?_ "w")` in my `.init.el`, which might hang when there is a line full of underscores.

I solved it by replacing this by `(global-superword-mode 1)`.

**Comment by Chris00** [comment] 2020-11-22 08:33
Can you turn on “Enter the debugger on Quit/C-g” in the option menu and then post here the trace you get after you hit <kbd>C-g</kbd> when it hangs?  Thanks.

**Comment by scemama** [comment] 2020-11-22 14:54
I did it but emacs is completely frozen with a 100% CPU activity. `C-g` doesn't unfreeze it.
The only way to get out of it is to kill the process.

If you want to reproduce it:

1. Add `(modify-syntax-entry ?_ "w")` to your `.init.el`
2. Open Emacs and mu4e 
3. Send yourself an email with the following content:

```
Hello
________________________________
Bye
```

4. Wait until the message arrives into your inbox
5. Reply to the message

I think it is more a bug related to Emacs than to mu4e. I added this to my `init.el` because the superword behavior is not properly handled by evil mode as reported here:
https://github.com/emacs-evil/evil/issues/721#issuecomment-585950044

**Comment by bitclick** [comment] 2021-02-01 14:10
I am affected by this too..  `C-g` is not working.  `super-word-mode` does not help. As a mitigation i removed  `(modify-syntax-entry ?_ "w")` from my `init.el`  

I am on emacs27 with spacemacs develop branch and mu4e 1.4.12

**Comment by djcb** [comment] 2021-02-11 11:20
This doesn't seem like a mu4e problem, so I'm closing this. Probably best to file a bug against emacs itself, and include a `gdb` backtrace of the hanging emacs process.

**Closed by djcb** 2021-02-11 11:20 UTC
Labels: needinfo

**Comment by DiogoFerrari** [comment] 2021-02-18 23:42
This is a mu4e problem, I think. It freezes one uses `(modify-syntax-entry ?_ "w")`, but no other mode does it. I am using that locally now.

**Comment by JonathanReeve** [comment] 2023-03-04 06:11
I'm seeing this issue, although I don't have anything resembling `modify-syntax-entry` in my config.
