### ISSUE TITLE
Header view replaced by message view after executing marks

### ISSUE THREAD

**Issue by crispinb** [djcb/mu#1651] opened 2020-04-20 07:38 UTC
## Expected or desired behavior

I have the stock 'unread' search open in the header view, and one of the listed emails open in the message view.

I mark the email I'm viewing for refiling with 'r', then hit x to execute. 

Expectation is for the marked email to be refiled, and  the header view to remain visible (I'm not sure whether it's supposed to refresh according to the executed action immediately, but I would expect it to remain visible).

## Actual behavior

The header view is replaced by a message view showing the same message (ie. it's now displayed in 2 message views - the one I was viewing, and a duplicate in the window that previously contained the header view).

## Versions of mu, mu4e/emacs, operating system etc.

mu & mu4e 1.4.1
emacs 26.3
OS ubuntu 19.04

**Comment by theophilusx** [comment] 2020-04-20 10:38
Just as a comparison.....

Also on Ubuntu, Emacs 27.0.91 and mu 1.4.1

I don't see that behaviour.

When I open the message for reading and have the hader view window at
the top and the message in a window below, hit 'r' to refile the message
I see the following behaviour

1. The message is marked for refile in the header view
2. The message display view changes to the next message (and it looks
like the 'phantom' cursor in the header view also moves to the next
message, but my 'real' cursor stays in the message view window, now on
the next message)
3. When I hit 'x' to process the mark, the marked message is
refiled/archived and the header view is updated with the refiled message
removed.

**Comment by crispinb** [comment] 2020-04-20 10:52
Do you get the same (correct, or at least expected) behaviour if the message you have open for reading was the last unseen message present in the header view? That's what seems to trigger this in my case.

**Comment by theophilusx** [comment] 2020-04-20 11:12
Yep, I get the behaviour you describe if you refile the last message in
the message list. That is the vital bit to reproduce. 

-- 
Tim Cross

**Comment by michaelmrose** [comment] 2020-06-03 22:37
I get the same behavior when just marking or unmarking ANYTHING on emacs 28. Example in headers hit r item is marked and we switch to message view showing the next message.

Hit q to go back go one line up hit u to unmark bam same thing. It makes mu4e 100% impossible to use.

**Comment by djcb** [comment] 2023-08-03 20:46
Cannot reproduce this, which isn't unexpected, since many thing changed. So closing this.

**Closed by djcb** 2023-08-03 20:46 UTC
Labels: mu4e
