### ISSUE TITLE
[mu bug] Header titles not aligning

### ISSUE THREAD

**Issue by Perangelot** [djcb/mu#2276] opened 2022-06-23 19:07 UTC
**Describe the bug**
When opening the header-view, the titles of the respective header columns do not match the columns themselves; they are misaligned.

![image](https://user-images.githubusercontent.com/89665177/175376279-b9726cda-d3e6-409d-806e-d970d89c59fe.png)

Noe that this is not the same misalignment as in #1062 or in #677. In these two issues, though, you can see enough screenshots of cases where the problem occurs, and some in which it does not. 

**To Reproduce**
I cannot say how to reproduce this issue.

**Environment**
Garuda Linux, Emacs 28.1

**Checklist**
- [X] running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).
- [X] tried out `(setq mu4e-headers-precise-alignment t)`
- [X] tried out `(setq mu4e-use-fancy-chars nil)`
- [X] tried out different values for `mu4e-headers-fields`

**Comment by djcb** [comment] 2022-06-25 03:51
Can you provide two example messages (anonymized as necessary) that are showing this? Thanks.

**Comment by Perangelot** [comment] 2022-06-25 13:43
Thanks for your quick answer! I very much appreciate the work you are doing.

I'm afraid I am not quite sure what you mean by "messages" here - the actual email content or two messages not anonymized in the header view. So I'll just provide both:

![image](https://user-images.githubusercontent.com/89665177/175776009-1f7185f2-5e3a-452f-b841-d96a7d6cfd5a.png)

**Message no. 1**
```
From: Vitus Schäfftlein <vitus.schaefftlein@wwu.de>
Subject: Example Number One (very long title)
To: Vitus Schäfftlein <v_scha12@uni-muenster.de>
Date: Sat, 25 Jun 2022 15:31:41 +0200 (10 minutes, 43 seconds ago)
Flags: seen
Maildir: /Posteingang
Attachment: [2. text/plain]...

This is the first example message.
```
**Message no. 2**

```
From: Vitus Schäfftlein <vitus.schaefftlein@wwu.de>
Subject: Ex no. 2
To: vitus.schaefftlein@wwu.de
Date: Sat, 25 Jun 2022 15:32:03 +0200 (9 minutes, 37 seconds ago)
Flags: seen
Maildir: /Posteingang
Attachment: [2. text/plain]...

Example no. 2 (short)
```

Note that there are also other messages below which could create the misalignment. I have not found any variable to set how many lines are shown in the header view (`mu4e-headers-visible-lines` only works for the horizonzal-split view, which I do not use). If you need something else, please do ask. I'll help where I can.

**Comment by djcb** [comment] 2022-07-06 22:07
Ah, now I understand. You mean the message fields do not line up with the column headings; this assumes that you use the same font(-size) for both (and even that is not perfect).... so that is not going to work. 

Does the alignment work for you for some other lists, e.g `M-x package-list-packages` or `M-x proced`?

**Comment by Perangelot** [comment] 2022-07-08 07:01
Thanks for your answer! I am using the same font for both, but not the same font size. With `proced`, I don't have alignment either, but I _do_ have that alignment with `list.packages`:

![image](https://user-images.githubusercontent.com/89665177/177932750-e3a2233d-68d9-4ac0-b6fb-c7af0763209c.png)

Even changing `package-archive-column-width` to any size has the headers align. This proves that there must be a way to align the headeres with the column, irrespective of font size. I mean, basically, the header must just start right above the first letter of that column. And columns are measured by emacs. There might be some hints in `package.el` as to how to go about this.

**Comment by djcb** [comment] 2022-07-08 07:54
Ah, so I think an important difference is that `package` uses `tabulated-list` mode, which apparently takes care of this, while `proced` does not (AFAIK).

The good news there are plans (and some code) for a new mu4e headers view based on tabulated-list... the bad news is that it's going to take a while before that is ready.

**Comment by djcb** [comment] 2023-01-16 20:45
Closing this, as this is not a bug, but the expected behavior for now.

**Closed by djcb** 2023-01-16 20:45 UTC
Labels: bug, needinfo, mu
