### ISSUE TITLE
Automatic updates of mu4e-headers when a message is open

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1397] opened 2019-03-21 19:06 UTC
I have a filter in mu4e that shows me all unread messages. If open an unread message, the message is correctly marked as read. However, if I wait a few seconds (my `mu4e-update-interval` is 60) the header view is refreshed and the message disappears from the list. This is especially disruptive in the following scenario:
- I open an unread message from my list of unread messages
- While reading the message the message disappears from the header view.
- I then decide to move the message to some other place. The message is gone from the header view so I try to move the message by calling `mu4e-headers-mark-for-move` in the message view but get an error that the message is no longer in the header view.

Is there a way to disable automatic updates to a view? I noticed that if I mark a message in a header view, all future updates do not affect the header view.

**Comment by kevinjfoley** [comment] 2019-03-24 13:52
You could set `mu4e-headers-auto-update` to nil which would prevent the update from refreshing the headers buffer.

> The message is gone from the header view so I try to move the message by calling mu4e-headers-mark-for-move in the message view

I believe you should be calling `mu4e-view-mark-for-move` if you're calling it from the message.  That should be bound to `m` by default in `*mu4e-view*` and shouldn't be affected by the message no longer being in the header buffer.

**Comment by djcb** [comment] 2020-03-11 18:53
Thanks for the report; It's a know problem... duplicate of #1055.

**Closed by djcb** 2020-03-11 18:53 UTC
