### ISSUE TITLE
[mu4e bug] From/To entry sometimes missing in headers

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#2243] opened 2022-05-01 14:00 UTC
**Describe the bug**
On current master (b686c9da25a77f5db1385748f3442d2a769ddcb4), in the headers view, I noticed several threads lack the From/To field. It's just blank.

However, if you select the message, the correct From/To is shown.

This happens irregardless if the threading setting is on or off, and I cannot pinpoint an exact reason as of why this happens. On the cli, the from is always visible.

**To Reproduce**
I've noticed this mostly happens with github notifications, which I hope you have plenty already ;)

**Environment**
GNU Emacs 29.0.50 (debian unstable)

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by wavexx** [comment] 2022-05-01 14:05
Seems like the problem is with the ``:from`` field (``:from-or-to`` behaves the same).
In one instance where this shows, I have:

``From: "stale[bot]" <notifications@github.com>``

Maybe the [] in the name? Another case is from messages in the mu mailing list itself, such as the message-id ``<6e636663-1c57-46db-8bd3-2af2fb9974dbn@googlegroups.com>``

In that case, the From name includes "phil..." (3 dots).

**Comment by nils-schween** [comment] 2022-05-02 07:05
I am experiencing the same issue with latest commit on the master branch.

**Comment by theophilusx** [comment] 2022-05-02 09:07
nils-schween ***@***.***> writes:

> I am experiencing the same issue with latest commit on the master branch.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

I too am seeing this on some messages - looks like ones which have a
particularly long from line, but that is just a guess.

**Comment by wavexx** [comment] 2022-05-02 09:28
I can reliably get this with any "From" containing square brackets.

**Comment by djcb** [comment] 2022-05-06 20:23
Can you reproduce with the latest (_many_ things have changed)? The `stale[bot]` seems to work just fine.

**Comment by theophilusx** [comment] 2022-05-07 06:01
"Dirk-Jan C. Binnema" ***@***.***> writes:

> Can you reproduce with the latest (many things have changed)? The stale[bot] seems to work just fine.
>

I don't seem to be seeing this issue anymore. However, I also notice
that there is no longer any entries under the 'list' column -
previously, this would show mail list names for messages from mail
lists.

**Comment by djcb** [comment] 2022-05-07 13:16
Thanks! Okay closing this one then. Re: the list thing; that was reported as #2246 and fixed as well.

**Closed by djcb** 2022-05-07 13:16 UTC
Labels: bug, needinfo, mu4e
