### ISSUE TITLE
mu4e very slow loading buffer even though mu is fast

### ISSUE THREAD

**Issue by titaniumbones** [djcb/mu#1326] opened 2018-10-06 02:31 UTC
## Expected or desired behavior
- start mu4e for the first time in an emacs session
- open bookmark, e.g. `("maildir:/inbox AND NOT (contact:notifications@github.com OR contact:noreply@github.com OR contact:builds@travis-ci.com OR contact:builds@travis-ci.org) AND NOT flag:trashed" "non-github msgs in Inbox" 105)`
- all headers (~6k) should load quickly, and it should be possible to open an individual message right away.

## Actual behavior

- start mu4e for the first time
- loading headers takes over 2 minutes
- during this time, messages will not load in the `*mu4e-view*` buffer.

`time mu find -r "maildir:/inbox AND NOT (contact:notifications@github.com OR contact:noreply@github.com OR contact:builds@travis-ci.com OR contact:builds@travis-ci.org) AND NOT flag:trashed"` returns 

`mu find -r   0.49s user 0.60s system 56% cpu 1.933 total` 

## Versions of mu, mu4e/emacs, operating system etc.

I'm using:
- Arch Linux, up to date
- recent emacs-git
- mu 1.0.3 from package (but seeing the same thing on v1.0 tag from git; unable to compile from paster so not sure whether behaviour is still present there

## Any other detail

I know this could be more detailed but please let me know what else I should include. Thank you!

**Comment by djcb** [comment] 2018-10-09 04:56
Hmmm.... so something specific to the first mu4e load. Do you happen to have a lot of contacts? I.e. `M-: (hash-table-count mu4e~contacts)`.

**Comment by titaniumbones** [comment] 2018-10-09 10:39
`(hash-table-count mu4e~contacts)` gives "6332". I don't **think** this is the issue since the contacts load quickly when I start mu4e; the delay comes when I open a bookmark or maildir.  I think it is actually not specific to the first load, but also whenever a search is refreshed with `mu4e-update-mail-and-index`.  Harder for me to get good numbers on this, but often when I try to view a message mu4e hangs with `Waiting for message...` I believe the delay is usually a bit shorter, but I am not sure how to get good numbers on this. Just now I just manually triggered `mu4e-update-mail-and-index` and waited for a message to appear i nthe view buffer; it took about 28 seconds, which seems long.  And there is a final ficker of the headers buffer about 50 seconds later, which may be the buffer completing its load.

I'm not seeing a lot of strange stuff in my config.  I have this for contacts: 

```emacs-lisp
  (setq mwp/contact-blacklist-file "/home/matt/.mu/contact-blacklist")
  (defun mwp/read-contact-blacklist ()
     "Return a list of blacklisted email addresses"
     (with-temp-buffer
       (insert-file-contents mwp/contact-blacklist-file)
       (split-string (buffer-string) "\n" t)))

   (defun mwp/make-contact-blacklist-regexp ()
     "Combine listed addresses into a regexp"
     (mapconcat 'identity (mwp/read-contact-blacklist) "\\|"))

   (setq mu4e-compose-complete-ignore-address-regexp (mwp/make-contact-blacklist-regexp)) 
```

and this tagging code (which I actually never use b/c search is so good)
```emacs-lisp
(add-to-list 'mu4e-marks
  '(tag
     :char       "g"
     :prompt     "gtag"
     :ask-target (lambda () (read-string "What tag do you want to add?"))
     :action      (lambda (docid msg target)
                    (mu4e-action-retag-message msg (concat "+" target)))))

(mu4e~headers-defun-mark-for tag)
(define-key mu4e-headers-mode-map (kbd "g") 'mu4e-headers-mark-for-tag)
```
I'm not seeing a whole lot else beyond the usual folder setup, etc.  I use offlineimap to retrieve mail, too.

Thanks @djcb  for your help!

**Comment by titaniumbones** [comment] 2018-10-09 17:27
Also maybe I should say that by adidng this to my mode-line: 
```emacs-lisp
(setq-default mode-line-front-space
              (append mode-line-front-space '((:eval (format "/%s" (line-number-at-pos (point-max)))))))
```
I can watch the length of the buffer change fairly slowly after a reload. So it seems like the loading of each individual message is somewhat slow. I'm not sure what might cause this.  Using the built-in profiler I get the following results (screenshot only -- not sure how to save this in a useful format):

![screenshot from 2018-10-09 13-20-56](https://user-images.githubusercontent.com/364340/46686488-71eb2880-cbc6-11e8-89ea-6c326ee9c572.png)

I'm not very familiar with profiling or with what kind of numbers would be good or bad. Is it possible there 's a hook somewhere that's slowing things down?

**Comment by titaniumbones** [comment] 2018-10-09 22:45
One more screenshot -- sorry for the noise -- during a refresh (in this case turning on threading and include-related) htop shows emacs pinned at about 100% of CPU and `mu server` at around 15-20% : 
![screenshot from 2018-10-09 18-43-28](https://user-images.githubusercontent.com/364340/46703003-4e8aa280-cbf3-11e8-8224-421bbd5550ec.png) (see the highlighted line). 

Not sure if that helps?

**Comment by titaniumbones** [comment] 2018-10-10 00:19
One more profiler output, of a different run.  Not sure how to interpret this: 

```
- mu4e~proc-filter                                               8812  40%
 - mu4e~headers-header-handler                                   4388  19%
  - mu4e~message-header-description                              3983  18%
   - mapconcat                                                   3761  17%
    + #<compiled 0x17a34bd>                                      3721  16%
     mu4e~headers-line-apply-flag-face                             43   0%
    mu4e-get-headers-buffer                                        45   0%
 - mu4e~headers-view-handler                                      882   4%
  - mu4e-view                                                     882   4%
   + mu4e~view-internal                                           882   4%
 + mu4e~fill-contacts                                             311   1%
 + mu4e-info-handler                                               74   0%
 + mu4e~headers-found-handler                                       9   0%
 + #<lambda 0x2355af179>                                            3   0%
- redisplay_internal (C function)                                5961  27%
 - eval                                                          5354  24%
  + format                                                       4774  21%
  + if                                                            240   1%
  + concat                                                        115   0%
  + unless                                                         76   0%
  + mode-line-eol-desc                                             23   0%
    replace-regexp-in-string                                        3   0%
 + #<compiled 0x3c7d29>                                           168   0%
   file-remote-p                                                  146   0%
 + mode-line-default-help-echo                                    117   0%
   menu-bar-update-buffers                                          3   0%
- ...                                                            3066  13%
   Automatic GC                                                  3062  13%
 - shr-collect-extra-strings-in-table                               4   0%
  + shr-collect-extra-strings-in-table                              4   0%
- timer-event-handler                                            2775  12%
 + apply                                                         2746  12%
   timer-inc-time                                                  10   0%
   timerp                                                           4   0%
   timer-until                                                      4   0%
 + timer-activate                                                   3   0%
   cancel-timer-internal                                            3   0%
+ command-execute                                                1367   6%
+ mu4e~update-sentinel-func                                         4   0%
  guide-key/close-guide-buffer                                      4   0%
+ winner-save-old-configurations                                    1   0%
```

**Comment by stardiviner** [comment] 2018-10-29 10:04
Maybe you can try `M-x elp-instruct-package RET mu4e RET` to profile to get a different benchmarking result.

**Comment by djcb** [comment] 2019-01-14 19:11
I've merged PR #1294 which does help to significantly speed up some cases... perhaps it helps here, too... can you try it?

**Comment by systemfreund** [comment] 2019-02-18 21:07
I can confirm i have a similar issue. In my case it only seems to be slow when i initially open a bookmark or jump directly to a maildir:

- `M-x mu4e`
- `j inbox<RET>`
- mu4e-headers view appears, but no headers yet, just the string "Searching..."
- after a few seconds the headers appear

**Comment by djcb** [comment] 2019-02-24 16:13
When it only happens at startup, it's problably just that mu4e is still receiving contact-info from the mu-server.

**Comment by recrist** [comment] 2019-02-28 04:12
I’m having the same issue as well. Jumping to the inbox results in a delay of several minutes. It seems to be mostly specific to the inbox, other boolmarks usually load instantly. Listing the same inbox on the command line with mu is always instantaneous as well. So, it seems to be a problem specific to mu4e.

**Comment by djcb** [comment] 2019-02-28 06:31
@recrist: several _minutes_, really? Does this happen each time you go the inbox or only at startup? Are you using mu4e from git? What platform are you on?

**Comment by recrist** [comment] 2019-03-01 04:36
Yes, minutes. Every time I open the inbox in Mu4e. It does eventually list the message headers but it takes several minutes. I’m running the version included with mu through homebrew. Away from my computer right now but I will provide more complete information when I get back to it. It’s very strange behavior because other folders (e.g., trash) list instantly.

**Comment by recrist** [comment] 2019-03-01 14:27
Hi. Here's a little more information. 

- macOS 10.14.3

- GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30

- As I mentioned above, I installed mu with homebrew, which I assume is grabbing the git package. I can't find any really clear version information, but it is installed in a subdirectory named "1.0_1." The latest entry in the NEWS.org file reads:  "1.0 After a decade of development, *mu 1.0*! Note: the new release requires a C++14 capable compiler."

- I'm a new emacs user and it is certainly possible that I have done something stupid to cause the problem. However, mu itself works great outside of emacs and everything inside of emacs seems to work accept jumping to the inbox. So, it seems like most of my configuration is working as expected.

- I am happy to provide any other information that I can to help track down the problem. I'd love to be able to use the package, but right now it's not really functional for me.

**Comment by djcb** [comment] 2019-03-02 10:14
@recrist -- So, if it takes minutes to go the inbox, at least that gives some time to see what's going on.
 
In mu4e, 'opening the inbox' is just a query which basically says 'list alls messages with the property that they live in the maildir that we've designated as inbox". In other words, there's nothing "special" about the inbox that could explain this.

Or are you using some custom / third-party extensions for mu4e? How many messages are there in your Inbox? And overall? 

And can you try setting
```
(setq
   mu4e-headers-show-thread nil
   mu4e-headers-include-related nil)
```
in your configuration and then try mu4e again? Thanks.

**Comment by recrist** [comment] 2019-03-03 16:14
There are just over 70000 messages in my inbox and around 170000 in the Maildir directory. 

Hi. I tried running "mu index --rebuild" and that seems to have sped things up a bit. I just roughly timed  jumping to the inbox in mu4e at about 1'45". That's still very slow compared to the roughly 12" that it takes using mu on the command line. 

I just started trying to use the package and I don't think there is anything special about my configuration. Here is everything related to mu4e from my config file.

(add-to-list 'load-path (expand-file-name "~/rcfiles/emacsd/mu4e"))
;; require mu4e
(require 'mu4e)
;; use mu4e for e-mail in emacs
(setq mail-user-agent 'mu4e-user-agent)
;; tell mu4e where my Maildir is
(setq mu4e-maildir "~/Maildir")
;; use mbsync to get mail
(setq mu4e-get-mail-command "mbsync -a")
(setq mu4e-update-interval 300) 
;; use w3m for html rendering
(setq mu4e-html2text-command "w3m -T text/html")
;; let gmail handle sent mail
(setq mu4e-sent-messages-behavior 'delete)
(setq mu4e-change-filenames-when-moving t)
;;An attempt to make changing mailboxes faster
(setq
  mu4e-index-cleanup nil      ;; don't do a full cleanup check
  mu4e-index-lazy-check t)    ;; don't consider up-to-date dirs
(setq
   mu4e-headers-show-thread nil
   mu4e-headers-include-related nil)

(setq mu4e-drafts-folder "/gmail/drafts")
(setq mu4e-sent-folder "/gmail/sent")
(setq mu4e-trash-folder "/gmail/trash")

I don't think that turning off show-thread and include-related made any difference.

Thank you very much for trying to help me track down the problem. I appreciate it.

**Comment by djcb** [comment] 2019-03-03 20:24
Hmm... `mu4e-maildir` should be the absolute file-system path to your Maildir. Do you really have a root-level `/Maildir`? Otherwise, I'm not sure how it would even work. Perhaps use `~/Maildir ` instead? Not sure how this could be related to the speed issue, but... 

Otherwise.. 
  ```mu find maildir:/gmail/inbox --include-related --threads -n 500``` 
should be the equivalent of what mu4e does (assuming your inbox can be found as `/gmail/inbox`. Is that very slow?

You could try `(setq mu4e-headers-results-limit 100)` and see if that makes a difference.

But really, I'd be interested in what's happening during the minute(s) mu4e is waiting to show anything. Is either `emacs` or `mu` very busy (as per e.g. `top` or `htop)?

**Comment by recrist** [comment] 2019-03-03 21:54
I don't know why but the "~" character seems to have been lost when I pasted into the message above.  The path in my config file was actually "~/Maildir". I changed it to an absolute path. 

Since you mention this, I wonder if it matters that I'm using a symlink in my emac.d directory to the actual location of all the mu4e files. Is there some reason that that would make a difference?

Running "time mu find maildir:/gmail/inbox --include-related --threads -n 500" returns:
real	0m39.379s
user	0m31.511s
sys	0m7.267s

Watching top while running either mu or mu4e shows that it's using 100% of the cpu for the duration of the waiting time.

I did put (setq mu4e-headers-results-limit 100) into my config file. Both running mu from the command line and mu4e now seem to take about 30 seconds.

**Comment by djcb** [comment] 2019-03-04 20:28
And what about `time mu find maildir:/gmail/inbox  -n 500`?

If you don't do so already, you want to mu from git, which has a few changes that make threaded/related search much faster.

**Comment by recrist** [comment] 2019-03-05 01:02
Much faster. "time mu find maildir:/gmail/inbox -n 500?" gives:
real	0m0.245s
user	0m0.069s
sys	0m0.093s

I have not tried grabbing mu directly from git but I will and I'll let you know if it makes any difference.

Thanks again for all your help.

**Comment by gusbrs** [comment] 2019-06-10 17:13
@djcb I can report I had been facing a similar issue and what I found out about it. I also was meeting a small delay (some seconds, let's say 3-4) on the start of mu4e, and if I went straight to a bookmark, it'd be "searching..." for a while. And I believe your guess (https://github.com/djcb/mu/issues/1326#issuecomment-466790462) is correct, that it has to do with contact info. As I tried to boil down what was going on, I ran `mu cfind` on the terminal, to find out it was fast, so it could not be the culprit. Examining the relevant functions, I believe (at least for me) the problem to be the _sorting_ of contacts done by mu4e, not the extraction done by mu. I managed to get a very good compromise by reducing the timespan of contact info for the last three years (it went from ~9k contacts to ~3k, and startup time from ~3-4s to faster than I can reach for the bookmark).

**Comment by djcb** [comment] 2019-06-10 18:58
@gusbrs ah, good to hear -- at least in the git version, the sorting is now done on the server side (in c) and should be bit faster; moreover, we only send the _changed_ contacts to mu4e, which should help with subsequent contact updates.

**Comment by gusbrs** [comment] 2019-06-10 19:31
@djcb That's good news. Indeed (forgot to mention, sorry) I'm using the released 1.2 version. Hopefully I'll get to this improvement in due time, though I'm quite happy with how things are set up here.

Btw, I'm some months into `mu4e` now, and I believe I've really fallen for it. So I also leave my warmest thank you!

**Comment by djcb** [comment] 2020-02-27 21:04
Okay, thanks all! Closing this now, as it seems to have been resolved. If you can still reproduce with 1.3.x, please file a new issue. 

Note that one other thing might be retrieving / indexing mail at startup. If the latter takes a long time, that may explain the delays.

**Closed by djcb** 2020-02-27 21:04 UTC
Labels: needinfo

**Comment by choppsv1** [comment] 2020-03-08 23:16
I'm seeing incredibly slow behavior but only under OS X, I'm trying with homebrew using --HEAD (HEAD-59fb743_1) and emacs 26.3. I think it's something with "mu server"

I see the "mu server" process taking huge amount of CPU time, the results are not displayed to emacs for quite a while (didn't time but way longer (at least a magnitude) than under linux running on the same system in a VM). This is on a new macbook pro 16 (octocore cpu).

I did a sample a few times on the mu server process in activity monitor and it seems to be doing one of the following (or some similar branch) each time I run the sampler:

![image](https://user-images.githubusercontent.com/3074665/76172954-2d740b80-6171-11ea-9a36-519497b2d9f6.png)

![image](https://user-images.githubusercontent.com/3074665/76172881-77a8bd00-6170-11ea-9423-39cf01238270.png)

Is mu server doing something that OS X is really bad at file system wise maybe?

**Comment by djcb** [comment] 2020-03-09 13:08
From that, it seems `access` is quite heavy, as part of the 'cleanup'. It shouldn't though; is there something special with the filesystem?

Anyway, you can try `(setq mu4e-index-cleanup nil)` which would avoid this cleanup part.

**Comment by choppsv1** [comment] 2020-03-09 13:27
To collect info:

```
(default) [09:24:05 stubbs:~/Mail]$ df .
Filesystem    1K-blocks      Used  Available Capacity iused       ifree %iused  Mounted on
/dev/disk1s1 1953901876 628653916 1311720864    33% 5145599 19533873161    0%   /System/Volumes/Data
(default) [09:24:07 stubbs:~/Mail]$ pwd
/Users/chopps/Mail
```

and the format is
"   1:                APFS Volume AppleHD - Data          643.7 GB   disk1s1"

FWIW, this is the default setup from Apple for user dir (documents etc) on the SSD.

I'll see if I can look at the code/etc to determine why its so slow, as honestly OSX feels slower with most comparable things than the archlinux VM I'm running inside it.

**Comment by choppsv1** [comment] 2020-03-09 13:36
`(setq mu4e-index-cleanup nil)` makes things *way* faster (like 2 seconds vs 15+ seconds). I also have been playing with different versions, instead of HEAD or 1.2 (the homebrew version) I created my own tap in homebrew and grab the 1.3.5 tag. That is definitely faster than 1.2 (I think that was expected) but still slow (15+seconds with the cleanup). The HEAD version I think has other issues for me I don't think it ever completes in emacs (i.e., the list never shows up).
