### ISSUE TITLE
Attached images are not displayed when I open a msg for the first time

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#447] opened 2014-06-26 07:08 UTC
When I close the message and reopen, I can see them.  I use mu4e in single-window mode instead of split-view.

**Comment by NicolasPetton** [comment] 2015-06-03 13:55
I have the exact same issue.

**Comment by djcb** [comment] 2015-06-07 10:15
I can usually see pics the first time, but I've seen the case where you need to reopen a message.. mu4e is not doing anything different/special when you reopen; it might be some caching issue inside emacs itself.

**Comment by djcb** [comment] 2016-02-21 08:18
I can't reproduce this anymore; if you can please specify the versions of mu4e and emacs you are using, and the OS. Also, does this always happen for all messages containing images?

Note, `mu4e-view-show-images` does not apply when you use mu4e-html2text-command.

**Comment by tmalsburg** [comment] 2016-02-21 21:17
I can't reproduce it with relatively recent development versions of mu/mu4e and Emacs.  Hooray!  In earlier versions, it happened pretty much always for bigger images and sometimes for smaller images (I think).

As far as I'm concerned we can close this issue.

**Comment by djcb** [comment] 2016-02-23 21:33
I never got to the bottom of this. I suspect it might be related to the version of emacs, or perhaps  the version of the imagemagick library. We didn't do any changes for this.

I'll close it for now, hope it's finally gone now!

**Comment by tmalsburg** [comment] 2016-02-29 19:04
Unfortunately, I just received two emails that trigger this problem, so perhaps we can reopen this issue.

**Comment by djcb** [comment] 2016-03-05 06:14
Got one as well...

**Comment by Chris00** [comment] 2016-12-18 15:05
Something I do not understand in this respect is: `mu4e~view-show-images-maybe` does not try to save the images but `mu4e~write-body-to-html` saves them to disk if `(plist-get attachment :temp)` is nil.  Why such a difference between the two functions?  Shouldn't there be a function that gets the filename of an image, saving it if needed?

**Comment by kepi** [comment] 2017-05-04 22:49
Same behaviour here every time. This week I discovered that same behavior is with PDF previews (I even didn't know I can have those :D)

**Comment by wavexx** [comment] 2017-08-15 12:04
I always had this problem which has been very consistent for me: all attached images require a refresh to be shown, along with #876.

By pure chance I recently discovered that with #1111 (which I've been using since), both this and gpg attachments are now shown correctly on the first go. Unfortunately I'm running with emacs from master, with debian unstable (which a recent version of gpg as well to booth), so I'm not entirely sure what (and if something) fixed it by chance.

Can anybody with gmime 3 give it a test?

**Comment by jgoerzen** [comment] 2017-10-16 13:45
This is 100% repeatable for me.  mu4e 0.9.18, emacs 25.1.  I am happy to help debug if this would be useful.  Let me know what you'd need me to do.

**Comment by jgoerzen** [comment] 2017-10-16 17:20
https://groups.google.com/d/msg/mu-discuss/swrh1cuhpzo/ZDc1gQ-sBQAJ has a workaround, incidentally

**Comment by wavexx** [comment] 2018-01-27 10:59
Uhm, at least since commit 82743b3164aa674359ce3da835d99f55c4847341 this problem disappeared for me. Both attachments and gpg messages are decrypted on the first view. Can anybody confirm?

**Comment by joostkremers** [comment] 2018-01-31 14:37
Just did a git pull and recompiled, but still no go. I tested by sending myself an email with a picture attachment. It's not displayed the first time I open the message, it's displayed fine the second time I open it.

When I open the sent mail in my Sent folder, the image is displayed without problems the first time. It's just with the new mail in my inbox that I'm (still 😞) having trouble.

**Comment by wavexx** [comment] 2018-01-31 14:52
On Wed, Jan 31 2018, Joost Kremers wrote:
> Just did a git pull and recompiled, but still no go. I tested by
> sending myself an email with a picture attachment. It's not displayed
> the first time I open the message, it's displayed fine the second time
> I open it.

It's really odd. I mentioned before this issue somehow got away in the
gmime-3 branch, and similarly it disappeared for me now for the regular
branch.

I still have some odd issues with the view hook occasionally, so I
suspect something else is influencing this, but I didn't have time to
dig deep into it unfortunately.

**Comment by tangxinfa** [comment] 2018-04-24 05:27
I have a fix https://github.com/djcb/mu/pull/1231, please verify if it can fix your problem

**Comment by djcb** [comment] 2018-06-11 18:38
Ok, thanks to @tangxinfa's analysis, this has finally been fixed!

**Closed by djcb** 2018-06-11 18:38 UTC
