### ISSUE TITLE
[mu4e bug] Cannot reply to or forward certain html emails.  I think these are emails with images.  

### ISSUE THREAD

**Issue by kourosh2** [djcb/mu#2510] opened 2023-07-04 20:20 UTC
**Describe the bug**
Cannot reply to or forward certain html emails.  I think these are emails with images.  I get an error with invalid image type 'svg'.

**How to Reproduce**
When trying to forward or reply to (hitting "F" or "R" in either header view or message view) to these emails, I get the following error.
```
error in process filter: image-type: Invalid image type ‘svg’
error in process filter: Invalid image type ‘svg’
```
An example of such message is attached as a zip file.

**Environment**
- macOS Ventura 13.4.1
- mu/mu4e 1.10.4
- GNU Emacs 28.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2022-09-12

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

[example.eml.zip](https://github.com/djcb/mu/files/11952130/example.eml.zip)

**Comment by djcb** [comment] 2023-07-04 21:56
Hmmm, I cannot reproduce; and the example doesn't seem to have any attachments and/or svg images; anyway, I think it's a known problem with emacs on MacOS:
https://emacs.stackexchange.com/questions/74289/emacs-28-2-error-in-macos-ventura-image-type-invalid-image-type-svg

So not much mu4e can do about this. So I'm closing this, hope you can find a solution from that thread.

**Closed by djcb** 2023-07-04 21:56 UTC
Labels: bug, mu4e, new

**Comment by kourosh2** [comment] 2023-07-04 22:58
Thanks for the pointer.  For someone else who might have the same problem, one of the comments from the referenced stackexchange post worked for me.  I added the following to my config and it did the trick.
```
(add-to-list 'image-types 'svg)
````
