### ISSUE TITLE
[mu4e bug] Displaying the headers sometimes takes a long time

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2320] opened 2022-08-13 19:40 UTC
**Describe the bug**

Displaying the headers buffer after fetching mail sometimes takes several seconds (15 in the screenshot below):
![mu4e](https://user-images.githubusercontent.com/1255665/184508277-f54bf631-52a2-45dc-81b1-5bac25d2d3af.png)

**How to Reproduce**

Unfortunately I do not have a clear way to reproduce that (it does not happen systematically when fetching email).

**Environment**
OS: Debian GNU/Linux
Emacs: 27.1
mu/mu4e: commit 6fdc20ae

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [x] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [x] you have read all of the above

**Comment by djcb** [comment] 2022-08-20 10:38
Likely, this is during indexing? If so, that's somewhat expected.

**Comment by dcolascione** [comment] 2022-12-31 16:10
Is there anything that would be helpful in debugging this problem?

**Comment by djcb** [comment] 2023-01-29 14:33
One thing that might help diagnosing further (and assuming `journalctl` here, change as needed):
- run a recent 1.9 version (>= 1.9.17 or so should do)
- run mu4e with `(setq mu4e-mu-debug t)`
- after using mu4e  for a while, including some case where things take longer than expected, do:
```
$ journalctl -b _COMM="mu" | grep "sw:"
```
Sources/mu % journalctl -b _COMM="mu" | grep "sw:"
Found existing alias for "journalctl". You should use: "jc"
Jan 29 08:12:32 evergrey mu[4674]: sw: ran query 'maildir:"/inbox"'; related: yes; threads: yes; max-size: 500: finished after 473 us
Jan 29 08:12:32 evergrey mu[4674]: sw: find_handler (indexing: no): finished after 613 us
[...]
Jan 29 08:17:17 evergrey mu[4674]: sw: indexing: finished after 2,7 s
[...]
Jan 29 10:18:03 evergrey mu[26439]: sw: view_handler (indexing: no): finished after 7,3 ms
[...]
Jan 29 16:30:34 evergrey mu[103688]: sw: ran query 'flag:unread AND NOT flag:trashed'; related: yes; threads: yes; max-size: 500: finished after 283,9 ms
Jan 29 16:30:35 evergrey mu[103688]: sw: find_handler (indexing: yes): finished after 1389,6 ms
```

An interesting case would be when you're indexing and finding/viewing at  the same time in the above you see such a case at 16:30:35, finding is quite a bit slower, but in absolute terms, 1.3s is still reasonable I think

**Comment by djcb** [comment] 2023-08-04 20:55
Note, I've pushed a bunch of optimizations to `master` which make querying  / showing results a _lot_ faster. Of course, this ticket is about _worst_ case performance.

Anyway, if this still happens: please check according the Jan 29 notes. A reindexing job shouldn't take very long in most cases, and and queries not much longer. But I can't reproduce this, so I need a bit of analysis, in particular how long re-indexing takes.

**Comment by djcb** [comment] 2023-08-06 14:06
I tested with doing a full indexing run (about 1.5 min) and during that time, I can use `mu4e` with queries etc., with hardly noticeable delay.

**Comment by Chris00** [comment] 2023-08-07 07:36
I am running it and it is noticeably faster (way < 1ms/msg).  Thanks!

**Comment by djcb** [comment] 2023-11-16 09:51
Overall, `mu` 1.11.x searching is quite a bit faster than 1.10; and I cannot reproduce any of the cases where it suddenly slows down; anyway, there's not much more to do here, so closing this.

If you still see slowdowns, feel free to open a new ticket, but please with the details as mentioned in the Jan 6 / Jan 29 comments here- thanks!

**Closed by djcb** 2023-11-16 09:51 UTC
Labels: bug, needinfo, mu4e
