### ISSUE TITLE
mu4e fails for messages with long paragraphs beginning "( http://blah" when variable `fill-nobreak-predicate` includes `fill-single-char-nobreak-p`

### ISSUE THREAD

**Issue by cacology** [djcb/mu#2237] opened 2022-04-21 15:51 UTC
**Describe the bug**
On certain messages, `mu4e-headers-view-message` would throw an error beep, give the raw gnus version of the message, and send `fill-nobreak-p: Beginning of buffer` to `*messages*`.  [EDIT: and variable `fill-nobreak-predicate` includes `fill-single-char-nobreak-p`]

I debugged it to `gnus-article-fill-cited-long-lines` which eventually called `fill-move-to-break-point` on a narrowed buffer for a paragraph.  The offending buffer is of the form,

```
( blah blah blah
```

You can reproduce the error by creating a new buffer, beginning it with `( blah` and calling `(fill-move-to-break-point (point))` at `(point)` 1.

The issue seems to be messages of the form,

```
( http://blahblahblahblah_for_a_very_long_url_consuming_several_lines_etcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetcetc
```
Note the space between the left parentheses and the beginning of the `http`.  Gnus is reluctant to break the http, so gives a long line unbroken and that barfs on `gnus-article-fill-cited-long-lines`

**To Reproduce**

Send yourself a message in mu4e of the form,

```
Hi, this will barf

( http://blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
```
**Note the space between the parentheses and the http, but that the last line begins `( http://blahblah` without a line break.**

This triggers the error consistently for me.  A short paragraph does not.

I think this might need a tiny bit more debugging, but this is as far as I can get it.

**Environment**
- MacOS 12.3.1
- emacs-plus@28 from homebrew built as "GNU Emacs 28.1 (build 2, aarch64-apple-darwin21.4.0, NS appkit-2113.40 Version 12.3.1 (Build 21E258)) of 2022-04-19"
- mu4e - mu for emacs version 1.6.10
- variable `fill-nobreak-predicate` includes `fill-single-char-nobreak-p` [EDIT: added this after initial post. This variable is crucial to reproduce the error and seems to be the source.]

**Checklist**
- [X] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [X] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by cacology** [comment] 2022-04-21 15:55
A quick follow-on, I can fix this locally by adjusting the variable `fill-nobreak-predicate` to exclude `fill-single-char-nobreak-p`.  I'll add that bit of important context above as part of the setup

**Comment by djcb** [comment] 2022-04-29 22:44
Can you attach a message that shows this problem? Thanks.

**Comment by cacology** [comment] 2022-05-01 21:27
Sure!  Here's the `*mu4e-raw-view*`

```
Return-Path: <jpa4q@virginia.edu>
Received: from grumpy-air.local ([193.148.18.58])
        by smtp.gmail.com with ESMTPSA id j9-20020ac85509000000b002f39b99f6absm3088641qtq.69.2022.05.01.14.17.24
        for <jpa4q@virginia.edu>
        (version=TLS1_3 cipher=TLS_CHACHA20_POLY1305_SHA256 bits=256/256);
        Sun, 01 May 2022 14:17:25 -0700 (PDT)
Received: by grumpy-air.local (Postfix, from userid 503)
	id 7ECF352F14EA; Sun,  1 May 2022 17:17:23 -0400 (EDT)
User-agent: mu4e 1.6.10; emacs 28.1
From: =?utf-8?Q?J=2E=E2=80=AFP=2E_Ascher?= <jpa4q@virginia.edu>
To: "jpa4q@virginia.edu" <jpa4q@virginia.edu>
Subject: Bad message
Date: Sun, 01 May 2022 17:15:51 -0400
Message-ID: <m0y1zlneak.fsf@virginia.edu>
MIME-Version: 1.0
Content-Type: text/plain
X-TUID: s+KieBbqJALQ

Hi, this will barf

( http://blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
```
[1651439912.53842_1.grumpy-air,U=14447:2,S.txt](https://github.com/djcb/mu/files/8599774/1651439912.53842_1.grumpy-air.U.14447.2.S.txt)

**Comment by cacology** [comment] 2022-05-04 12:14
Here's an email in the wild that causes the error.  Forgive the [snip]s, but I've left out other people's private emails.

The offending link is the result of passing a long URL back and forth enough to accrue safelink redirects and `>` quotes.

## Headers (I think unrelated to the problem)
```
Delivered-To: jpa4q@goog.email.virginia.edu
Received: by 2002:a59:ca41:0:b0:2a6:7661:85c2 with SMTP id v1csp502136vqt;
        Sat, 2 Apr 2022 10:41:59 -0700 (PDT)
X-Google-Smtp-Source: ABdhPJy0yuV4BiUjO4QxR+6IvhAAMJkVu0Ql0Z+lQebN7ZKZhQwTNQW8LRO6HHzwrprmflsbs3hj
X-Received: by 2002:a05:620a:2847:b0:67b:9886:f6f with SMTP id h7-20020a05620a284700b0067b98860f6fmr10091832qkp.577.1648921319000;
        Sat, 02 Apr 2022 10:41:59 -0700 (PDT)
ARC-Seal: i=2; a=rsa-sha256; t=1648921318; cv=pass;
        d=google.com; s=arc-20160816;
        b=nCdQefzhJ62ARaZyHEIAWhdpyhA+U7mns9LmjT2wANczXDiulQbl4ycpahiahokV6F
         vttHtc+41tIFshfSuKQ0RhO/wAfCBq6O3fvpzQAmdWIZgSSf6AIj6g9Ijm2zNABrjRNx
         mefJ1EmlvfX0C5UZ3e2n+25Ul3MJJIG+0MpC0pB2w6lsXb8DYtW4F3KSRchi8gflK1fo
         E4+94k8Z96aXu1AF65wCX747+SSC1/xTlclViLzCPPn+Qen8sKQ/Gvzr/JPgFMuF4AJh
         VrNZfRuoJIShu6HmjkHVRrhS3rdHME47z+QBPpm1CmZ+xdOxrV/dUs9aUbB7nNZzzAGM
         Nzdg==
ARC-Message-Signature: i=2; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=mime-version:suggested_attachment_session_id:content-language
         :accept-language:in-reply-to:references:message-id:date:thread-index
         :thread-topic:subject:to:from:dkim-signature;
        bh=moW9X4ldOzD+pUMT462Wrse3LN/+UeqTXV5TLF2fEZY=;
        b=VOwj4MvsLUI6WUTndHX7c7xE0FBeMuhCxhwHgGgZ0vPmp1OEh58Q5TYsxrEDwpl+ka
         JkcCBNU8fra7jpOMIhqc8e7zYLX8WbNBXH7wPNVyyKlZyxrab5XJ668eShdT27SKVQnj
         NPZu8zwmCBI6gLUMxuheNKyzz5cIGULzFJNYpn82nYWzG7+GmKu9xdGa8ZOkHzCU4cqF
         /kiS7EbJxGAr/h/fAkzaNgKN7h3/gVubHAnLtM4tHpnDfPqasal1vxZlvMNFRZzUEFth
         GASbMcfR3cAz7sub7Ed1eYwG0O0UJ2hKyAJEs2SD3d5lrK9ZUkBoD+eCn2dsQoc/Ivtq
         Br5w==
ARC-Authentication-Results: i=2; mx.google.com;
       dkim=pass header.i=@princeton.edu header.s=selector2 header.b=pb0fhqw8;
       arc=pass (i=1 spf=pass spfdomain=princeton.edu dkim=pass dkdomain=princeton.edu dmarc=pass fromdomain=princeton.edu);
       spf=pass (google.com: domain of [snip]@princeton.edu designates 40.107.223.52 as permitted sender) smtp.mailfrom=[snip]@princeton.edu
Return-Path: <[snip]@princeton.edu>
Received: from EIFMAILUE2P2.az.virginia.edu (mail.az.virginia.edu. [52.254.56.82])
        by mx.google.com with ESMTPS id r14-20020ac867ce000000b002e20c2a75e0si1820225qtp.622.2022.04.02.10.41.58
        for <jpa4q@goog.email.virginia.edu>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 02 Apr 2022 10:41:58 -0700 (PDT)
Received-SPF: pass (google.com: domain of [snip]@princeton.edu designates 40.107.223.52 as permitted sender) client-ip=40.107.223.52;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@princeton.edu header.s=selector2 header.b=pb0fhqw8;
       arc=pass (i=1 spf=pass spfdomain=princeton.edu dkim=pass dkdomain=princeton.edu dmarc=pass fromdomain=princeton.edu);
       spf=pass (google.com: domain of [snip]@princeton.edu designates 40.107.223.52 as permitted sender) smtp.mailfrom=[snip]@princeton.edu
Received: from NAM11-DM6-obe.outbound.protection.outlook.com (mail-dm6nam11on2052.outbound.protection.outlook.com [40.107.223.52])
	by EIFMAILUE2P2.az.virginia.edu  with ESMTP id 232HfvSL016411-232HfvSN016411
	(version=TLSv1.2 cipher=ECDHE-RSA-AES256-GCM-SHA384 bits=256 verify=OK)
	for <jpa4q@virginia.edu>; Sat, 2 Apr 2022 13:41:58 -0400
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=Z/LIm5YEI1P4yPZrn9XzRkqSni6xadjviHcc018YN+WzKBjpvcwkYNOuiFYg1zAaCIDH8sgmMxCh4fPLvxtmFZWQa+no+4h4NulkNvfDHppKThp51938SCfgndOKPw8+uNoRK6W8dSAyqCcnzjEtYFGVHpuLauqswDOlt47aJPbcWdLNYOSCDlqYzwvgYZ9HbgMu5U0Wm/AoPT3B93N/j4JGSOk10I/NEn8PftmX6fakw+QpKd7LwIUu2MxnoIjZEaYpCFbgd6/ndXWG6/bRIGmHW5BwWZn3yIigWUt7B7StYvH9qFOQO7nJUdHLRTnmVoFkADehmSf9ci3tIjfYfw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=moW9X4ldOzD+pUMT462Wrse3LN/+UeqTXV5TLF2fEZY=;
 b=H2PbhHiNQYliOkDKm3z3TMvBb3DrHiG96nO/PVgcIU+xhav9L4V0dqxtSYrt1pSOQGQCQOU7NiCyZG0Mr3KCdlx0REESQ1l4a91mCeuG4qbjlZnx2DDiNffqCmvgeBcxZIrwYcOJjEaqooUlwgPn8t2owXZ1rDPO0iOjoyDEwFWX8ewAFt7dnKNOkZa0IL+lo3V5zsHZTgGOHaQqGU8GUbc9rDLhPtU3jJyxDRjQ2V+2yuP2gl6BIaDZfOJDotCueJNcEVM293BbUCRweemfPRyfhc2/XAK/34tGcZ+EyaMj5ZCXeHHBkZhp7pfZHaI2ev/amkzR1gbd0oD/Jox8oA==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=pass
 smtp.mailfrom=princeton.edu; dmarc=pass action=none
 header.from=princeton.edu; dkim=pass header.d=princeton.edu; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=princeton.edu;
 s=selector2;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=moW9X4ldOzD+pUMT462Wrse3LN/+UeqTXV5TLF2fEZY=;
 b=pb0fhqw8pxKATat0qoThmfk3LdnQBXznOdKfgRk1p96AUeClYa16wLQKhQVgKr3Zs00uHN+OIhiTM+wxy7O+Om8DuYNgUdoZjE7HaWO8SarcCG0EuiYLv6JYRKmPtABw8i+CyZIGhqAxJgaXn9+/Py+dMviUVLkiNJN7nYpjYuhntV7oxl6ReDCYwG+/l4FCnZlU42Gfth7hHokPONMEhtUhOeZlcD77Rtu13kAmxnYhWR/mvZUFgGXIQB6l3ZbpIiI+xDrpII5ty4GAQ2AQQQTCjO8vrs5nwv8OwAAN3IktgLzIx+utVnU3ywVPFGhEIcHZysc60qOIbAeMe2qGOA==
Received: from MN2PR04MB6974.namprd04.prod.outlook.com (2603:10b6:208:1ee::19)
 by CO6PR04MB7795.namprd04.prod.outlook.com (2603:10b6:5:35b::7) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5123.30; Sat, 2 Apr
 2022 17:41:56 +0000
Received: from MN2PR04MB6974.namprd04.prod.outlook.com
 ([fe80::f15b:cb2c:3c5f:e991]) by MN2PR04MB6974.namprd04.prod.outlook.com
 ([fe80::f15b:cb2c:3c5f:e991%7]) with mapi id 15.20.5123.030; Sat, 2 Apr 2022
 17:41:56 +0000
From: Snip <Snip@princeton.edu>
To: J. P. Ascher <jpa4q@virginia.edu>
Subject: Re: exlibris-l Digest Thu, 31 Mar 2022 (1/1)
Thread-Topic: exlibris-l Digest Thu, 31 Mar 2022 (1/1)
Thread-Index: AQHYROS4FCaU0OZIcEWnKtNNA6rV1qzZzKn7gAAE44CAAiTJPoAAw4KAgAAsKn8=
Date: Sat, 2 Apr 2022 17:41:56 +0000
Message-ID:
 <MN2PR04MB6974D8CE564E6C4094C455F6CAE39@MN2PR04MB6974.namprd04.prod.outlook.com>
References:
 <DM6PR04MB6969C263C42FE2D547638976CAE19@DM6PR04MB6969.namprd04.prod.outlook.com>
 <743A75FE-A6FC-42EE-BDDA-DFFBFAA99752@virginia.edu>
 <MN2PR04MB6974B95E3BFD91504515E2ADCAE39@MN2PR04MB6974.namprd04.prod.outlook.com>
 <m0tubbr0ms.fsf@virginia.edu>
In-Reply-To: <m0tubbr0ms.fsf@virginia.edu>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
suggested_attachment_session_id: 91e0f264-2aff-cdca-898c-a66d60e5bea2
Authentication-Results: eifmailue2p2.az.virginia.edu;
	spf=pass (virginia.edu: domain of [snip]@princeton.edu designates 40.107.223.52 as permitted sender) smtp.mailfrom=[snip]@princeton.edu
authentication-results: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=princeton.edu;
x-ms-publictraffictype: Email
x-ms-office365-filtering-correlation-id: 1d2bd249-da1d-4b38-7b0f-08da14d014d2
x-ms-traffictypediagnostic: CO6PR04MB7795:EE_
x-microsoft-antispam-prvs:
 <CO6PR04MB779589F29D27C829D3BD6757CAE39@CO6PR04MB7795.namprd04.prod.outlook.com>
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
x-microsoft-antispam: BCL:0;
x-microsoft-antispam-message-info:
 ZW4qy+R+jlt/JYgrm5v8doE+9xT1bixCVVnLYxyX9lnHlutem2AHjyKy0sDovFgifDlmIDmxxNt8NChpTv1dsHYvlVeMJ8eNqQF3C5pu3eA1PUNJxIGyarjGUSdhLfVa7IU3X4YrVmTerO0DB5GCwdjSaaZyE6Stndb5O4o3wRvAefvKAi/8LHSdbNPR887yPy8AwomkTW4eyzwco+Odku8oXgGf7nmtNn0aQeAdVq3fF3SA+uAk0velayXGOpqq2qB2/RN8EPBntuyD7KFcLgpz24nWbRyVZIB7TaGFa4DpwLQq/ZN9P9dCnhelwZFNn0lLv+gPLPfUcItwB3zQtCh2Kl/KHwF5FeYWubKiWeYsfLxjphzbsxyCEvwRiu36955BxpPEbjncqFw7H+GJzT4HDG/FKiotPJNJf7BYqc6zzkVEykpRD1d3op1ewLOqRvjf7WnbPquW+nbiH2vL62IUskRL9iq2hj7Lh3+iqkmtbUQQ71vYs4LhlMo+yrmI4W9poul3oC16/ma9h7ZX2Gj/ndwKrSTTR0zRnyIObqIc0NwN9mNwcCp5EVNEadJrhJgIqwatSnUzWiWitGkD0tLiB6d1HPu3xjkfPwVFnNfGBOEJaopFAHbMSHJ4rNHquNMTQ02yeKxrvq8Ng+oZyP4slbWKS5hOfePrrnds7yBifDN+1Fg5xTQ3+8fqt4U/lchQcUgHJ+bcTuYjkd0cbGJ0xHF3WWnKHdYU1zK9rDcZKO96+knvhyergGxz3Dw4Rx9UMPPtFH6Jrel8kZyHctaUWffAxYHUeCFev/16KyWJpvq59FuuNN42AuYqG3vj
x-forefront-antispam-report:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:MN2PR04MB6974.namprd04.prod.outlook.com;PTR:;CAT:NONE;SFS:(13230001)(4636009)(366004)(53546011)(75432002)(19627405001)(7696005)(6506007)(40140700001)(5660300002)(2906002)(9686003)(76116006)(64756008)(66946007)(66556008)(66446008)(66476007)(38070700005)(8676002)(55016003)(38100700002)(33656002)(122000001)(166002)(186003)(26005)(30864003)(66574015)(83380400001)(71200400001)(45080400002)(786003)(316002)(6916009)(508600001)(84970400001)(52536014)(86362001)(966005)(8936002)(509004004);DIR:OUT;SFP:1101;
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 zthRK4OkVP7L1rLzzahUFqFcjPeuIolXdfOpXmw785QWtCxdetBFE6e4Cn+i+5QO6z1E+L44q93iv/EBOHpqbTeHz5PBYu4KVlVWhNiymGU5bJY3Rof2UERfL4lTdWnbIuQj8UOwY2TD3+I+LB0Um0L/qeiaqZ08v04qnLZRtwNSmLCjOwsjslFcv5NvcIbLU/mFRZbkRDmghgEoNWQMO6xeRU2ntX94c9DhTuj3LNdYlwPd4yunM5GtNdTaEUXRBuAJkKA810Izn1Y9OhbG9XPt/N2ZHHL3uNEGmbjOzcYZUr+GSwATfX/wYHvwLP2gOksaWVTvsjXi5IHNJpt2//M0P6FmQqx9A8aouvZTJ2q+VLvBDMX1u/9Y1r75MxpvVmAY60jurNf43xkorkexsioWHlZNGImS6/taf1Kx/0Exkc07zTP1XdpeVeB9maVFXQneTjCTss9zdncAyb9tjM7Bq9tGEkcnpeWZjf9Al0n5xCNkmUgILjn/wlwDweD3hbvuvKhU6uTZ5fQDYFuNZpNZyw1FZvO3ppeEoRdYw9iCD0Thrj8syFYLYKksVsvmXklfOkGrmDAv9SnLkKyuU0vW7fmpYB5SxFJwwonBDcEaqc6a3De5zM1LW8PAcEW3ohDqAC/aeAfup/MelFCjhJED051ejQ0GuHQCcePc4o9Oed+X+8dTdOySJ+cH5VeE5QUT3YWjEhsNOR4j3OZblFIVlkwiu5jYRjgyw8pl6gRUJy3JkSiZfmoRFqKjYgY9Jlc2fbhLBRmcL+hq+r4DbRXFQR3hqI4wiEfEk6403+79P3tzfnkhyLbapC6KY7EhvJz6i8bpaS5LlqnFVJoSMm0tr4WiLb4kwwa2gitp/qvgmrT3mrMXMOvwJswzP80OtIBlid0taQ73EgC3kjSFduNzlLaHZsarIARtKrv6fhAaM6H0dMT76puwxtcmZeiRzFla8n9T2j3GYVNh2VJW1kQUDWXNP4LAex5mGfM+4IKNaAavdqKfZKqp1DjhYiemBNWK/vWGEDff6W0qXT91yCl5JkwGpWr64DM+0RO8hq46yNcd/RqK7WK1bAKIQVQRtAnN/SQ7V9rEBEcYV1VMScJqrF+E/GbTG4LwpNUuFEq7niCWYMW5NxxVPbdQB/Pi2WGeGPTumOWeVXQPxRPUUqMKWaFMYhmV2I4VERxZZXDdgPBEsmVapBnmqdkCHI0d1V61qKp4DpW8VPaaBmTiud3Oifb6sSh8XxqjHp9Am/XO/73FOWP8GLf/28ku3T/wG9+RoTOGqXrsRTx0T42PE7+Jmq4wvgxEBuDnOrvnRSuUj8etahKkiJOS2DcpV5WAz2NjNW2QwCRGmvCDQzrJh1GGKCH0u5AYkJ+kzCqvdCydO9dnzG308eQZT6cM/ZWKRVftKhIcq1kYt/1xylBlqCoqSOjI/SdFGanZj8A7MsCbIxbEJd/WSylNrBzweyyLqYGNXFn7SbhziAjsrzTt4AhffAhUedepwTcSdXq3/2XX01Vf4gPiEUSVe3n+2Dkyat3062aqKdVFrmgfPYUqRdJmKYNNl+ImjZ75ddh7WRceFuJ9l09ONAoioT7AKGdZuHR017dKlJ0tDF6+Z6gq6oEsWsFpiNDNI60eIRp+fL/XRiCF52nhh7egQC34bLF+A+GdW8QToMVI7i8qxVFlwgoWCWCNz+QOBxybjANrwCoQH5TC5vKv+IT9CPnGTERVwhLd9/aEhGq/EA8ErbYaxA==
Content-Type: multipart/alternative;
	boundary="_000_MN2PR04MB6974D8CE564E6C4094C455F6CAE39MN2PR04MB6974namp_"
MIME-Version: 1.0
X-OriginatorOrg: princeton.edu
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: MN2PR04MB6974.namprd04.prod.outlook.com
X-MS-Exchange-CrossTenant-Network-Message-Id: 1d2bd249-da1d-4b38-7b0f-08da14d014d2
X-MS-Exchange-CrossTenant-originalarrivaltime: 02 Apr 2022 17:41:56.0343
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 2ff60116-7431-425d-b5af-077d7791bda4
X-MS-Exchange-CrossTenant-mailboxtype: HOSTED
X-MS-Exchange-CrossTenant-userprincipalname: UcPby7r0g1iIZOYnSt5gS2kS74/F+i7bQxRhHwnd9hq2PkCLDheHrxpuNBT5X1QVRshJMArNMRfTHjyKML5wCQ==
X-MS-Exchange-Transport-CrossTenantHeadersStamped: CO6PR04MB7795
X-FE-Last-Public-Client-IP: 40.107.223.52
X-FE-Envelope-From: [snip]@princeton.edu
X-FE-Policy-ID: 0:28:1:virginia.edu
X-TUID: 8aMmCf1OTeU/

TA! Yes, it does so feel good to be nearing the finish line,
[snip: a huge amount of back-and-forth with my friend]
```

## Body cont. with the forward with the offending line
```
> ------------------------------
> Message-ID:
>  <BN6PR13MB31887AA64A0B7A569DD25513E51F9@BN6PR13MB3188.namprd13.prod.outlook.com>
> Date: Wed, 30 Mar 2022 16:45:36 +0000
> From: "Belanger, Terry (tb3e)" <tb3e@virginia.edu>
> Subject: ["EXLIBRIS-L"] FW: Upstairs, downstairs: a book to purchase
>
> This summer, David R. Whitesell retires as curator of rare books at the Albert
> and Shirley Small Special Collections Library of the University of Virginia.
> In honor of the occasion, the library has published meditations by Whitesell
> on his ten years of acquisitions work, titled A curator's Wunderkammer: a
> decade of collecting for the University of Virginia. The catalog  accompanies
> an exhibition (on view through July 2022) of 64 of Whitesell's most notable
> acquisitions for UVa.
>       This is not your usual exhibition catalog. Item by item, Whitesell
> explains why, how, and from whom he made each purchase, naming the dealers
> involved, and citing the UVa endowed and other funds that made the purchase
> possible. The dashingly-designed color catalog illustrates all of the items
> discussed. The result is as a textbook of canny special collections high-end
> acquisitions.
>       The named dealers include Antiquariat Banzhaf, James Arsenault, Asia
> Bookroom, Bartleby's Books, Simon Beattie, Bookvica, Ian Brabner, the Brick
> Row Book Shop, Paul Brzozowski and Michael Brown Rare Books, Leo Cadogan, John
> Carbonell, Rodolphe Chamonal, James Cummins, DeWolfe and Wood, Roger Gaskell,
> Samuel Gedge, Christopher Edwards, Mark Godburn, Peter Harrington, Hünersdorff
> Rare Books, Michael Laird, Peter Luke, Bruce McKittrick Rare Books, Nicholas
> Marlowe Rare Books, Howard S. Mott, Musinsky Rare Books, Cal Packard, Bernard
> Quaritch, Richard C. Ramer, the William Reese Company, L. and T. Respess,
> Savoy Books, Swann Auction Galleries, the Veatchs, John Waite, and Charles B.
> Wood III. These are the headliners: Whitesell estimates that in all he
> purchased about 15,000 books for UVa, from several hundred dealers, during a
> decade in which about a hundred thousand gifts came into Special Collections
> (many of them through his efforts).
>       Stepping back: until well after World War II,  the title pages of major
> American art and book exhibition catalogs routinely omitted the names of their
> authors. An exhibition catalog's preface, usually signed by the chief
> executive officer of the organizing museum or library, would almost always
> mention and thank the curators responsible for the text that followed; but the
> focus was institutional. One sometimes learned the names of a catalog's author
> or authors only by word of mouth, or when alert library catalogers eventually
> ferreted out their names and gave them credit.
>       In the 1970s, it became increasingly common practice for exhibition
> catalog authors to receive title-page acknowledgement; and these days, such
> credits are routinely provided. UVa's publication of the Whitesell catalog is
> a significant further step in the institutional acknowledgement of curatorial
> expertise. A curator's Wunderkammer was designed by Holly Robertson and Jeff
> Hill, with digital production and photography by Stacey Evans, Rob Smith, and
> Bobbi Morris. The final pages of the catalog are devoted to a modest pitch,
> inviting contribution to the UVa Library's endowed acquisitions funds; I
> gather that a considerable part of the modest pressrun of A curator's
> Wunderkammer has been allocated to institutional purposes.
>       Some copies of the 106-page Curator's Wunderkammer, however, are
> available for  public sale via the UVa Bookstore for $25 plus s/h: see
> https://uvabookstores.com/shop_product_detail.asp?catalog_group_id=MTU1&catalog_group_name=R2VuZXJhbCBCb29rcw&catalog_id=1903&catalog_name=Qm9va3MgJiBDYWxlbmRhcnMgQWJvdXQgVXZh&pf_id=48311&product_name=V2hpdGVzZWxsLCBEYXZpZCAvIEN1cmF0b3IncyBXdW5kZXJrYW1tZXI6ICBEZWNhZGUgT2YgQ29sbGVjdGluZyBGb3IgVGhlIFVWQQ&type=3&target=shop_product_list.asp<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuvabookstores.com%2Fshop_product_detail.asp%3Fcatalog_group_id%3DMTU1%26catalog_group_name%3DR2VuZXJhbCBCb29rcw%26catalog_id%3D1903%26catalog_name%3DQm9va3MgJiBDYWxlbmRhcnMgQWJvdXQgVXZh%26pf_id%3D48311%26product_name%3DV2hpdGVzZWxsLCBEYXZpZCAvIEN1cmF0b3IncyBXdW5kZXJrYW1tZXI6ICBEZWNhZGUgT2YgQ29sbGVjdGluZyBGb3IgVGhlIFVWQQ%26type%3D3%26target%3Dshop_product_list.asp&data=04%7C01%7Curomero%40iu.edu%7C4cbeb56f911b4a919ecb08da11e0a6ee%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637841953814777492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DqRrwZYrIeXeN2t5ZL65gTsIsBqQ2wgpHtykCAPYxv0%3D&reserved=0>
>             If you wish to have a copy, personally or institutionally, you
> should probably act quickly.
>
> Terry Belanger . 101 Amherst Commons . Charlottesville, VA 22903
> Land: 434-296-9917  Mobile: 434-825-8968  Email:
> terry.belanger@virginia.edu<mailto:terry.belanger@virginia.edu>
>
>
> ------------------------------
[snip]
```

The offending line, which is what the above message simulates without the cruft of the discussion is:

```
> https://uvabookstores.com/shop_product_detail.asp?catalog_group_id=MTU1&catalog_group_name=R2VuZXJhbCBCb29rcw&catalog_id=1903&catalog_name=Qm9va3MgJiBDYWxlbmRhcnMgQWJvdXQgVXZh&pf_id=48311&product_name=V2hpdGVzZWxsLCBEYXZpZCAvIEN1cmF0b3IncyBXdW5kZXJrYW1tZXI6ICBEZWNhZGUgT2YgQ29sbGVjdGluZyBGb3IgVGhlIFVWQQ&type=3&target=shop_product_list.asp<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuvabookstores.com%2Fshop_product_detail.asp%3Fcatalog_group_id%3DMTU1%26catalog_group_name%3DR2VuZXJhbCBCb29rcw%26catalog_id%3D1903%26catalog_name%3DQm9va3MgJiBDYWxlbmRhcnMgQWJvdXQgVXZh%26pf_id%3D48311%26product_name%3DV2hpdGVzZWxsLCBEYXZpZCAvIEN1cmF0b3IncyBXdW5kZXJrYW1tZXI6ICBEZWNhZGUgT2YgQ29sbGVjdGluZyBGb3IgVGhlIFVWQQ%26type%3D3%26target%3Dshop_product_list.asp&data=04%7C01%7Curomero%40iu.edu%7C4cbeb56f911b4a919ecb08da11e0a6ee%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637841953814777492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DqRrwZYrIeXeN2t5ZL65gTsIsBqQ2wgpHtykCAPYxv0%3D&reserved=0>
```

## Discussion
You can see here that the offending line started out as a long eCommerce link, but through the process of being forwarded through an Outlook Server, acquired more length, and was--itself--eventually quoted with a preceding `>` followed by a space. This triggers the error.

**Comment by djcb** [comment] 2022-05-29 12:38
Thanks, I tried the test message, and it works for me without a hitch. But `fill-nobreak-predicate` is `nil` in my case (the default value); I can reproduce the problem when I set it.

Seems like something beyond mu4e's control; or perhaps we could let-bind `fill-nobreak-predicate` before rendering the message.

**Comment by djcb** [comment] 2023-10-31 19:57
Checking this again... it seems this is a little beyond mu4e's control. We could let-bind `fill-nobreak-predicate` to nil when rendering the message, but that seems a bit... wrong. 

I can still see the error though, I still get `error in process filter: fill-nobreak-p: Beginning of buffer`. So I'd recommend filling a issue against `fill.el`  (?). I really have no idea what's going on there... but it seems `mu4e` is innocent here.

So am closing this, sorry....

**Closed by djcb** 2023-10-31 19:57 UTC
Labels: bug, needinfo, mu4e

**Comment by cacology** [comment] 2023-11-01 09:21
Thanks for following up- I think you're right about `fill-nobreak-predicate` being the solution and this not quite being mu4e's problem. I think the documentation here in this closed issue is sufficient. If someone trips up on this, they can find this then. (Sorry I lost track of this too. Thanks for your responses!)

I think the root problem is inconsistent client-to-client quoting behavior combined with well-intentioned, but disruptive, server-to-server alterations that puts text into really unusual states. (I'm looking at you, SafeLinks, HTML, and plain text.)

Perhaps this is a (very) low-priority enhancement request: **provide an alternative message viewing framework for really messed-up messages**. My local solution until I figured out the above was just to use a different email client to deal with that particular email.
