### ISSUE TITLE
[mu4e bug] Clicking links opens them twice

### ISSUE THREAD

**Issue by phil-s** [djcb/mu#2645] opened 2024-03-01 01:09 UTC
**Describe the bug**

In `mu4e-view-active-urls-keymap` both `[mouse-1]` *and* `[down-mouse-1]` are bound to `mu4e--view-browse-url-from-binding` which means it gets triggered twice:

* `down-mouse-1` is the event which fires the moment you depress the button
* `mouse-1` is the event which fires if you then release the button without moving the mouse in the interim
* `drag-mouse-1` is the event which fires if you had moved the mouse before releasing the button

Either way Emacs sees two mouse events, and so you don't want `down-mouse-1` bound to the same command as either of the others.

I recommend removing the `down-mouse-1` binding.

**How to Reproduce**

Click a link.  I then get two duplicate tabs in Firefox for that URL.

**Environment**

* Emacs 29.2 (but I believe the mouse events have always worked this way).
* Ubuntu 22.04 and its maildir-utils package version 1.6.10-1

I can see the same issue in the current `master` branch:
https://github.com/djcb/mu/blob/68822006c89605c2872c3130f2bd01517cd4d362/mu4e/mu4e-view.el#L432-L438

**Checklist**
- [ ] *(but see master branch code link)* you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [X] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

**Comment by phil-s** [comment] 2024-03-01 01:16
Workaround for end users:

```el
(with-eval-after-load "mu4e-view"
  (define-key mu4e-view-active-urls-keymap [down-mouse-1] nil))
```

**Comment by djcb** [comment] 2024-03-01 08:32
I can't reproduce that problem. When I click, only a single tab is opened. Can you show your `view-lossage` output when you see this? Thanks.

**Comment by phil-s** [comment] 2024-03-01 08:54
```plain
 C-g                        ;; keyboard-quit
 <help-echo> <down-mouse-1> ;; mu4e~view-browse-url-from-binding
 <mouse-1>                  ;; mu4e~view-browse-url-from-binding
 C-h l                      ;; view-lossage
```

**Comment by djcb** [comment] 2024-03-01 21:37
Pushed a fix. I've changed it a bit, and now the click is bound only to `<mouse-2>`, to be consistent between "html mode" and "text mode".

**Closed by djcb** 2024-03-01 21:37 UTC
Labels: bug, needinfo, mu4e
