### ISSUE TITLE
[mu4e bug] Current header marked incorrectly, when switch-to-buffer-obey-display-actions is set

### ISSUE THREAD

**Issue by martin5233** [djcb/mu#2338] opened 2022-09-22 11:10 UTC
**Describe the bug**

When the init files contains the setting
(setq switch-to-buffer-obey-display-actions t)
the current message header is not correctly highlighted, after pressing 'n' or 'p' in the message view.

**How to Reproduce**

1. Eval  (setq switch-to-buffer-obey-display-actions t)
2. Open mu4e
3. Select any message
4. In message view type 'n' or 'p' to display the next or previous message

The current header is then set twice. Once to the correct message and then to the first message instead.

**Environment**
Emacs 28.1 on Linux, mu4e 1.8.9

**Checklist**
- [x ] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [x ] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [x ] you have read all of the above

**Comment by djcb** [comment] 2022-10-07 08:14
Never used that option, but suspect that simply might be incompatible with what mu4e does. So perhaps for now I'd say "don't do that".

**Comment by martin5233** [comment] 2022-10-07 10:05
So, this means I can either use mu4e or use display-buffer-alist to organize my buffer display, which is rather disappointing. From my point of view additional packages should strive to work with all standard Emacs features. Mickey Petersen has recommended this approach to handle display-buffer-alist in his [article](https://www.masteringemacs.org/article/demystifying-emacs-window-manager).

**Comment by djcb** [comment] 2022-10-14 23:08
No need to be disappointed, you can help if you can give an analysis about what this option is expecting and what mu4e is doing; it seems it depends on some unwritten rule, but I have no idea.

**Comment by rdiaz02** [comment] 2022-11-26 14:26
For the record, this is the setting that also causes the issue asked about here: "mu4e-headers sometimes selects the wrong email" : https://groups.google.com/g/mu-discuss/c/z94akIoAyg8 . 


For completeness I am copying the steps I follow:

 Suppose we have three accounts, call them A, B, C (and we have `(setq switch-to-buffer-obey-display-actions t) `) . The following shows the problem:

1. Start mu4e

2. j  (mu4e~headers-jump-to-maildir)  to maildir A

3. C (mu4e-compose-new) with account B; in my case, it asks for the context and I choose context B. You can abort it (e.g., kill the *draft* buffer) or send it

4. j to maildir B or C

5. Open any email. Close it (q). The cursor is generally on the top one on the mu4e-headers list, not in the one you just opened.


As for why I set `switch-to-buffer-obey-display-actions` to `t`:  I do it by default in my init.el to force even misbehaving commands (not from mu4e, but from other packages) to obey the rules I set in display-buffer-a-list. (This is my understanding from, for example, https://www.masteringemacs.org/article/demystifying-emacs-window-manager).

**Comment by djcb** [comment] 2022-12-30 13:49
Is this still a problem with the new window-management code (which was contributed by @mickeynp mentioned here)?

**Comment by rdiaz02** [comment] 2022-12-31 13:22
Thanks for the fixes. But, yes, at least for me the problem remains.

**Comment by djcb** [comment] 2023-01-20 13:36
Can't reproduce the problem with `master`. Can you, @martin5233 or @rdiaz02 ?

**Comment by rdiaz02** [comment] 2023-01-21 23:04
I can't reproduce either. Thanks a lot!

**Comment by djcb** [comment] 2023-01-22 06:58
Great, thanks. Closing this (I think this was fixed as the side-effect of something else)

**Closed by djcb** 2023-01-22 06:58 UTC
Labels: needinfo, mu4e
