### ISSUE TITLE
Cannot open eml attachment

### ISSUE THREAD

**Issue by brabalan** [djcb/mu#313] opened 2013-11-14 13:03 UTC
Hello,

When I try to open an eml attachment (o 1 on the message below), nothing happens. If I try to open the attachment again, I get the error:
```
error in process filter: mu4e-error-handler: Error 3: unknown error
error in process filter: Error 3: unknown error
```

Here is the problematic message:

```
Return-Path: SRS0=Zm7i=UW=returns.groups.yahoo.com=notify-return-alan.schmitt=polytechnique.org@bounces.m4x.org
Received: from zfront2.inria.fr (LHLO zfront2.inria.fr) (193.51.193.148) by
 zmbs2.inria.fr with LMTP; Wed, 13 Nov 2013 08:32:32 +0100 (CET)
Received: from mail3-relais-sop.national.inria.fr (mail3-relais-sop.national.inria.fr [192.134.164.104])
	by zfront2.inria.fr (Postfix) with ESMTPS id 9585724805F
	for <aschmitt@zimbra.inria.fr>; Wed, 13 Nov 2013 08:32:32 +0100 (CET)
Received-SPF: None (mail3-smtp-sop.national.inria.fr: no sender
  authenticity information available from domain of
  unison-users-owner@yahoogroups.com) identity=pra;
  client-ip=129.104.30.35;
  receiver=mail3-smtp-sop.national.inria.fr;
  envelope-from="SRS0=Zm7i=UW=returns.groups.yahoo.com=notify-return-alan.schmitt=polytechnique.org@bounces.m4x.org";
  x-sender="unison-users-owner@yahoogroups.com";
  x-conformance=sidf_compatible
Received-SPF: Pass (mail3-smtp-sop.national.inria.fr: domain of
  SRS0=Zm7i=UW=returns.groups.yahoo.com=notify-return-alan.schmitt=polytechnique.org@bounces.m4x.org
  designates 129.104.30.35 as permitted sender)
  identity=mailfrom; client-ip=129.104.30.35;
  receiver=mail3-smtp-sop.national.inria.fr;
  envelope-from="SRS0=Zm7i=UW=returns.groups.yahoo.com=notify-return-alan.schmitt=polytechnique.org@bounces.m4x.org";
  x-sender="SRS0=Zm7i=UW=returns.groups.yahoo.com=notify-return-alan.schmitt=polytechnique.org@bounces.m4x.org";
  x-conformance=sidf_compatible; x-record-type="spf2.0"
Received-SPF: Pass (mail3-smtp-sop.national.inria.fr: domain of
  postmaster@mx2.polytechnique.org designates 129.104.30.35 as
  permitted sender) identity=helo; client-ip=129.104.30.35;
  receiver=mail3-smtp-sop.national.inria.fr;
  envelope-from="SRS0=Zm7i=UW=returns.groups.yahoo.com=notify-return-alan.schmitt=polytechnique.org@bounces.m4x.org";
  x-sender="postmaster@mx2.polytechnique.org";
  x-conformance=sidf_compatible; x-record-type="v=spf1"
X-IronPort-Anti-Spam-Filtered: true
X-IronPort-Anti-Spam-Result: Av0CAH8qg1KBaB4jnGdsb2JhbABPCoM/rR2TexYOAQEBAQEICwkJFCiCHAtFAQEBATYBDwMKAWMkKxKHXQMPDatThFIBBQKEdAMKiWIBBg2MYIEpBoFghBuHZo5CgxqFDjWFYYF2gmCECoFx
X-IPAS-Result: Av0CAH8qg1KBaB4jnGdsb2JhbABPCoM/rR2TexYOAQEBAQEICwkJFCiCHAtFAQEBATYBDwMKAWMkKxKHXQMPDatThFIBBQKEdAMKiWIBBg2MYIEpBoFghBuHZo5CgxqFDjWFYYF2gmCECoFx
X-IronPort-AV: E=Sophos;i="4.93,690,1378850400"; 
   d="scan'208";a="35284334"
Received: from mx2.polytechnique.org ([129.104.30.35])
  by mail3-smtp-sop.national.inria.fr with ESMTP/TLS/ADH-AES256-SHA; 13 Nov 2013 08:32:32 +0100
Received: by yuuai.polytechnique.org (Postfix)
	id 40626802C93; Wed, 13 Nov 2013 08:32:31 +0100 (CET)
Delivered-To: alan.schmitt.1995@hruid.polytechnique.org
Received: from ng17-ip4.bullet.mail.ne1.yahoo.com (ng17-ip4.bullet.mail.ne1.yahoo.com [98.138.215.96])
	by mx2.polytechnique.org (Postfix) with SMTP id 69658802C90
	for <alan.schmitt@polytechnique.org>; Wed, 13 Nov 2013 08:32:30 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yahoogroups.com; s=echoe; t=1384327949; bh=IVNre5GkMMrvhdpwDPc5FqNEqFNbc912uZtVhaN2n58=; h=Received:Received:X-Yahoo-Newman-Property:X-eGroups-Msg-Info:X-Sender:X-Apparently-To:Received:Date:Message-ID:MIME-Version:From:Reply-To:To:Subject:Content-Type:Sender:X-eGroups-Moderators; b=U/2LYt+kWsZe5Iz+I7Zluf6WIMtemUhN5sxnxwEkZJxdKaiCIfD9W5qenHNigjIt6umr84wqHklwmFCQjnyKPbJMHhcvlRdZwpbPRuqDGUr6L3VtaHHXdNfJ3o6aCMdAByrm8ERDCVm3QVxnIegFyv7lSdpuQmCWlo2us7oHdDo=
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws; s=echoe; d=yahoogroups.com;
	b=UUhSNLFOYMMY0aAEjSGFGsYLE3JpKyZX+JaYMMoKIm8T6bOUYz3ttNMZU+EsA4MnhidORlej8RNP/Du+qLYSxpyxFi/rJ6hduyp7gxT4S5IlJbmv1HbFiDFOFfTzKtpgfjQbj++ypuxFs6ABX+6z4VrLbOc43jQX1L8RlUbzQ84=;
Received: from [98.138.101.138] by ng17.bullet.mail.ne1.yahoo.com with NNFMP; 13 Nov 2013 07:32:29 -0000
Received: from [10.193.39.44] by tg8.bullet.mail.ne1.yahoo.com with NNFMP; 13 Nov 2013 07:32:29 -0000
X-Yahoo-Newman-Property: groups-notify
X-eGroups-Msg-Info: 1:6:0:0
X-Sender: notify@yahoogroups.com
X-Apparently-To: unison-users-owner@yahoogroups.com
Received: (qmail 66753 invoked by uid 7800); 13 Nov 2013 07:32:29 -0000
Date: 13 Nov 2013 07:32:29 -0000
Message-ID: <1384327949.137.66752.m11@yahoogroups.com>
MIME-Version: 1.0
From: Yahoo Groups Notification <unison-users-accept-qklwbcodgkpjict0bwd54mmwou1q@yahoogroups.com>
Reply-To: unison-users-accept-qklwbcodgkpjict0bwd54mmwou1q@yahoogroups.com
To: unison-users-owner@yahoogroups.com
Subject: MODERATE -- arorap@gmail.com posted to unison-users
Content-Type: multipart/mixed;
  boundary="-----004408537300607237790078125963"
Sender: unison-users-owner@yahoogroups.com
X-eGroups-Moderators: unison-users
X-AV-Checked: ClamAV using ClamSMTP at yuuai.polytechnique.org (Wed Nov 13 08:32:31 2013 +0100 (CET))
X-Spam-Flag: No, tests=bogofilter, spamicity=0.260690, queueID=1B286802C93

-------004408537300607237790078125963
Content-Type: text/plain
Content-Transfer-Encoding: 7bit


Hello,

A message has been sent to the unison-users group from

  arorap@gmail.com 

The message summary:
--------------------
FROM: arorap@gmail.com 
DATE: Wed, 13 Nov 2013 13:02:28 +0530 
SUBJECT: deleting a particular archive file 

How can I identify the arXXX and fpXXX files for a 
particular host+root pair so I can delete them from both 
hosts? 

I want to do this because two roots that I synced are no 
longer supposed to be synced since their contents are 
completely changing. In future I may want to sync them again
but would want to start fresh then and have no previous 
archives. 

--------------------

A complete copy of this message has been attached for your convenience.

This message requires your approval for one of the following reasons:
* Your group is set to moderate all messages from this user, OR
* Your group is set to moderate messages from all users

To approve or reject this message using the web, please visit:
http://groups.yahoo.com/group/unison-users/pending?view=1&msg=9828 

To approve this message using email, reply to this message. You do not 
need to attach the original message, just reply and send.

To reject this message using email, forward this message to

unison-users-reject-stxbyieaoh1kzx45sygv3hw3vxnq@yahoogroups.com 

NOTE: The pending message will expire after 14 days. If you do not 
take action within that time, the pending message will be automatically
rejected.  Yahoo Groups does this to maintain a high quality of
service for our users.

Thank you for choosing Yahoo Groups.

Regards,

Yahoo Groups Customer Care

Your use of Yahoo Groups is subject to http://info.yahoo.com/legal/us/yahoo/utos/terms/
 

-------004408537300607237790078125963
Content-Type: message/rfc822

Return-Path: <arorap@gmail.com>
X-Sender: arorap@gmail.com
X-Apparently-To: unison-users@yahoogroups.com
X-Received: (qmail 66747 invoked by uid 102); 13 Nov 2013 07:32:28 -0000
X-Received: from unknown (HELO mtaq2.grp.bf1.yahoo.com) (10.193.84.33)
  by m11.grp.bf1.yahoo.com with SMTP; 13 Nov 2013 07:32:28 -0000
X-Received: (qmail 31106 invoked from network); 13 Nov 2013 07:32:28 -0000
X-Received: from unknown (HELO mail-we0-f175.google.com) (74.125.82.175)
  by mtaq2.grp.bf1.yahoo.com with SMTP; 13 Nov 2013 07:32:28 -0000
X-Received: by mail-we0-f175.google.com with SMTP id t60so20066wes.20
        for <unison-users@yahoogroups.com>; Tue, 12 Nov 2013 23:32:28 -0800 (PST)
MIME-Version: 1.0
X-Received: by 10.194.185.73 with SMTP id fa9mr30336078wjc.29.1384327948277;
 Tue, 12 Nov 2013 23:32:28 -0800 (PST)
X-Received: by 10.227.192.143 with HTTP; Tue, 12 Nov 2013 23:32:28 -0800 (PST)
Date: Wed, 13 Nov 2013 13:02:28 +0530
Message-ID: <CAMcoJ2VqiRTLdjKtk=EyEbMP0xjMiXSuA5Q9e4M8vP6NMozqyA@mail.gmail.com>
To: "unison-users@yahoogroups.com" <unison-users@yahoogroups.com>
Content-Type: multipart/alternative; boundary=047d7bd6b0489c225404eb09f7e2
X-Originating-IP: 10.193.84.33
X-eGroups-Msg-Info: 1:12:0:0:0
From: Puneet Arora <arorap@gmail.com>
Subject: deleting a particular archive file
X-Yahoo-Group-Post: member; u=270041356; y=gpdgicwlzJOzXoHdh54v_-Xf2jzrIcGCVy5tGSDMssx151DKiWU
X-Yahoo-Profile: arorapuneet
X-YGroups-SubInfo: t=0;f=16;g=mwiTaOYtgbEI7cdRdTWzVmL2dWb-bggQb5WPGwqFIVQHq6jqhnu0diH-RiGO8ANKfK4;

--047d7bd6b0489c225404eb09f7e2
Content-Type: text/plain; charset=ISO-8859-1

How can I identify the arXXX and fpXXX files for a particular host+root
pair so I can delete them from both hosts?

I want to do this because two roots that I synced are no longer supposed to
be synced since their contents are completely changing. In future I may
want to sync them again but would want to start fresh then and have no
previous archives.

is this possible without blindly deleting all archives from both hosts?

thanks,
Puneet

--047d7bd6b0489c225404eb09f7e2
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">How can I identify the arXXX and fpXXX files for a particu=
lar host+root pair so I can delete them from both hosts?<div><br></div><div=
 style>I want to do this because two roots that I synced are no longer supp=
osed to be synced since their contents are completely changing. In future I=
 may want to sync them again but would want to start fresh then and have no=
 previous archives.</div>
<div style><br></div><div style>is this possible without blindly deleting a=
ll archives from both hosts?</div><div style><br></div><div style>thanks,</=
div><div style>Puneet</div><div style><br></div></div>

--047d7bd6b0489c225404eb09f7e2--

-------004408537300607237790078125963--
```

**Comment by mardukbp** [comment] 2015-01-10 03:02
I have a similar situation. I can open the eml attachment, but not its attachments. I get the same errors from above

```
error in process filter: mu4e-error-handler: Error 3: unknown error
error in process filter: Error 3: unknown error
```

**Comment by buster** [comment] 2015-03-26 10:57
I have the same problem. Unfortunately, i cannot even save the attached file..

**Comment by pmiddend** [comment] 2015-10-22 09:23
I have the same problem opening an image inside an attached mail.

**Comment by djcb** [comment] 2015-10-26 19:44
Attachments inside attached messages are not currently supported...

**Comment by pmiddend** [comment] 2015-10-29 09:13
This is an extremely common use-case for me, however. Is there a separate issue to cover that and can you say when you have time to implement it (or if it's difficult)?

**Comment by taurgal** [comment] 2015-12-23 14:28
Is there some plan to implement this or is it considered low priority? I understand the problem is that attached messages are not indexed by mu and so have no docid and I have no easy fix to this. Maybe one would need to augment docids to chain them like docid1/docid2/docid3?

**Comment by djcb** [comment] 2016-02-20 11:43
Opening eml attachments works fine, so I'm closing this. The other issues mentioned here are separate from that -- and are tracked in #454.

**Closed by djcb** 2016-02-20 11:43 UTC
