### ISSUE TITLE
[mu4e bug]

### ISSUE THREAD

**Issue by algon-ns** [djcb/mu#2192] opened 2021-12-20 10:21 UTC
**Describe the bug**
at install on emacs, the build of mu4e fails

**To Reproduce**
(straight-use-package 'mu4e)

**Environment**
Apple iMac 24" with M1 (aarch64)
macOS Monterey version 12.1
GNU Emacs 29.0.50 (build 21A559)

**Checklist**
- [ ] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x ] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x ] you are running either the latest 1.6.x release, or a 1.7.x development release (? taking default from straight).

<img width="2232" alt="Skærmbillede 2021-12-19 kl  16 47 46" src="https://user-images.githubusercontent.com/58687687/146751866-59adcba3-d613-4a52-82a3-2e7763a273b5.png">

**Comment by djcb** [comment] 2021-12-20 11:16
For bug-reports we require that reporters use a vanilla setup, and build with the instructions in the manual. We cannot support things like 'straight' (and the errors are not useful for diagnosis). 

Can you reproduce the problem by following the installation steps in the manual? If not, please show the errors you got.

Otherwise, please take it up with the 'straight' folks; if the problem turns out to be in mu/mu4e, they should be able to make a more actionable report.

**Comment by algon-ns** [comment] 2021-12-20 12:34
Hello,
I can not get it to work in any form, are you sure, that mu/mu4e is supported on my machine using package mangement  "straight".
I can't even find the programs with this setup:

_;;;minimal init
(setq-default debug-on-error         nil)
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/"))
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))_


and neither (require 'mu)
       nor       (require 'mu4e)
       nor       (use-package mu)
       nor       (use-package mu4e)
works.

Straight find this recipe for finding mu4e:
(mu4e :type git :host github :repo "djcb/mu" :pre-build ,(cl-letf (((symbol-function #'el-get-package-directory) (lambda (package) (straight--repos-dir (format "%S" package)))) (el-get-install-info (straight--el-get-install-info)) (el-get-emacs (straight--el-get-emacs)) (el-get-dir (straight--repos-dir))) (pcase system-type (_ `(("./autogen.sh") ("make"))))) :files (:defaults "mu4e"))

which kinda getting there, but not all the way.

So until further I won't use mail in my emacs

kind regards
Niels

**Comment by djcb** [comment] 2021-12-20 13:43
@algon-ns: we're mis-communicating. As mentioned multiple times, we do not provide support for "straight" which is a third-party package beyond our control. Its error messages are not useful for us. If it does not work, you should talk to the "straight" people first.

If you want support here, use the instructions at:
   https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html#Installation
to compile for yourself and post any errors you get here.

**Comment by algon-ns** [comment] 2021-12-22 06:40
Dear Dirk-Jan,
No, we're not....
I did figure it out, and now it's running, and the error is actual yours (or/and Apple).
The MU I install by brew is NOT located in the usual place, but Apple has changed it to
"/opt/homebrew/Cellar/mu/1.6.10/share/emacs/site-lisp/mu/mu4e/" like all other stuff installed by brew.
You need to check if it's an Apple with the M1 chip, that is with the "aarch64" architecture.

I got the inspiration (and solution) from: https://emacs.stackexchange.com/questions/46156/how-to-install-mu-and-mu4e-with-gui-emacs

thanks for the fight, and a great program
kind regards
Niels

**Comment by theophilusx** [comment] 2021-12-22 08:40
I would be wary of pointing fingers and seeking to allocate blame.

Dirk-Jan was very clear that the only supported installation method is
outlined in the manual - either from a release tarball or from git. The
project has NOTHING to do with any other installation method, including
homebrew. Likewise, apple has nothing to do with homebrew either. The
homebrew recipes are done by 3rd parties who have nothing to do with
mu4e or the project.

The issues you ran into has nothing to do with your mac being an M1. It
was 100% user configuration failure.

If you had read the manual as suggested in the original response to your
issue, you would have found the following paragraph

   You may need to restart Emacs, so it can find mu4e in its
‘load-path’.  If, even after restarting, Emacs cannot find mu4e, you may
need to add it to your ‘load-path’ explicitly; check where mu4e is
installed, and add something like the following to your configuration
before trying again:
     ;; the exact path may differ --- check it
     (add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")

which clearly outlines the importance of telling Emacs where to find the
mu4e sources and the need to set the load-path if Emacs cannot find the
files.

BTW that path for the mu4e sources is standard for homebrew packages and
it is a normal requirement for users to ensure that application search
paths are set appropriately. Homebrew use to be in /usr/local, but that
was changed back in 10.10 or 10.11 when Apple changes the permission
management on the /usr/local tree. The old path can still be used, but
you have to modify the security model of macos. To avoid users needing
to do that, the homebrew team moved the default location to
/opt/homebrew.

**Comment by djcb** [comment] 2021-12-25 10:06
Okay, great you got it working! Closing this.

**Closed by djcb** 2021-12-25 10:06 UTC
Labels: bug, mu4e, new

**Comment by algon-ns** [comment] 2021-12-25 10:09
Thanks….
Working to make configurations to suiting my likings…..
mvh
Niels
 <applewebdata://2634EF74-14F5-49D6-9836-A2E970BF2689>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45%204052%202789>+45 4052 2789 ***@***.*** ***@***.***>
Ultra posse nemo obligatur.
