### ISSUE TITLE
Cannot change status of mail

### ISSUE THREAD

**Issue by dschrempf** [djcb/mu#1670] opened 2020-04-30 19:16 UTC
## Expected or desired behavior
Mark mail read; sync (`mbsync -a`); status change is propagated to server.

## Actual behavior
Status change is not propagated to server. Upon a second sync, the mail is again unread.

## Versions of mu, mu4e/emacs, operating system etc.

mu (mail indexer/searcher) version 1.4.3 (github commit 7a47784d789c9fcab1b484e1c4fdd1f2bd3751ad)

mbsync version 1.3.1

## Any other detail
There are no error messages. The only weird thing is that when syncing the 'email read' flag, mbsync reports a status change on the master, and a new mail (?) on the master. For example,
```
C: 1/1  B: 1/1  M: +1/1 *1/1 #0/0  S: +0/0 *0/0 #0/0
```
This must have been a recent change, because I didn't have this problem a few days ago. Could it also be a change from my email provider (Gmail)?

Thank you for your help!

**Comment by djcb** [comment] 2020-04-30 20:14
Can you replicate without mbsync? Ie. mark mail read, restart mu4e, and check if it's still unread?

**Comment by theophilusx** [comment] 2020-05-01 00:41
I saw a very similar issue to this after upgrading to 1.4.3, but so far
it has only happened with one message. For some reason, just one message
in my INBOX would be marked as unread after a period when I returned to
look at the inbox - this was despite the fact it was also marked as
having been replied to. It was a message from a mailing list, but other
messages from the same list were not affected. Unfortunately, I have
deleted the message and not see this issue since. 

I do suspect this is some issue between mu4e and mbsync, but not tracked
it down yet.

**Comment by manuel-arguelles** [comment] 2020-05-01 05:13
I'm experiencing the same, not sure if it is related to mbsync since using mutt with mbsync seems to work ok.

isync 1.3.1
mu 1.4.1

I marked a message as read, restarted mu4e and the message is still marked as read, but as soon as mbsync kicks in it goes back to unread.

Also flagging seems to work in a way: I can flag the message (from mu4e to gmail) but not unflag it (from mu4e to gmail, it just stays as flagged).

**Comment by dschrempf** [comment] 2020-05-01 05:32
It is weird that you are using mu 1.4.1, so maybe it is a server related change? Are you using gmail?

**Comment by djcb** [comment] 2020-05-01 06:18
The problem is that `mbsync` is changing things behind `mu`'s back; that's not new, and we try to mitigate that (such as with `mu4e-change-filenames-when-moving`).

I would at least recommend setting `mu4e-index-cleanup` to `t`, and `mu4e-index-lazy-check` to `nil`, so mu has a chance to catch up.

I don't use `mbsync`, would be great to see if someone could try to track what happens with a new message, read it, sync etc. in terms of the file (name and path) corresponding to that message.

**Comment by theophilusx** [comment] 2020-05-01 06:59
I will see what I can find out. The issue was frequent this morning,
then I did a fresh pull from the git repo, saw there were some changes,
re-built and the issue has now gone away (or has not occurred again at
least).

Note that I've been using mu4e and mbsync for a few years now and had
not seen this issue before. I do tend to run with the git HEAD version,
so have been running the pre-release and not just recently updated to
the new version. My mbsync config has not changed. My mu4e config has
also not changed since the changes re mu config, but as I was running
the dev version, those changes were done a while back.

**Comment by djcb** [comment] 2020-05-01 07:14
Thanks, @theophilusx; there were indeed a few changes (fixes/refixes) recently for things that would influence the mitigation (in particular, `mu4e-change-filenames-when-moving`), so that could have done.

@dschrempf: does ugrading help you as well?

**Comment by tshu-w** [comment] 2020-05-01 09:45
I meet this issue all the time with Gmail. After I received an email, read it, the email was moved to the trash but not marked as read. 
<img width="1580" alt="Screen Shot 2020-05-01 at 5 09 59 PM" src="https://user-images.githubusercontent.com/13161779/80795408-f64d3400-8bce-11ea-8b4d-a850e56d7e7b.png">
When I received an email, it was in:
```
~/.mail/gmail/inbox/new
-rw-------  1 wangtianshu  staff   4.1K May  1 17:36 1588325766.37596_1.MacBook-Pro,U=30:2,
```
after I read it: 
```
~/.mail/gmail/inbox/cur
-rw-------  1 wangtianshu  staff   4.1K May  1 17:36 1588326048.51ac274e325f4e35.MacBook-Pro.local:2,S
```
then I press `u` to make it sync with mbsync, it's so weired that the mail was moved to `gmail/trash/new`:
```
~/.mail/gmail/trash/new
-rw-------  1 wangtianshu  staff   4.1K May  1 17:41 1588326085.40045_1.MacBook-Pro,U=108:2,
```

**Comment by manuel-arguelles** [comment] 2020-05-01 13:49
I can confirm that after upgrading to git (7a47784) and setting mu4e-index-cleanup to t and mu4e-index-lazy-check to nil. Everything seems to be working fine: read/unread, flag/unflag.

**Comment by dschrempf** [comment] 2020-05-02 07:09
I tried with the latest commit `59ed21b0`, `mu4e-index-cleanup t`, and `mu4e-index-lazy-check nil`. I can now mark mail as read and unread, and the changes get propagated to the server. However, I can not anymore flag messages. The changes do not even get applied without any sync operation, they are just ignored. I.e., I flag a message, apply the changes, and when I re-enter the bookmarked search, the mail is unflagged.

**Comment by dschrempf** [comment] 2020-05-02 10:40
I just removed the `mu4e-index-*` settings and still everything works fine!

**Comment by nivekuil** [comment] 2020-05-04 03:14
It looks like the line pointed out by tarsius here https://github.com/djcb/mu/commit/a5dccffcdfa3aeb1908832bf467f90db82b7f82c#r38811721 made it into 1.4.3 and broke `mu4e-change-filenames-when-moving` and was fixed in the later commit https://github.com/djcb/mu/commit/7a47784d789c9fcab1b484e1c4fdd1f2bd3751ad. I think this issue can be closed.

**Comment by djcb** [comment] 2020-05-04 06:43
Okay, closing this.

@dschrempf: I'm using `fetchmail` but that doesn't sync back to the server (avoiding various surprises), which works just fine for me. If you need (inherently trickier) two-way sync, you can use mbsync/offlineimap (but I don't currently use those). Occasionaly, it could be surprising.

**Closed by djcb** 2020-05-04 06:43 UTC
Labels: needinfo
