### ISSUE TITLE
[mu4e bug] severe: marking and moving messages in trash deletes message from filesystem

### ISSUE THREAD

**Issue by bjc** [djcb/mu#2579] opened 2023-10-30 13:50 UTC
**Describe the bug**
I had a message in my Trash folder, hit '?' to mark it unread, then 'm' to move it to another folder. After pressing 'x' and confirming, mu4e issued the warning:
```
mu4e-warn: [mu4e] No message at /net/snorlax/home/bjc/.cache/mail/spork/Trash/cur/1698667581_0.900.psyduck,U=122981,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,ST
```
and the message was entirely missing from my filesystem.

**How to Reproduce**
1) open trash folder
2) select message
3) mark as unread with '?'
4) move to folder 'm' followed by folder name
5) execute actions with 'x'
6) confirm execution

**Environment**
emacs 29.0.92
mu4e 1.10.5
mu 1.10.5

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by djcb** [comment] 2023-10-30 15:08
Does this always happen or only once? Are you using a program like `mbsync` to grab your email?

**Comment by bjc** [comment] 2023-10-30 15:13
i'm using `offlineimap` to sync mail once per minute, but this happens every time, so barring extremely bad timing luck over multiple tests, I don't think that's a factor.

**Comment by bjc** [comment] 2023-10-30 15:22
after further testing, it's not every time. i've had it happen a few times, but i'm not sure what the difference is between tests.

**Comment by djcb** [comment] 2023-10-30 15:25
Hmm, the `?` should not matter, since there's no `x` after, and the `m` replace it. 
Some more questions:
- Can you reproduce without the `?` ? 
- Can you reproduce this using other folders?
- Does the file exist _before_  you issues those commands (i.e., can you open them)?

(at least I cannot reproduce it at all).

**Comment by bjc** [comment] 2023-10-30 16:02
i'm now running into trouble reproducing it, but have previously made it happen three times with the steps outlined above. i'll keep trying to see if i can isolate the issue. when i submitted the bug report, i was only able to reproduce in the trash folder (an attempt in my inbox folder worked as one would expect), so i assumed that was relevant. now i'm not so sure.

i'll update this ticket as i learn more.

**Comment by djcb** [comment] 2023-11-16 09:46
Any update on this? I.e., steps to reproduce, esp. as detailed in my earlier comment? Thanks!

**Comment by bjc** [comment] 2023-11-26 14:27
"Dirk-Jan C. Binnema" ***@***.***> writes:

> Any update on this? I.e., steps to reproduce, esp. as detailed 
> in my earlier
> comment? Thanks!

I've managed to reproduce it a once more, though the it was more 
complicated than I initially reported. I haven't had the time to 
try again in the last while, but my last steps were:

1) open message
2) move message from inbox to review mailbox
3) mark unread
4) execute
5) jump to review mailbox
6) move message back to inbox
7) execute

I'm not sure how much of this is necessary due to lack of testing, 
and my notes are a bit slapdash, but if you want to give this flow 
a try, maybe it'll break for you, too.

-bjc

**Comment by bjc** [comment] 2024-01-09 15:51
> And most important, can you see what happens to the file representing the message? You can see the path (changing slightly) with `mu4e-copy-message-path`. Ie., check after each step, and see if the file is still on the file system.

Sorry, I thought I'd mentioned: they're deleted from the file system. I used a recursive grep on my mailbox folder to try and find them and they're gone.

**Comment by bjc** [comment] 2024-01-09 17:00
After doing a little more testing with the logs on, i think today's lossage is different than the previous, because this time the messages are moved, but they're moved to an "Archive" folder, rather than the "Review" folder I specify in the call to `mu4e-mark-at-point`.

The messages that prompted this thread, however, weren't there, and when I lost them I grepped my mailbox for them to verify they were gone gone.

**Comment by djcb** [comment] 2024-01-10 07:25
At least part of the problem sounds very much like a maildir synchronization thing, where messages are changed behind mu's back (through `offlineimap`) etc.

To dig a little deeper, try `M-x mu4e-toggle-logging` and press `$` before trying this, as well as checking the systemd journal if you're using that `journalctl _COMM=mu -f ` and set `mu4e-debug` and `mu4e-mu-debug` to `t`. Then, restart `mu4e`.

Now, you can try to reproduce with just:

1) mark-for-review for some message M
2) `x` (i.e., (`mu4e-mark-execute-all`) and confirm
3) now message M is gone, both from its source and target maildir?

Can you reproduce the above (without any other steps)? Are there errors from mu4e?

**Comment by djcb** [comment] 2024-03-18 20:29
Anyway, can't do  much without the information, so closing this. Note, a recent mailing list thread sounds very familiar: 
https://groups.google.com/g/mu-discuss/c/PD0OANgRDmc

**Closed by djcb** 2024-03-18 20:29 UTC
Labels: bug, cannotreproduce, needinfo, mu4e
