### ISSUE TITLE
mu4e uses a lot of CPU and takes several seconds to reoload 

### ISSUE THREAD

**Issue by tychoish** [djcb/mu#1279] opened 2018-07-01 18:45 UTC
## Expected or desired behavior

Header's view should refresh quickly and MU should not use 100% CPU for prolonged periods of time.

## Actual behavior

I've been using mu/mu4e for years and it's great. However, after a recent update, refreshing bookmark searches/views began taking a rather long time and I noticed that the mu process (managed by emacs) was pegging an entire CPU (thread/core/etc.) While reploying and reading email works fine, the Header view takes a rather long time to refresh. 

## Versions of mu, mu4e/emacs, operating system etc.

mu 1.0 installed on arch linux from OS packages.

## Any other detail

I'm not sure this is the best place to register this comment. My data set is pretty large (1.6gb and 3.6gb) so it feels like a bad index or query but I don't even know where to start. It also got precipitously bad after a recent upgrade.

**Comment by djcb** [comment] 2018-07-02 05:30
Hmm, what happens when you search from the command-line (with --threads/--include-related etc.)?

**Comment by djcb** [comment] 2018-07-08 17:43
This a bit of a dup of #163 perhaps. I can't reproduce any slowdown on my system  at least. It might be something changed with recent emacs.

Can you profile this? I.e first step would be to see if the problem is with mu4e only or with mu in general; and in the former case, would be interesting to see what happens when using some older emacs version. In the latter case, some OS-level profiles (e.g. `perf`) would be most useful.

**Comment by djcb** [comment] 2018-07-08 17:45
This a bit of a dup of #163 perhaps. I can't reproduce any slowdown on my system  at least. It might be something changed with recent emacs.

Can you profile this? I.e first step would be to see if the problem is with mu4e only or with mu in general; and in the former case, would be interesting to see what happens when using some older emacs version. In the latter case, some OS-level profiles (e.g. `perf`) would be most useful.

**Comment by tpapp** [comment] 2018-07-19 07:47
I also have this, on Emacs 26.1 and latest Emacs snapshot, on Ubuntu 18.04, with `mu` compiled from `master`. The computer is otherwise reasonably fast (all files l local, on an SSD, 16GB RAM).

Reverting to `v1.0` fixes things. I am happy to bisect.

**Comment by djcb** [comment] 2018-07-19 10:50
@tpapp: bisecting would be most welcome, thanks!

**Comment by tpapp** [comment] 2018-07-19 14:34
Result of bisecting:
```
1cb3cbc94db519b4b8ff0241f6e5559e17db4f56 is the first bad commit
commit 1cb3cbc94db519b4b8ff0241f6e5559e17db4f56
Author: djcb <djcb@djcbsoftware.nl>
Date:   Fri Jun 29 18:08:43 2018 +0300

    mu4e: fix bbdb doc

:040000 040000 70df1bb2eb3e881a8ea41685131df021262390f7 712c53f8b925eef7a249ff11ae50f40ce8b3834d M      mu4e
```

This is how I bisected: for each stage,

1. `./configure`
2. `make`
3. run Emacs for at least 30 minutes (CPU problem usually shows much sooner)

I did not do `make clean` or `make distclean`. `./configure` output:
```
mu configuration is complete.
------------------------------------------------
mu version                           : 1.1.0

Xapian version                       : 1.4.5
GLib version                         : 2.56.1
GMime version                        : 2.6.23
Emacs version                        : GNU Emacs 26.1

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : no
McCabe's Cyclomatic Complexity tool  : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
```

**Comment by tpapp** [comment] 2018-07-24 09:20
I just looked at the commit 1cb3cbc94db519b4b8ff0241f6e5559e17db4f56 and I find it hard to believe that this is the root of the issue, that looks like just fixing a malformed `setq`. Nevertheless, I kept experiencing this issue sporadically in other modes, and disabling `visual-line-mode` everywhere apparently fixed it.

**Comment by djcb** [comment] 2018-08-04 10:26
Thanks for the bisecting; but how weird, the actual change there is in the manual! And it's a bit hard to see how emacs' visual-line-mode setting would influence the `mu` process. So, some mysteries to solve!

What would be useful is to get a profile when mu seems so busy, ie. with `perf`. There must be something strange going on. Are you able to do that?

**Comment by tpapp** [comment] 2018-08-05 15:43
I think I will bisect again, I may have been too hasty to pronounce some versions OK.

The weird thing is that as soon as I call `profiler-start`, CPU turns back to normal immediately. Perhaps some kind of race condition in Emacs itself, that interacts poorly with `mu4e`.

**Comment by tpapp** [comment] 2018-08-22 12:19
Since I disabled `beacon-mode`, CPU usage has been back to normal. I confirmed this extensively with the bisected version above, and the `master` for `mu4e`. Regarding the bug I was experiencing, at this point I am not even sure if `mu4e` is involved at all, or if this is an interaction between `beacon` and `mu4e`.

Cf https://github.com/Malabarba/beacon/issues/62

**Comment by tychoish** [comment] 2018-08-30 16:17
I don't use becaon, and am still seeing this issue. 

In my setup it looks like the `mu` process itself is the thing that using 100% cpu. 

Turning on the cpu profiler in emacs does seem to make mu4e more responsive, though in it's still slow in cases when mu is doing an index operation (e.g. downloading new messages.)

**Comment by djcb** [comment] 2018-09-26 17:32
Some profile data from the mu process would be useful, otherwise it's very hard to find the cause for this -- e.g. a build with symbols and `perf`. Would you able to do that?

**Comment by djcb** [comment] 2019-02-24 16:16
Closing this, but of course am willing to reopen with some profiling data (e.g `perf` in Linux) and/or a bisect............ Thanks!

**Closed by djcb** 2019-02-24 16:16 UTC
Labels: needinfo

**Comment by tychoish** [comment] 2019-02-24 17:27
I've locally resolved the annoyance by cleaning up and deleting a bunch of email, and things now seem zippy. 

I'm not a very regular user of email, and so it felt like it got precipitously worse, when in fact I might have just been seeing a normal linear degradation.
