### ISSUE TITLE
when mu4e-compose-in-new-frame is set, mu4e closes currently focused frame

### ISSUE THREAD

**Issue by malb** [djcb/mu#781] opened 2016-01-31 13:26 UTC
I have `(setq  mu4e-compose-in-new-frame t)` in my config. When I send a message and shift focus away from the compose frame, then the frame which has the focus by the time sending finished is closed, not the frame in which I composed my e-mail. 

Looking `mu4e-compose.el` it seems to do the right thing™ so I'm a bit at a loss in understand the observed behaviour.

```emacs-lisp
(defun mu4e-sent-handler (docid path)
  "Handler function, called with DOCID and PATH for the just-sent
message. For Forwarded ('Passed') and Replied messages, try to set
the appropriate flag at the message forwarded or replied-to."
  (mu4e~compose-set-parent-flag path)
  (when (file-exists-p path) ;; maybe the draft was not saved at all
    (mu4e~proc-remove docid))
  ;; kill any remaining buffers for the draft file, or they will hang around...
  ;; this seems a bit hamfisted...
  (dolist (buf (buffer-list))
    (when (and (buffer-file-name buf)
               (string= (buffer-file-name buf) path))
      (if (and mu4e-compose-in-new-frame (window-system))
	  (progn
	    (switch-to-buffer buf)
	    (when (and (get-buffer-window buf)
		       (window-frame (get-buffer-window buf)))
	      (delete-frame (window-frame (get-buffer-window buf)))))
	)
      (if message-kill-buffer-on-exit
	  (kill-buffer buf))
      ))
  ;; now, try to go back to some previous buffer, in the order
  ;; view->headers->main
  (if (buffer-live-p mu4e~view-buffer)
      (switch-to-buffer mu4e~view-buffer)
      (if (buffer-live-p mu4e~headers-buffer)
          (switch-to-buffer mu4e~headers-buffer)
          ;; if all else fails, back to the main view
          (when (fboundp 'mu4e) (mu4e))))
  (mu4e-message "Message sent"))
```

**Comment by zakkak** [comment] 2016-01-31 16:03
I also observe this behavior, but since I don't use async sending didn't care much about it.

I think that the problem is that it switches to the correct buffer in the wrong window and then gets the window (which by now is the wrong one) and closes it:
``` cl
        (switch-to-buffer buf)
        (when (and (get-buffer-window buf)
               (window-frame (get-buffer-window buf)))
          (delete-frame (window-frame (get-buffer-window buf)))))
```

**Comment by malb** [comment] 2016-02-11 14:37
FWIW, patching `mu4e-sent-handler` to

```emacs-lisp
(defun mu4e-sent-handler (docid path)
  "Handler function, called with DOCID and PATH for the just-sent
message. For Forwarded ('Passed') and Replied messages, try to set
the appropriate flag at the message forwarded or replied-to."
  (mu4e~compose-set-parent-flag path)
  (when (file-exists-p path) ;; maybe the draft was not saved at all
    (mu4e~proc-remove docid))
  ;; kill any remaining buffers for the draft file, or they will hang around...
  ;; this seems a bit hamfisted...
  (dolist (buf (buffer-list))
    (when (and (buffer-file-name buf)
               (string= (buffer-file-name buf) path))
      ;; (if (and mu4e-compose-in-new-frame (window-system))
      ;; 	  (progn
      ;; 	    (switch-to-buffer buf)
      ;; 	    (when (and (get-buffer-window buf)
      ;; 		       (window-frame (get-buffer-window buf)))
      ;; 	      (delete-frame (window-frame (get-buffer-window buf)))))
      ;; 	)
      (if message-kill-buffer-on-exit
	  (kill-buffer buf))
      ))
  ;; now, try to go back to some previous buffer, in the order
  ;; view->headers->main
  ;; (if (buffer-live-p mu4e~view-buffer)
  ;;     (switch-to-buffer mu4e~view-buffer)
  ;;     (if (buffer-live-p mu4e~headers-buffer)
  ;;         (switch-to-buffer mu4e~headers-buffer)
  ;;         ;; if all else fails, back to the main view
  ;;         (when (fboundp 'mu4e) (mu4e))))
  (mu4e-message "Message sent"))
```

and adding 

```emacs-lisp
(defun malb/mu4e-compose-frame ()
  (set-window-dedicated-p (get-buffer-window (current-buffer)) t)
  )
(add-hook 'mu4e-compose-mode-hook #'malb/mu4e-compose-frame)
```

seems to produce the behaviour I want.

**Comment by djcb** [comment] 2016-02-20 10:33
We're closing the frame in a slightly different way now; can you check if it works, even when using async sending?

**Comment by malb** [comment] 2016-02-21 13:15
After sending my email the new code correctly closes my dedicated frame for composing the email. However, it also closes my dedicated frame for mu4e. That is, I have three fames: normal Emacs stuff, mu4e headers view, mu4e compose window and sending an e-mail now closes the latter two, whereas I'd expect it to only close the last frame.

**Comment by djcb** [comment] 2016-02-21 14:44
Thanks for testing! I did some changes -- does it work for your use case now?

**Comment by malb** [comment] 2016-02-21 15:41
Are your changes on `master` yet? Last check-in is from yesterday, sorry if this is naive.

**Comment by djcb** [comment] 2016-02-21 16:01
Oh, yeah! Didn't push yet, but have done so now.

**Comment by malb** [comment] 2016-02-21 17:33
Thanks a bunch! It seems to work as expected. I'll report back, should I encounter uexpected behaviour.

**Comment by djcb** [comment] 2016-02-21 18:06
Excellent -- thanks for the quick response!

**Closed by djcb** 2016-02-21 18:06 UTC
Labels: needinfo
