### ISSUE TITLE
Find-related doesn't find message in a particular thread

### ISSUE THREAD

**Issue by dkogan** [djcb/mu#830] opened 2016-04-12 21:35 UTC
Hi.

I'm using mu4e. Today I encountered a thread where some of the messages were not being reported as related to the rest of the thread. I'm including a minimized demo. There are 3 mail files msg[012]: msg2 is a reply to msg1 is a reply to msg0. The Message-ID and In-Reply-To fields confirm this. However I see this:

> dima@shorty:~/mu/mu$ ./mu find msgid:928715624.1082166.1460432287234.JavaMail.yahoo@mail.yahoo.com -r
> Mon Apr 11 20:38:07 2016 iiiiiiii aaaaa@yahoo.com asdfasdasdf
> Tue Apr 12 10:31:29 2016 uyyyyyy tttttttt@gmail.com Re: xzcvzxcvzxcv
> 
> dima@shorty:~/mu/mu$ ./mu find msgid:906353689.1456243.1460482844318.JavaMail.yahoo@mail.yahoo.com -r
> Tue Apr 12 10:40:44 2016 fffff eeeee@ymail.com Re: qwerqwerwqe

I.e. msg2 is not reported as being related to msg0 and msg1
## Expected or desired behavior

All messages in the thread should be related ot each other
## Actual behavior

msg2 is seen as separate
## Steps to reproduce

Take the given 3 messages, "mu index" and then the "mu find" commands above.

I observe the issue every time
## Versions of mu, mu4e/emacs, operating system etc.

mu from git. Debian.

Thanks!
[mu_bug_messages.tar.gz](https://github.com/djcb/mu/files/215990/mu_bug_messages.tar.gz)

**Comment by seanfarley** [comment] 2016-06-08 03:43
I seem to have hit this as well. It's weird because this was working until recently. I've tried to bisect to no avail.

**Comment by seanfarley** [comment] 2016-06-08 18:51
More information: it seems to only happen when I reply to a thread on a mailing list (it seemingly worked today with a personal conversation).

**Comment by dkogan** [comment] 2016-06-09 02:55
On June 8, 2016 11:51:13 AM PDT, Sean Farley <notifications@github.com> wrote:
>More information: it seems to only happen when I reply to a thread on a
>mailing list (it seemingly worked today with a personal conversation).

Do you not observe the issue with the test case attached above? Somebody just needs to go debug it. I just don't have the time right now

**Comment by seanfarley** [comment] 2016-06-10 18:19
Sorry, haven't had time to look at your messages :-/

**Comment by djcb** [comment] 2016-07-24 17:28
I think this might have been fixed with a related fix.... can you still reproduce this?

**Comment by dkogan** [comment] 2016-07-25 00:13
Hi. I'm still observing this issue with both the dev and master branches from today's git.

**Closed** 2017-11-04 13:18 UTC
Labels: needinfo
