### ISSUE TITLE
message hard to index?

### ISSUE THREAD

**Issue by bderembl** [djcb/mu#1202] opened 2018-03-01 07:42 UTC
I noticed that some messages are considerably slowing down mu4e. These are not the largest (in size) messages but rather messsages with a lot of data in it (attachment with huge arrays of numbers). I found one of these messages and deleted it which considerably speeded up mu4e. But I suspect I have a couple more in my mailbox.

Is there a way to find these messages (again this is not a matter of sorting the messages by size but to find the messages that take a lot of space in the index) 
I am not sure my request is well formulated but if this makes sense, any hint to solve this issue will be greatly appreciated

edit: it is not only slowing down the index process but every action in mu4e
I am using `mu4e-index-cleanup nil`   and  `mu4e-index-lazy-check t`

**Comment by djcb** [comment] 2018-04-24 15:42
I guess the only way is to measure the time one of those messages takes to index. If you have a (sufficiently censored) example message, that would help.

**Comment by djcb** [comment] 2018-06-11 09:58
Can't reproduce this -- so closing this for now. If you have an example message which exhibits this behavior, feel free to attach it here, and we can take a look. Thanks.

**Closed by djcb** 2018-06-11 09:58 UTC
Labels: needinfo
