### ISSUE TITLE
Sort Order Reversed Within Threads

### ISSUE THREAD

**Issue by jterk** [djcb/mu#1657] opened 2020-04-22 17:09 UTC
## Expected or desired behavior

I typically sort mail in mu4e in chronological order - oldest at the top. My expectation is that this ordering will hold within a thread. I.e. (TN denotes relative timestamps):

* [T1] - Some Other Subject
* [T0] - Initial Email
  * [T2] - Re: Initial Email
  * [T3] - Re: Initial Email
* [T4] Yet Another Subject

## Actual behavior

Since updating to mu/mu4e 1.4.1 I observe the following sorting behavior, instead. Note that the thread as a whole is sorted correctly relative to other messages, but the messages within the thread are in the opposite order of what is expected (the most recent message in the thread is first):

* [T1] - Some Other Subject
  * [T3] - Re: Initial Email
  * [T2] - Re: Initial Email
* [T0] - Initial Email
* [T4] Yet Another Subject

This screenshot demonstrates the behavior. The thread beginning on 2019-07-25 is sorted correctly (oldest-to-newest) relative to the emails before (most recently updated on 2019-06-27, not visible here)  and after (2020-02-06), but the items within the thread are sorted newest-to-oldest

![Screen Shot 2020-04-22 at 09 51 43](https://user-images.githubusercontent.com/4620/80010901-f5562d00-847f-11ea-9595-8d7a91dfe1f4.png)

## Steps to reproduce

Receive some email, including some that should be threaded. In header view, sort by date (`O d`), toggle threading, if necessary (`P`).

## Versions of mu, mu4e/emacs, operating system etc.

* mu/mu4e: 1.4.1
* emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, NS appkit-1671.40 Version 10.14.4 (Build 18E226)) of 2019-08-30
* OS: Mac OS X 10.15.4

**Comment by djcb** [comment] 2020-04-22 18:36
The order has changed indeed, and this is per design (e.g. series of patches are easier to read chronologically); after some discussion on the mailing-list (see "Changing the way threads are sorted") it seemed that most people preferred the new order.

**Comment by jterk** [comment] 2020-04-22 22:57
I see - I find it very surprising that the sorting within a thread is exactly the opposite of the sort order I choose.

**Comment by czan** [comment] 2020-04-28 06:23
I'm not sure this is actually doing the right thing. If we look at [the PR](https://github.com/djcb/mu/pull/1444) linked from [the mu-discuss thread](https://groups.google.com/d/topic/mu-discuss/zvaJPRrd0NE/discussion) I think there's something going wrong.

This is the example from the PR:
```
2020-01-16  Remi Pommarel     [PATCH v5 0/7] PCI: amlogic: Make PCIe working reliably on AXG platforms
... other lines ...
2020-01-16  Remi Pommarel       ┗━▶ [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-16  Bjorn Helgaas       ┃        ┣━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-23  Neil Armstrong      ┃            ┗━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-23  Jerome Brunet       ┃        ┗━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
```
If my mail was sorted that way I would be happy, but what I'm getting is effectively this:
```
2020-01-16  Remi Pommarel     [PATCH v5 0/7] PCI: amlogic: Make PCIe working reliably on AXG platforms
... other lines ...
2020-01-16  Remi Pommarel       ┗━▶ [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-23  Jerome Brunet       ┃        ┣━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-16  Bjorn Helgaas       ┃        ┗━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-23  Neil Armstrong      ┃            ┗━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
```
Note that the 2020-01-23 email has been sorted *before* the 2020-01-16 email that is its sibling. In my case, this is happening even in the case where there is no second 2020-01-23 email. So it ends up like this:
```
2020-01-16  Remi Pommarel     [PATCH v5 0/7] PCI: amlogic: Make PCIe working reliably on AXG platforms
... other lines ...
2020-01-16  Remi Pommarel       ┗━▶ [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-23  Jerome Brunet       ┃        ┣━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
2020-01-16  Bjorn Helgaas       ┃        ┗━▶ Re: [PATCH v5 7/7] PCI: amlogic: Use AXG PCIE
```
Is that really the intended behaviour? That doesn't seem to be what the PR is describing, and it makes for very unnatural reading within threads.

**Comment by czan** [comment] 2020-04-28 22:57
Okay, I think I've realised why this doesn't match my expectations: I sort my emails by date ascending.

I like to start at the top of my list and work through sequentially. That means that I work my way down the list of emails, starting with the oldest and working towards now. With the new code, [these lines](https://github.com/djcb/mu/pull/1444/files#diff-3f94cf8033f7966ce02e3156873173ceR368-R371) reverse the sort order so that within each thread it's sorted in the opposite order to what I want - the newest emails in the thread end up at the top. That means I have to go top-to-botton at the top level, but then bottom-to-top within a thread.

However, if I sort by date descending then all of my threads are in the opposite order to what I want (ie. the newest thread is at the top), but within each thread the order is appropriate for me to read from top to bottom.

I compiled `mu` locally with `sort_func_child` redefined to the following definition, and now each thread is in the appropriate order for me to read top-down, irrespective of whether I am sorting by date ascending or date descending.

```
static int
sort_func_child (MuContainer *a, MuContainer *b, SortFuncData *data)
{
	return container_cmp (a, b, data->mfid);
}
```

I don't know how this would affect the sort when using other sort fields, though.

**Comment by czan** [comment] 2020-05-07 12:29
Nine days later and I'm very happy with my patched behaviour. I'm not sure how to progress the conversation about getting this into mu, though.

**Comment by djcb** [comment] 2020-05-09 14:45
Best start a discussion on the mailing-list, explain why your method is different / better and we see from there :)

(I'm a bit reluctant adding more _options_ for such things)

**Comment by czan** [comment] 2020-05-11 11:30
[Done.](https://groups.google.com/forum/#!topic/mu-discuss/EWNpMoiIkuI) I'm curious to hear what people say.

**Comment by djcb** [comment] 2020-05-17 11:47
Thanks - I have merged this.

**Closed by djcb** 2020-05-17 11:47 UTC
