### ISSUE TITLE
opening a PGP-signed message is slow

### ISSUE THREAD

**Issue by ArneBab** [djcb/mu#1536] opened 2020-01-03 17:48 UTC
## Expected or desired behavior

Opening a PGP-signed message should be just as instant as opening a non-signed message.

It would be great if the verification could happen asynchronously and update the state of the Signature: field at the once it is finished.

1. Signature: checking… (gray?)
2. Signature: unverified/verified (Details)

## Actual behavior

When I open a signed message, mu4e displays "Waiting for message ..." for several seconds before showing the message. I see delays between 3 and 7 seconds.

## Steps to reproduce

- In headers view, click ENTER on an email just above a signed email.
- Wait until the non-signed message is displayed.
- Click n (for next message). It shows the waiting for message dialog.

## Versions of mu, mu4e/emacs, operating system etc.

- mu (mail indexer/searcher) version 1.2.0
- OS: GNU Guix
- Emacs 26.1
- CPU clockspeed: 1200MHz (6 cores / 12 threads)

**Comment by djcb** [comment] 2020-03-28 09:10
FWIW, At least in the later 1.3.x and the gnus-based viewer, mu4e/mu don't do any crypto when viewing a message.

**Comment by ArneBab** [comment] 2020-03-28 12:38
I now tried to package/update 1.3.9 for Guix, but found that there’s no release tarball (mu-1.3.9.tar.xz). It would be cool if you could upload that!

**Comment by djcb** [comment] 2020-03-28 12:53
Oh sure: https://github.com/djcb/mu/releases/tag/1.3.10

**Comment by ArneBab** [comment] 2020-03-29 21:07
I now updated, but when trying to reply I get the error (anonymized):
```
Debugger entered--Lisp error: (void-variable mu4e-user-mail-address-list)   
  mu4e-personal-addresses()                                                 
  #f(compiled-function (cc-cell) #<bytecode 0x27c5011>)(("foo bar"
  cl--position(nil (("foo bar" . "foo.bar@example.com")) 0 n
  cl-position(nil (("foo bar" . "foo.bar@example.com")) :if 
  apply(cl-position nil (("foo bar" . "foo.bar@example.com")
  cl-find(nil (("foo bar" . "foo.bar@example.com")) :if #f(c
  apply(cl-find nil (("foo bar" . "foo.bar@example.com")) :i
  cl-find-if(#f(compiled-function (cc-cell) #<bytecode 0x27c5011>) (("foo
  mu4e-message-contact-field-matches-me((:docid 221614 :subject "Re: 3D-Druc
  mu4e~draft-reply-construct-recipients((:docid 221614 :subject "Re: 3D-Druc
  mu4e~draft-reply-construct((:docid 221614 :subject "Re: 3D-Drucken für Kra
  mu4e-draft-open(reply (:docid 221614 :subject "Re: 3D-Drucken für Krankenh
  mu4e~compose-handler(reply (:docid 221614 :subject "Re: 3D-Drucken für Kra
  mu4e~proc-filter(#<process  *mu4e-proc*> "\376dc0\377(:compose reply :orig
```

That variable isn’t found with `C-h v`, but it is in my init.el in custom-set-variables, and a fallback could be `user-mail-address`.

Was the variable-definition removed, and does that cause custom-set-variables to no longer set it?

**Comment by ArneBab** [comment] 2020-03-29 21:18
With 1.3.10 I still see multi-second wait time until a signed message is displayed.

If it helps you, I can send you a signed message so you can test it on your own machine.

**Comment by djcb** [comment] 2020-03-30 07:00
In the 1.3.x case, the behavior for the default view is not much different; however when using `(setq mu4e-view-use-gnus t)` (the gnus-derived view), `mu` doesn't do any verification of the signatures, instead it's delegated to gnus' machinery for that.

What I've seen that in _both_ cases, verification can be a bit slow (in my case, it's less than 1s, but still noticeable); for that reason suspect it all comes down to the underlying gpg/gpgme. That does not immediately help you, of course. To be continued.

**Comment by gour** [comment] 2020-04-11 15:51
Hello, 

I'm experiencing the same issue as @ArneBab, iow.

```
Debugger entered--Lisp error: (void-variable mu4e-user-mail-address-list)   
  mu4e-personal-addresses()      
[...]
```

when I have `(setq mu4e-view-use-gnus t)`, but when I disable it, everything is fine except a little slow down. (`mu-1.3.9` on Fedora-32(fc32-beta), Emacs-26.3)

Will something change in regard in the upcoming 1.4 release or do you recommend to simply not use `(setq mu4e-view-use-gnus t)` ?

**Comment by djcb** [comment] 2020-04-13 08:41
If you look at the code in the backtrace and compare it to the source-code, you'll notice that the latter doesn't _use_ that variable anymore, so apparently, you're mixing new & old code.

I.e. clean up your build and recompile (`./autogen.sh` should do the trick)
 
And yes, `mu4e-user-mail-address-list` is gone, see `NEWS.org` for a bit more detail.

**Comment by gour** [comment] 2020-04-13 09:43
> If you look at the code in the backtrace and compare it to the source-code, you'll notice that the latter doesn't _use_ that variable anymore, so apparently, you're mixing new & old code.

Hmm, the problem is that it is fresh install, iow. I moved from Debian to Fedora...

> I.e. clean up your build and recompile (`./autogen.sh` should do the trick)

iow. I did not build from the src, but using package from official repo?

**Comment by djcb** [comment] 2020-04-13 10:37
Hmmm, seems Fedora picked a development release for F32?  The 1.3 series are for development, and they happened to pick some "in-between" version... 

I filed: https://bugzilla.redhat.com/show_bug.cgi?id=1823325

**Comment by djcb** [comment] 2020-05-06 10:16
BTW, I've pushed a few changes that should help for the slowness.... does it help your case?

**Comment by ArneBab** [comment] 2020-05-07 10:03
Are they already in 1.4.3?

**Comment by djcb** [comment] 2020-05-07 10:21
> Are they already in 1.4.4?

No; it is even newer than that.

**Comment by ian-kelling** [comment] 2020-05-19 01:26
For me, it takes over a minute to load unverified messages

```
Emacs version
commit 35d56948256
Date:   Sun Jan 5 21:55:20 2020 +0100


mu version
commit 1c88651f41b02
Date:   Mon May 18 18:51:25 2020 +0300
```

**Comment by ian-kelling** [comment] 2020-05-19 01:36
I tried using gnus view and it locks up emacs about the same amount of time, even after

```
(setq mm-verify-option 'never)
```

**Comment by ian-kelling** [comment] 2020-05-19 01:40
Fixed by turning off this option in my gpg ~/.gnupg/gpg.conf

```
#keyserver-options auto-key-retrieve
```

Still, mu4e and gnus should not hang when that is on.

**Comment by djcb** [comment] 2022-05-22 09:20
Thanks, this not seems like a mu/mu4e problem, closing.

**Closed by djcb** 2022-05-22 09:20 UTC
Labels: needinfo
