### ISSUE TITLE
[mu4e bug] error in process filter: mu4e-error: [mu4e] Error 32825: failed to add path

### ISSUE THREAD

**Issue by titanofold** [djcb/mu#2358] opened 2022-11-01 13:42 UTC
**Describe the bug**

Has a conniption after sending the email. Doesn't indicate where the actual error lies, so I'm at a loss of what or how to trouble shoot.

```
[mu4e] Switched context to Gentoo
Mark set
(New file)
Auto-saving...done
Undo [13 times]
next-line: End of buffer
Saving file /home/titan/.maildir/gentoo/Drafts/cur/1667308971.29a595441a867148.gilman:2,DS...
Wrote /home/titan/.maildir/gentoo/Drafts/cur/1667308971.29a595441a867148.gilman:2,DS
[mu4e] Saved (36 lines)
It seems `org-mime-htmlize' is NOT called; send anyway? (y or n) y
Sending...
Sending via mail...
Saving file /home/titan/.maildir/gentoo/Sent/cur/1667309023.bf7f13d074393bf6.gilman:2,S...
Wrote /home/titan/.maildir/gentoo/Sent/cur/1667309023.bf7f13d074393bf6.gilman:2,S
Sending...done
error in process filter: mu4e-error: [mu4e] Error 32825: failed to add path
error in process filter: [mu4e] Error 32825: failed to add path
[mu4e] Retrieving mail...done
[mu4e] Update process returned with non-zero exit code
[mu4e] Indexing... checked 56051, updated 4
[mu4e] Indexing completed; checked 56051, updated 4, cleaned-up 2
[mu4e] Contacts updated: 10; total 6772
```

**How to Reproduce**

I replied to an email on the list and sent the email using `C-c C-c` as usual. I don't think the email fetch/update is related, as another took place with no error as I wrote this.

**Environment**
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0) of 2022-10-31
mu4e 1.8.10

**Checklist**
- [x] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [ ] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [x] you have read all of the above

I'm not sure if org-htmlize counts as a third-party extension. Otherwise, everything is fairly vanilla.

**Comment by djcb** [comment] 2022-11-12 06:07
I've pushed a change which should get you slightly more informative errors, but still it's unclear what happens. Can you reproduce with a basic setup (without org-mime etc.)?

**Comment by djcb** [comment] 2022-12-19 21:30
Okay, assuming that means "can't reproduce". Closing this.

**Closed by djcb** 2022-12-19 21:30 UTC
Labels: bug, mu4e
