### ISSUE TITLE
[mu4e bug] Duplicate entries in inbox headers view

### ISSUE THREAD

**Issue by baruchsiach** [djcb/mu#2327] opened 2022-09-01 12:45 UTC
**Describe the bug**

When inbox folder messages change state from unread to read, and then run
mu4e-update-mail-and-index, the message appears duplicate in the headers view
as below:

```
08/29/2022   👨     Thomas Petazzoni          [autobuild.buildroot.net] Your daily results for 2022-08-28
08/29/2022   👨     Thomas Petazzoni          └ ≡ [autobuild.buildroot.net] Your daily results for 2022-08-28
```

If I delete or move both messages, I get a message that a file is missing. If
I delete/move only the first, its duplicate disappears after refresh
(`mu4e-search-rerun`).

I guess this is related to Maildir file move from new/ to cur/. If I open the message
in mutt, thus moving it from new/ to cur/ outside of mu4e, the message does
not duplicate.

This bug is since upgrade from 1.6.x to 1.8.x.

**How to Reproduce**

1. Set `mu4e-headers-skip-duplicates` to false
2. Open a new inbox message to change its state from unread to read
3. Run `mu4e-update-mail-and-index`

**Environment**
mu/mu4e version 1.8.7-2 packaged by Debian testing. Emacs version 27.1 from Debian testing.

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by djcb** [comment] 2022-10-26 19:37
Hmm, I added a unit test to try to reproduce, but no luck so far.

**Comment by baruchsiach** [comment] 2022-10-27 05:49
> Hmm, I added a unit test to try to reproduce, but no luck so far.

What is the value of `mu4e-headers-skip-duplicates`? I can only reproduce with its value set to `nil`, and I don't see the test toggling it.

One more thing I can add is that when I send a reply to a duplicated message I get:

```
error in process filter: [mu4e] Error 32814: cannot read /home/baruch/Maildir/cur/1666803207.832_0.mail:2,S
```

This indicates that the code expects a (duplicate?) file under the `cur/` subdirectory, while in fact it is only under `new/`.

What else should I shared about the sate of the code running here to help you get to the bottom of this issue?

**Comment by djcb** [comment] 2022-10-27 07:06
In the description, skip-duplicates is false, which is what the test does as well. But turning it on and a few other variations don't seem to make a difference.

But the
```
error in process filter: [mu4e] Error 32814: cannot read /home/baruch/Maildir/cur/1666803207.832_0.mail:2,S
```
gives a hint.

After step 1 and 2 (but _before_ 3), check for the existence of the message under `cur/`. If it's there, do step 3, and after completion check if the file still exists.

**Comment by baruchsiach** [comment] 2022-10-27 09:45
Before step 2 I get:
```
$ grep -r Daily cur/ new/
new/1666848938.5938_0.mail:Subject: [Buildroot] [autobuild.buildroot.net] Daily results for 2022-10-26
```
After step 2, before 3 I get:
```
$ grep -r Daily cur/ new/
cur/1666848938.5938_0.mail:2,S:Subject: [Buildroot] [autobuild.buildroot.net] Daily results for 2022-10-26
```
After step 3 I get:
```
$ grep -r Daily cur/ new/
cur/1666848938.5938_0.mail:2,S:Subject: [Buildroot] [autobuild.buildroot.net] Daily results for 2022-10-26
```
The subject is now shown duplicated in the headers view:
```
10/27/2022   🔈     Thomas Petazzon... BR     [Buildroot] [autobuild.buildroot.net] Daily results for 2022-10-26
10/27/2022   🔈     Thomas Petazzon... BR     └ ≡ [Buildroot] [autobuild.buildroot.net] Daily results for 2022-10-26
```

**Comment by baruchsiach** [comment] 2022-11-03 16:11
I should note that when the `cannot read` message shows on email reply, the file is renamed to that its name ends with `,RS` instead of just `,S`. So the file named in the error message indeed does not exist. But I don't see this error if I reply to the email before step 3. So it is somehow related to the duplication issue.

**Comment by djcb** [comment] 2023-02-17 11:31
Thanks for testing. 

In the meantime, there have been a few changes in mu that may have made a difference ("join_paths"), do you still see this with recent (>= 1.9.18 or so) versions? If you're happy with 1.8.x, no need to get a newer version of course.

**Comment by baruchsiach** [comment] 2023-02-19 05:32
I'm currently using version 1.8.14 from Debian testing and the issue persists. Is there any easy way to test the development branch?

By the way, I see no 1.9.x tags in current git. Am I missing anything?

**Comment by djcb** [comment] 2023-02-19 07:02
Tags are used for releases, but not on  `master` (the development branch).

You can compile the development branch, see e.g. 
   https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html
whether that's easy depends a bit on experience which such things I suppose

Feel free to ask if anything is unclear.

**Comment by baruchsiach** [comment] 2023-02-20 17:21
It looks like current master as of commit 558745bf00b1e58 does not have this issue.

Unfortunately the 'V' key binding stopped working for some reason. But this is unrelated.

**Comment by djcb** [comment] 2023-02-23 18:28
Where did you find the V/W documentation?

**Comment by djcb** [comment] 2023-02-23 18:29
Anyway, closing this ticket, as the issue seems to be gone.

**Closed by djcb** 2023-02-23 18:29 UTC
Labels: bug, mu4e

**Comment by baruchsiach** [comment] 2023-02-23 23:48
> Where did you find the V/W documentation?

As of commit 5c037f7579dae, W is documented in `mu4e/mu4e.texi` line 2134.

V is documented in line 2149 of the same file.
