### ISSUE TITLE
[mu4e bug] Default value of MIME separator breaks sync with Protonmail

### ISSUE THREAD

**Issue by JonathanReeve** [djcb/mu#2177] opened 2021-11-04 21:53 UTC
**Describe the bug**
A clear and concise description of what the bug is, what you expected to happen and what actually happened.

Protonmail doesn't accept malformed emails, and so it chokes when trying to sync mail containing `--text follows this line--`, generated by mu4e. Here's the output of `mbsync protonmail`: 

```
C: 0/1  B: 1/5  F: +0/2 *0/0 #0/0  N: +1/1 *0/0 #0/0
IMAP command 'APPEND "Drafts" (\Draft \Seen) ' returned an error: NO failed to create new parser: message: malformed MIME header line: --text follows this line--
```

**To Reproduce**

1. Save a draft, using the default settings  
2. Try to sync that draft to Protonmail
3. Note that it won't sync, because `--text follows this line--` isn't a valid MIME header

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

Latest versions of mu, emacs, etc, released on NixOS unstable. 

**Checklist**
- [ ] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [ ] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [ ] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment] 2021-11-05 06:54
The actual messages written to disk should not include the `--text follows this line--`. 

However, they could appear in temporary / backup files; so either tell your sync tool to not attempt to sync such files, or instruct emacs to write those somewhere else; see e.g.
   https://emacs.stackexchange.com/questions/17210/how-to-place-all-auto-save-files-in-a-directory

**Comment by JonathanReeve** [comment] 2021-11-05 20:34
I don't think I have any temporary or backup files there. It's just one file with the contents: 

```
From: Jonathan Reeve <redacted>
To: <redacted>
Subject: Test
Date: Fri, 05 Nov 2021 16:30:20 -0400
User-agent: mu4e 1.6.9; emacs 27.2
--text follows this line--
#+OPTIONS: html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil tex:dvipng d:nil
#+STARTUP: hidestars indent inlineimages
:PROPERTIES:
:reply-to: nil
:attachment: nil
:alternatives: (utf-8 html)
:END:

* TODO test testing

```

Maybe the issue is that the certificate validation fails before it gets a chance to send it? EIther way, that line is definitely on the disk.

**Comment by djcb** [comment] 2021-11-05 21:03
Hmmm, can you provide tsteps-to-reproduce, starting with `emacs -q` and ending with such a message on your disk?

From your description, it seems this _always_ happens?

**Comment by theophilusx** [comment] 2021-11-05 21:44
I think it is something unusual in your local configuration. If I look
at the text of a draft message in my maildir (just using cat), there is
no --text follow this line-- or anything similar. When I check the draft
message on my remote server (using gmail web interface), the text is not
included either.

As Dirk pointed out, that line is not part of the 'real' message - only
part of the buffer Emacs uses to compose the message. For your remote
mail server to be seeing it, mbsync must somehow be picking up a
temporary or backup file (or something in your configuration is dumping
the internal working buffer to a file which mbsync sees as a message
file).

I would start by creating a minimal mu4e configuration and putting it
into a setup.el file and then run emacs -q -l /path/to/mu4e/setup.el and see
if you can reproduce the issue.  If you can, post the minimal setup.el
file, details of emacs and mu4e version and platform your on and then
perhaps someone can try reproducing your issue with the same config.

**Comment by husainaloos** [comment] 2021-11-08 02:00
I use protonmail as well and I can confirm that I DO NOT see any issue.

```
User-agent: mu4e 1.7.0; emacs 27.2
From: <redacted>
To: <redacted>
Subject: some subject
Date: Sun, 07 Nov 2021 19:58:48 -0600
--text follows this line--
#+OPTIONS: html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \n:t d:nil
#+STARTUP: hidestars indent inlineimages
:PROPERTIES:
:reply-to: nil
:attachment: nil
:alternatives: (text)
:END:

* TODO

```

**Comment by Chris00** [comment] 2021-11-11 09:31
The `--text follows this line--` on disk comes from you using [org-msg](https://github.com/jeremy-compostella/org-msg).  You should file an issue there.

**Comment by djcb** [comment] 2021-11-13 08:06
Thanks for checking, @Chris00. Closing this, it seems to be outside our sphere of influence.

**Closed by djcb** 2021-11-13 08:06 UTC
Labels: needinfo, mu4e, help
