### ISSUE TITLE
mu4e-view.elc seems to randomly differ for reproducible builds

### ISSUE THREAD

**Issue by jubalh** [djcb/mu#1363] opened 2019-01-15 14:11 UTC
We received the following bugreport: https://bugzilla.suse.com/show_bug.cgi?id=1111950

Where I have actually no idea about. So I would like to spread the word here in case someone else knows more. I guess Debian, who also is very active with reproducible builds is also interested in this.

It seems that `/usr/share/emacs/site-lisp/mu4e/mu4e-view.elc` differs randomly.
I have never seen such an issue but actually don't know much about the internals of emacs. I only started using emacs for mu4e.

We use mu4e 1.0 and emacs 26.1 on openSUSE Tumbleweed.

**Comment by bmwiedemann** [comment] 2019-01-16 16:48
My analysis showed that it differs between 1-core-VM / `make -j1` and 4-core / `make -j4` so it cannot be reproduced with a simple sequential make call. If you did not manage to reproduce it until Monday, I will look into making a simpler reproducer.

**Comment by djcb** [comment] 2019-02-19 05:18
Hmm, some of the mu4e source .el files depend on others (with `require` etc)... so perhaps the difference is between using a source version or a pre-compiled version.

@bmwiedemann: What happens when you add `MAKEFLAGS=-j1` to `mu4e/Makefile.am`?

**Comment by jubalh** [comment] 2019-03-05 10:24
> What happens when you add MAKEFLAGS=-j1 to mu4e/Makefile.am? 

Then it probably works since like stated in openSUSE bug, building with

```
make -C lib %{?_smp_mflags}
make
```

also makes it work.

**Comment by bmwiedemann** [comment] 2019-03-05 12:36
```diff
--- mu-1.0.orig/mu4e/Makefile.am
+++ mu-1.0/mu4e/Makefile.am
@@ -16,6 +16,7 @@
 
 include $(top_srcdir)/gtest.mk
 
+MAKEFLAGS=-j1
 SUBDIRS=
 
 info_TEXINFOS=mu4e.texi
```

still left it unreproducible though:


```diff
/usr/share/emacs/site-lisp/mu4e/mu4e-view.elc differs at offset '32229' (Emacs/X
Emacs v23 byte-compiled Lisp data)
+++ /usr/share/emacs/site-lisp/mu4e/mu4e-view.elc 2019-02-19 10:25:09.343072440 +0000
@@ -1,11 +1,11 @@
 00007dc0  6e 74 65 72 61 63 74 69  76 65 29 20 61 70 70 6c  |nteractive) appl|
 00007dd0  79 20 66 75 6e 63 74 69  6f 6e 20 23 5b 28 23 35  |y function #[(#5|
-00007de0  3d 23 3a 47 32 29 20 22  5c 33 30 31 08 4a 21 5c  |=#:G2) "\301.J!\|
+00007de0  3d 23 3a 47 35 29 20 22  5c 33 30 31 08 4a 21 5c  |=#:G5) "\301.J!\|
 00007df0  32 30 37 22 20 5b 23 35  23 20 62 72 6f 77 73 65  |207" [#5# browse|
 00007e00  2d 75 72 6c 2d 6d 61 69  6c 5d 20 32 5d 20 71 75  |-url-mail] 2] qu|
 00007e10  6f 74 65 20 2d 2d 63 6c  2d 72 65 73 74 2d 2d 20  |ote --cl-rest-- |
 00007e20  28 69 6e 74 65 72 61 63  74 69 76 65 29 20 23 5b  |(interactive) #[|
-00007e30  28 23 36 3d 23 3a 47 33  29 20 22 5c 33 30 31 08  |(#6=#:G3) "\301.|
+00007e30  28 23 36 3d 23 3a 47 36  29 20 22 5c 33 30 31 08  |(#6=#:G6) "\301.|
 00007e40  4a 21 5c 32 30 37 22 20  5b 23 36 23 20 62 72 6f  |J!\207" [#6# bro|
 00007e50  77 73 65 2d 75 72 6c 5d  20 32 5d 5d 20 38 20 28  |wse-url] 2]] 8 (|
 00007e60  23 24 20 2e 20 33 31 35  37 33 29 5d 29 0a 23 40  |#$ . 31573)]).#@|
```

**Comment by djcb** [comment] 2020-02-26 20:50
Is this still an issue? Or does `MAKEFLAGS=-j1` do the trick?

**Comment by djcb** [comment] 2020-05-17 06:18
Since there's a workaround at least, closing this for now. Thanks all.

**Closed by djcb** 2020-05-17 06:18 UTC
Labels: needinfo
