### ISSUE TITLE
Newer messages not shown when full search is off.

### ISSUE THREAD

**Issue by joostkremers** [djcb/mu#1919] opened 2021-01-29 20:46 UTC
## Expected or desired behavior

If I execute a search with full search turned off, I expect the newest messages matching the search to show up.

## Actual behavior

The messages that show up are older messages. If I toggle full search (`Q`), all messages show up, so I can see the newest ones as well. If I toggle full search again, the newest messages disappear.

## Steps to reproduce

Just execute a search with full search turned off.

## Versions of mu, mu4e/emacs, operating system etc.

I just pulled the latest commit (e5a52e4).

OS: Linux / Elementary OS 5 (based on Ubuntu 18.04)

Emacs: 27.1.91 (compiled from source)

## Any other detail

This used to work until I pulled the latest changes. I was running commit 46bd7051 from Dec. 26 before.

**Comment by djcb** [comment] 2021-01-30 09:04
This is a duplicate of #1916.

**Closed by djcb** 2021-01-30 09:04 UTC

**Comment by joostkremers** [comment] 2021-02-10 12:31
> This is a duplicate of #1916.

I'm not sure it's a duplicate. I just pulled the latest commit, 6ff9829, which fixes #1916, but it doesn't seem to fix my issue.

To show what I mean, this is mu4e commit 46bd705 (or thereabouts) showing a mail dir with a few new messages, full slatestearch off:

![mu4e-46bd705-full-search-off](https://user-images.githubusercontent.com/191630/107509787-5122ab80-6ba3-11eb-8119-3c65eff26e10.png)

Here is the latest commit (6ff9829) showing the same mail dir with full search off. Notice the dates on the messages, the most recent ones are from 2020, and the new messages aren't visible:

![mu4e-latest-full-search-off](https://user-images.githubusercontent.com/191630/107509851-6ac3f300-6ba3-11eb-87be-bb0928324f24.png)

If I toggle full search (`Q`), I can see all messages:

![mu4e-latest-full-search-on](https://user-images.githubusercontent.com/191630/107509920-86c79480-6ba3-11latesteb-8ca5-4f1431e79624.png)

Possibly there's something in my config that's causing this, but I looked through it and nothing stands out.

**Comment by joostkremers** [comment] 2021-02-10 12:35
Hmm, seems #1916 isn't fixed either, as suggested by @wavexx: https://github.com/djcb/mu/issues/1916#issuecomment-776673481.

**Comment by djcb** [comment] 2021-02-10 13:16
Thanks for testing - did you do a `./autogen.sh` first before rebuilding?

**Comment by joostkremers** [comment] 2021-02-10 14:29
Yes, I always start with `./autogen.sh` when I compile a newer version. I don't do `make clean` or anything similar, though.

**Comment by djcb** [comment] 2021-02-11 07:32
Okay... I have pushed some updates... does that help?

**Comment by joostkremers** [comment] 2021-02-11 08:17
Yes, the latest commit (936fd3f4) appears to work. Thanks!
