### ISSUE TITLE
Some emails do not show up on mu4e 1.3.5

### ISSUE THREAD

**Issue by averter** [djcb/mu#1513] opened 2019-11-17 08:21 UTC
## Expected or desired behavior
mu4e should display all received emails in the headers buffer.

## Actual behavior
I noted that some emails do not show up on mu4e, but appear on my thunderbird browser. This issue occurs only when I use a compiled version of mu4e. I don't know what is the criteria for emails to be excluded, and I've tried to rebuild the index tree but nothing changed.

## Versions of mu, mu4e/emacs, operating system etc.
mu4e 1.3.5, emacs 26.3 Linux mint 19.2 Cinnamon

## Any other detail
I don't know what is the best information to debug why this is happening. I have opened a similar [issue](https://github.com/djcb/mu/issues/1478) before and the configuration log seemed to be fine according to @djcb .

**Comment by theophilusx** [comment] 2019-11-17 08:32
To possibly help isolate this issue, I'm not seeing this behaviour with
a compiled version of 1.3.5 on Ubuntu Mate 19.10 with latest emacs built
from git (27.0.50). Everything appears to be working fine. Using mbsync
to get email from gmail.

Tim
Averter <notifications@github.com> writes:

> ## Expected or desired behavior
> mu4e should display all received emails in the headers buffer.
>
> ## Actual behavior
> I noted that some emails do not show up on mu4e, but appear on my thunderbird browser. This issue occurs only when I use a compiled version of mu4e. I don't know what is the criteria for emails to be excluded, and I've tried to rebuild the index tree but nothing changed.
>
> ## Versions of mu, mu4e/emacs, operating system etc.
> mu4e 1.3.5, emacs 26.3 Linux mint 19.2 Cinnamon
>
> ## Any other detail
> I don't know what is the best information to debug why this is happening. I have opened a similar [issue](https://github.com/djcb/mu/issues/1478) before and the configuration log seemed to be fine according to @djcb .


-- 
Tim Cross

**Comment by averter** [comment] 2019-11-17 09:01
Hmmm, I found an additional detail. Two of the "invisible emails" were in a separate directory and simply do not show up when the "unread messages" bookmark is used. However, a third "invisible email" is in the inbox and I can't see it regardless if I am in the inbox directory or not...

**Comment by djcb** [comment] 2019-11-17 12:24
First I'd check if you can reproduce with plain `mu` from the command line. Check if you can find it e.g. by searching for the subject.

**Comment by averter** [comment] 2019-11-17 12:53
@djcb Ah, good that you mentioned that. The problem was that I had maildir-utils installed from my previous setup (I removed mu4e but not maildir-utils), and was using mu 0.9.18 to rebuild the index tree and mu4e 1.3.5 to parse the emails.  It is working now. Thank you very much!

**Comment by averter** [comment] 2019-11-18 12:09
It is happening again... Sorry but I'll have to reopen it. I can see the emails with mu but not on emacs. Another detail is that it seems to only happen with the emails of my work account, which has a mbsync+davmail+mu4e setup.

**Comment by averter** [comment] 2019-11-18 12:39
I'm starting to see a pattern: 1-the email is received and I am able to read it, 1- after some time if I try to open the email from the headers it is not there anymore errors are
`error in process filter: insert-file-contents-literally: Opening input file: No such file or directory, /myusername/mailInbox/cur/1574080332.13784_2,U=1813:2,S`
`error in process filter: Opening input file: No such file or directory, /myusername/mailInbox/cur/1574080332.13784_2,U=1813:2,S`
I activated enter debugger on error and will try to post the output when I get another example.

**Comment by djcb** [comment] 2019-11-18 18:52
So you can open a message (1), and you can open it again, but after "some time" (how long?) you cannot do so anymore? Sounds like something else is changing the mail files behind mu's back... perhaps mbsync?

**Comment by averter** [comment] 2019-11-18 19:13
Indeed, I think it is [this](https://sourceforge.net/p/isync/bugs/38/) isync bug, because after my previous comment my thunderbird mailbox suddenly became filled with duplicates of a particular email. 
When I first set up mbsync+davmail+mu4e 0.9.18 I ran into this issue but then was able to fix it by changing the mbsyncrc file. So I wonder why now this bug came back when I installed mu4e 1.3.5... One solution is to install isync 1.3.1. I'll try to do that and see what happens.

**Comment by averter** [comment] 2019-11-19 10:47
@djcb it disappears in about 6 minutes or so. Here is an error log (some parts omited)

````elisp
Debugger entered--Lisp error: (error "Error 70: cannot read file /home/username/Mail/user@workemail/Inbox/cur/1574159554.8453_1.mypcname,U=1996:2,S: No such file or directory")
  signal(error ("Error 70: cannot read file /home/username/Mail/user@workemail/Inbox/cur/1574159554.8453_1.mypcname,U=1996:2,S: No such file or directory"))
  error("Error %d: %s" 70 "cannot read file /home/username/Mail/user@workemail/Inbox/cur/1574159554.8453_1.mypcname,U=1996:2,S: No such file or directory")
  mu4e-error-handler(70 "cannot read file /home/username/Mail/user@workemail/Inbox/cur/1574159554.8453_1.mypcname,U=1996:2,S: No such file or directory")
  mu4e~proc-filter(#<process  *mu4e-proc*> "\376a1\377(:error 70 :message \"cannot read file /home/username/Mail/user@workemail/Inbox/cur/1574159554.8453_1.mypcname,U=1996:2,S: No such file or directory\")\n\376275\377(:view (\n\011:docid 1726\n\011:subject \"test\"\n\011:date (24019 50296 0)\n\011:size 7732\n\011:message-id \"87a78s5f9j.fsf@gmail.com\"\n\011:path \"/home/username/Mail/user@workemail/Inbox/cur/1574159913.8654_1.mypcname,U=1997:2,S\"\n\011:maildir \"/user@workemail/Inbox\"\n\011:priority normal\n\011:flags (seen)\n\011:tags (\"NonJunk\")\n\011:parts ((:index 1 :name \"1.msgpart\" :mime-type \"text/plain\" :type (leaf) :attachment nil  :size 0  ))\n\011:from ((\"My gmail username\" . \"myusername@gmail.com\"))\n\011:to ((\"Gmail username\" . \"MyUsername@workemail\"))\n\011:user-agent \"mu4e 1.3.5; emacs 26.3\"\n\011:body-txt-params ((\"charset\" . \"us-ascii\"))\n)\n)\n\n")

````

**Comment by tausen** [comment] 2019-11-20 16:10
Not sure if this is the same issue, but sounds related. I'm using offlineimap.

Same thing happened to me today - I received and replied to an email through mu4e and was later unable to find the email. Could find the message with the mu command line, but not through mu4e. Tried with a few different versions (v1.0, 1.2) to no avail.

Seemed to be an issue with the mu cache in my case. I had both ~/.mu and ~/.cache/mu. At least one of them (maybe both) had been built with an older mu version (0.9.11). After deleting both and rebuilding ~/.cache/mu with mu 1.3.5, things seem to work again. Might be the same false positive that @averter ran into, will report back if that's the case.

**Comment by emryd** [comment] 2019-12-01 13:06
This seems to be due to the fact mails without a Message-ID are considered as duplicates when the mu-find --skip-dups option is set.

**Comment by tausen** [comment] 2019-12-02 07:17
Thanks! My disappearing messages seem to show up after invoking `mu4e-headers-toggle-skip-duplicates`.

Are these messages somehow loosing their Message-ID and getting them again after running `mu index`?

**Comment by djcb** [comment] 2020-01-21 19:13
There are some different issues here:
- messages disappearing because some tool (isync?) is removing the messages behind mu's back. There's not so much we can do about that.
- messages not showing because they are duplicates; that can be turned off in both mu and mu4e.

I don't think we can do more about this from the mu/mu4e side... closing this.

**Closed by djcb** 2020-01-21 19:13 UTC
