### ISSUE TITLE
[mu4e bug] attachment names containing Chinese characters are not handled right

### ISSUE THREAD

**Issue by jian-lin** [djcb/mu#2309] opened 2022-08-01 03:34 UTC
**Describe the bug**

what I expect: attachment names containing Chinese characters at the receiver's end are the same as those at the sender's end
what actually happens: attachment names containing Chinese characters at the receiver's end are not the same as those at the sender's end

**How to Reproduce**

1. `C` in `*mu4e-win*`
2. fill `To:` and `Subject:`
3. `M-x mml-attach-file`
  3.1. choose a file with Chinese characters in its name, e.g. `测试123abc.tar`
  3.2. choose a mime type, e.g. `archive/tar`
  3.3. `RET` to input empty `One line description`
  3.4. choose `attachment` as `Disposition`
4. `C-c C-c` to send the message
5. check the receiver's mailbox, and find the name of attachment is wrong, e.g. gmail shows `noname` instead of `测试123abc.tar`.

**Environment**

OS: Linux (NixOS)
Emacs: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
Mu: 1.8.7
`send-mail-function` is `#'smtpmail-send-it`

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by jian-lin** [comment] 2022-08-02 03:50
I find [this](https://emacs.stackexchange.com/questions/54734/mail-attachment-filename-coding) and his solution, `(setq rfc2047-encode-encoded-words nil)` works for me, too.

This is part of a right (`rfc2047-encode-encoded-words` is nil`) raw email:
```
Content-Disposition: attachment;
 filename="=?utf-8?B?5rWL6K+VMTIzYWJjLnRhcg==?="
```
Gmail says
```
Content-Disposition: attachment; filename="测试123abc.tar"
```

This is the wrong (`rfc2047-encode-encoded-words` is `t`) one:
```
Content-Disposition: attachment;
 =?us-ascii?Q?filename=3D=22=3D=3Futf-8=3FB=3F5rWL6K+VMTIzYWJjLnRhcg=3D=3D?=
 =?us-ascii?Q?=3F=3D=22?=
```
Gamil says
```
Content-Disposition: attachment; "filename=\"=?utf-8?B?5rWL6K+VMTIzYWJjLnRhcg==?=\""
```

**Comment by djcb** [comment] 2022-08-02 04:04
I tried to reproduce, but here it seems to work just fine; I get:
```
Content-Disposition: attachment;
 filename="=?utf-8?B?5rWL6K+VMTIzYWJjLnRhcg==?="
```
so just what gmail does. I suspect the problem may be in using a non-utf8 locale. 

In general, I'd recommend using a UTF-8 locale, but at least you have found a solution; I'll add a note to the reference manual - thanks!

**Comment by jian-lin** [comment] 2022-08-02 04:08
> I tried to reproduce, but here it seems to work just fine

with `rfc2047-encode-encoded-words` set to `t`?

> I'd recommend using a UTF-8 locale,

I think my locale is utf8, is there any way to check it?

**Comment by jian-lin** [comment] 2022-08-02 04:22
``` console
> localectl
   System Locale: LANG=en_US.UTF-8
```

On my machine, if `rfc2047-encode-encoded-words` is `t`, the `filename` part is encoded twice:
call `rfc2047-decode-region` on
```
=?us-ascii?Q?filename=3D=22=3D=3Futf-8=3FB=3F5rWL6K+VMTIzYWJjLnRhcg=3D=3D?=
=?us-ascii?Q?=3F=3D=22?=
```
you will get `filename="=?utf-8?B?5rWL6K+VMTIzYWJjLnRhcg==?="`

**Comment by jian-lin** [comment] 2022-08-03 04:23
I can reproduce it in `emacs -Q` in `compose-mail`'s `message-mode`, which derives `mu4e-compose-mode`. I have reported this bug to emacs and will post the link when I get a bug id.

I find another workaround:
```elisp
(setq rfc2047-header-encoding-alist
      ;; rua can be any symbol other than nil, mime,
      ;; address-mime, a charset or default
      (cons '("Content-Disposition" . rua)
            rfc2047-header-encoding-alist))
```

**Comment by jian-lin** [comment] 2022-08-03 09:03
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=56906

**Comment by jian-lin** [comment] 2022-08-04 09:55
Here is the fix which will be in emacs29: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=f025005e8619ab42b43dad5dd470dbbbcdc75041

Feel free to close this.

**Comment by djcb** [comment] 2022-08-12 05:25
Oh, thank you for researching this. Still weird I couldn't reproduce.

Closing.

**Closed by djcb** 2022-08-12 05:25 UTC
Labels: mu4e
