### ISSUE TITLE
cfind --personal doesn't find all contacts that emailed me

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#2000] opened 2021-04-27 09:56 UTC
I did 

`mu init -m maildir --my-address my@address.com`

and `mu index`.

`mu cfind --personal some_name` finds several addresses matching "some_name", but not "some_name@his_address.com", although `mu find 'f:some_name@his_address.com t:my@address.com'` finds some hits. Any idea how to debug this?

**Comment by antoine-levitt** [comment] 2021-04-27 09:57
Should say this is mu 1.4.15. Worked fine before (with an old mu version)

**Comment by antoine-levitt** [comment] 2021-05-06 12:27
Sorry to insist, but any ideas? This is a regression from previous mu versions, and I'll have to revert if this is not fixed.

**Comment by djcb** [comment] 2021-05-06 20:25
...but you can find it with `cfind` without the `--personal`? 

Can you attach a message / contact where this happened (anonymized as needed, but should reproduce the issue). Thanks.

**Comment by antoine-levitt** [comment] 2021-05-07 07:09
Sorry should have said: yes `cfind` without `--personal` works. I've sent you a copy of an email to your email address. Thanks!

**Comment by djcb** [comment] 2021-05-07 15:21
Hmm. I didn't receive anything, and frankly the best place is to attach it here, so others can take a look as well. Can you confirm it's a problem with the dev (1.5.x) series as well?

**Comment by antoine-levitt** [comment] 2021-05-07 17:29
Thanks for the suggestion, I've updated to master: there the `mu cfind --personal` command works as expected, but the mu4e completion doesn't (ie produces the same results that `mu cfind --personal` did in 1.4)...

**Comment by antoine-levitt** [comment] 2021-05-07 18:19
OK so I think I've traced it. mu4e sends
```
2021-05-07 20:17:28.812 -> (contacts :personal t :after nil :tstamp "150476135990")
2021-05-07 20:17:28.822 * Received 49 byte(s)
2021-05-07 20:17:28.822 <- (:contacts nil :tstamp "150490996090")
```
If I do `(pp (hash-table-keys mu4e~contacts-hash))`, the results don't match with `mu cfind --personal` at all.

**Comment by antoine-levitt** [comment] 2021-05-07 18:23
After banging my head I think I figured out the pattern: it seems like some boolean flag got inverted somewhere and mu4e only gets the non-personal contacts instead of the personal ones. That's about how far I can go without plunging into the mu code.

**Comment by djcb** [comment] 2021-05-07 19:21
Restarting mu4e after `(setq mu4e-compose-complete-only-personal t)`:
```
[mu4e] Contacts updated: 2460; total 2222
```

Restarting mu4e after `(setq mu4e-compose-complete-only-personal nil)`:
```
[mu4e] Contacts updated: 5708; total 5272
```
Those numbers look reasonable at least.

Note that the hash in mu4e is also subject to `mu4e-compose-complete-only-after`

**Comment by djcb** [comment] 2021-06-26 13:04
As before, can you attach a message with a contact that _should_ be included, but isn't, using mu 1.5.x? Let's concentrate on `mu cfind` here, not `mu4e` (since it does not influence the result).  Thanks.

**Comment by antoine-levitt** [comment] 2021-06-27 16:16
Sorry if I was unclear: the problem is that the results from mu cfind --personal and for mu4e's completion do not match. Eg for a particular contact I get:

```
antoine@lambda:~$ mu cfind person
Person Name mail1
Person Name mail2
Person Name mail3
antoine@lambda:~$ mu cfind --personal person
Person Name mail3
```
mu4e's completion for person gives me nothing under  mu4e-compose-complete-only-personal t and Person Name mail3 under mu4e-compose-complete-only-personal.

**Comment by djcb** [comment] 2022-05-22 09:17
Contacts works a bit different now (in 1.7.x); closing this for now. If you can reproduce with >= 1.7.23, feel free to reopen - thanks!

**Closed by djcb** 2022-05-22 09:17 UTC
Labels: needinfo

**Comment by antoine-levitt** [comment] 2022-05-29 18:31
I can reproduce issues in mu 1.7.23 (not tried mu4e):
```
antoine@lambda:~$ mu cfind XXX
XXX@host1
XXX@host2
XXX@host3
antoine@lambda:~$ mu cfind --personal XXX
XXX@host1
XXX@host2
```
I have received emails directly from the address in third line, not from the first or the second (although they do appear in emails sent to me). Not sure what more information to provide to help debug this.

**Comment by djcb** [comment] 2022-05-30 17:38
As before, what's needed is an example message with contacts that are not recognized as "personal" + the "personal addresses. You can of course use fakes if you can reproduce with that -- thanks!

**Comment by djcb** [comment] 2022-05-30 18:45
Oh, and if you have the very latest `master` and you run with `--debug`, it'll log when it considers a message "personal", i.e., if one the contacts in the message is considered personal.
