### ISSUE TITLE
[mu4e bug] Failing to start server, "mu server process ended with exit code 1"

### ISSUE THREAD

**Issue by c3d** [djcb/mu#2525] opened 2023-07-26 15:23 UTC
**Describe the bug**
After a recent upgrade of Emacs (Fedora 38, package `emacs-28.2-7.fc38.x86_64`, `mu` failed to start with a message "mu server process ended with exit code 1".

Using `mu4e-server-repl` shows:

```
Process terminal exited abnormally with code 127
..: line 1: [: syntax error: `--debug' unexpected
..: line 1: /usr/local/bin/mu --debug server: No such file or directory
```

Debugging showed that the Emacs `(term)` function now has trouble with anything containing multiple arguments. There is this weird piece of code in `term.el.gz` function `term-exec-1` which seems to do some weird extra argument parsing and injection, and that seems to be causing the problem.

```
    (apply #'start-process name buffer
	   "/bin/sh" "-c"
	   (format "stty -nl echo rows %d columns %d sane 2>%s;\
if [ $1 = .. ]; then shift; fi; exec \"$@\""
		   term-height term-width null-device)
	   ".."
	   command switches)))
```

Running `(term "zsh")` from a scratch server works, but `(term "zsh foo.sh`)` fails in a similar fashion:

```
Process terminal exited abnormally with code 127
..: line 1: [: too many arguments
..: line 1: exec: zsh foo.sh: not found
```

**How to Reproduce**

1. _ docker run -it --rm -- fedora:latest bash  
2. dnf install -y emacs git make meson ninja-build g++ glib2-devel gmime30-devel xapian-core-devel
3. git clone https://github.com/djcb/mu.git 
4. cd mu
5. make && make install
6. (cd /usr/local/share/emacs/site-lisp/; tar cf - mu4e) | (cd /usr/share/emacs/site-lisp/; tar xvf - )
7. Start Emacs
8. In `*scratch*` buffer, type `(require 'mu4)` and control-J
9. Type `m-x mu4e`

At this point, I get an error message `error in process sentinel: mu server process ended with exit code 1`.

 
**Environment**
Fedora 38, package `emacs-28.2-7.fc38.x86_64, `mu` rebuilt from `master` at commit 23ba61a65086a48957bb31918a252423e94c3e4a. `mu version` returns `version 1.11.10` but the same problem had shown with the 1.8 I had before, so it's an Emacs regression.

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade) 
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment] 2023-07-26 17:28
Hmm, I'm on the same Fedora and with same emacs 28.2, I can't reproduce. The term errors for `mu4e-server-repl` are probably a red-herring, since the _real_ mu4e process doesn't concatenate the parameters like that.

I bet the problem is something else..  can you try:
```
M-: (shell-command "mu server" "*output*") RET
```
and then check the "*output*" buffer? (perhaps use the full path for mu).

**Comment by c3d** [comment] 2023-07-27 07:24
I get
```
No such file or directory
```

This is the same thing I get from `mu server` on the command line.

Something has gone wrong with that install. If I type `mu find "Hello"` or `mu info`, I get:

```
% mu info
terminate called after throwing an instance of 'fmt::v10::format_error'
  what():  string pointer is null
[3]    3966343 IOT instruction (core dumped)  mu info
```

**Comment by c3d** [comment] 2023-07-27 07:28
So I tried a big sledgehammer: ran `mu init --maildir=~/Maildir --my-address=...` (5 `my-address`). Right after that, `mu index`:

```
error: '~/Maildir' is not readable: No such file or directory
```

But the directory exists and looks perfectly readable to me:

```
% ls -l ~/Maildir
total 0
drwxrwxr-x. 1 ddd ddd 432 Jul 17 11:06 gmail
drwxrwxr-x. 1 ddd ddd 254 Jan 21  2022 rh
drwxr-xr-x. 1 ddd ddd  18 Mar  6  2020 trash
% du -sh ~/Maildir
27G	/home/ddd/Maildir
```

So apparently all files are readable.

**Comment by c3d** [comment] 2023-07-27 07:35
One thing that does not really make sense with my explanation is why this broke when I did a `dnf update` for my Emacs. I only installed a new `mu` after that started failing.

**Comment by djcb** [comment] 2023-07-27 09:19
I think the problem is with the shell and/or environment setup. Because of that, `mu` can't be found (and `~/Maildir` don't work as expected).

The `terminate called` is a bug in the formatting code... do you see that with the latest still, ie. 1.11.12?

**Comment by djcb** [comment] 2023-07-28 16:39
Anyway, seems mu4e isn't doing anything wrong here, closing.

**Closed by djcb** 2023-07-28 16:39 UTC
Labels: bug, mu4e
