### ISSUE TITLE
[mu bug] white-space doesn't work in `--target-dir` parameter

### ISSUE THREAD

**Issue by danielkrajnik** [djcb/mu#2619] opened 2024-01-08 22:31 UTC
**Describe the bug**
This fails: 
```shell
mu extract --save-all "Sent Items/240.eml" --target-dir "Sent Items/240"
```
`error: target 'Sent' is not a writable directory` I've tried both to escape white space and surround it with quotes
**To Reproduce**
1. Create a folder with a white space in it (e.g. "Sent Items")
2. Add an .eml email to it (e.g. 240.eml)
3. create a target folder in it (e.g. 240)
4. Try to extract that message to that folder using the command above (mu extract --save-all "Sent Items/240.eml" --target-dir Sent\ Items/240)
5. It will fail with the above errror
**Environment**
Linux 6.6.9-arch1-1 x86_64
LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling

mu --version: 1.10.8

**Checklist**
- [x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by djcb** [comment] 2024-01-09 04:19
Can't reproduce that (with 1.11.x/`master`)... what shell are you using?

**Comment by danielkrajnik** [comment] 2024-01-09 09:51
That's strange, I'm using zsh ([z4h](https://github.com/romkatv/zsh4humans)).

I've tried to run it via [fd-find](https://github.com/sharkdp/fd) previously and it gave the same error:
`fd . -e eml -x mu extract --save-all {} --target-dir '{.}'`

**Comment by djcb** [comment] 2024-01-14 07:11
The `--save-all` parameter is unquoted, so that explains.

**Comment by danielkrajnik** [comment] 2024-01-14 11:03
Quoting it doesn't resolve the issue:
` fd . -e eml -x mu extract --save-all '{}' --target-dir '{.}'`

```
error: target 'Sent' is not a writable directory
````

**Comment by djcb** [comment] 2024-01-23 17:30
But now you're quoting the input to `fd`, not the input to `mu`. Using external tools doesn't help isolating the problem.

Anyway, I still can't reproduce, so I'm going to close this; feel free to reopen if you can reproduce with `master` and without any external tools, thanks!

**Closed by djcb** 2024-01-23 17:30 UTC
Labels: bug, mu
