### ISSUE TITLE
[mu4e bug]

### ISSUE THREAD

**Issue by martinarielhartmann** [djcb/mu#2797] opened 2024-12-13 06:43 UTC
Hi, I'm having a problem with 1.12.7-st and GNU Emacs 29.3 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.6 (Build 21G646)) of 2024-03-24, Macos 15.0 (24A335). Let's say I get a message from this person:
```
From: Stüber, Madonna <madonna.stueber@foo.bar>
Subject: Thank You
To: "Doe, John" <john.doe@fakemail.com>
Date: Thu, 12 Dec 2024 20:49:10 +0000 (9 hours, 49 minutes, 21 seconds ago) 

```

When I hit reply, mu4e creates this:

```
To: Stüber
Cc: Madonna <madonna.stueber@foo.bar>
Subject: Re: Thank You
From: Doe, John <john.doe@fakemail.com>
```
This of course can be edited manually, but I guess it is a bug that could be addressed. I get it every time there is an umlaut in a name.

Thanks again for mu4e!!!!

**Comment by djcb** [comment] 2024-12-13 10:41
Can you attach a raw message file where this happens? Thanks.

**Comment by martinarielhartmann** [comment] 2024-12-13 20:03
Sure. Is there a less public way to do this?

**Comment by djcb** [comment] 2024-12-13 21:48
To looks at this, we need the raw message. You can of course anonymize it as much as needed, as long as the problem still reproduces. Thank you!

**Comment by djcb** [comment] 2024-12-14 08:57
Anyway, looking at the line, the relevant RFCs imply that the address must be quoted. See 
  https://stackoverflow.com/questions/15555563/how-to-format-an-email-from-header-that-contains-a-comma
for some details (and links to the relevant specs)

So it seems the problem is on the sender-side.

Now, presumably, some email programs try to be smart and guess what the sender _really_ meant. I don't think the Gnus machinery (which mu4e uses) has anything like that.. and perhaps the problem is rare enough to ignore.

So perhaps ask the sender to quote the name-part of their address?

**Comment by bderembl** [comment] 2024-12-14 19:30
Have you tried this?
https://github.com/djcb/mu/issues/2662#issuecomment-2147205731

**Comment by djcb** [comment] 2024-12-14 20:45
Oh, had forgotten about that one! Thanks @bderembl!

**Comment by martinarielhartmann** [comment] 2024-12-17 09:06
> Have you tried this? [#2662 (comment)](https://github.com/djcb/mu/issues/2662#issuecomment-2147205731)

That seems to solve my problem, thanks! I haven't tried sending an e-mail to one of my 'colleägues' yet, but everything looks good so far.

Thanks again!

**Comment by djcb** [comment] 2024-12-17 09:15
Gnus doesn't enable it by default, there's probably a reason for that...
Anyway, closing this...

**Closed by djcb** 2024-12-17 09:15 UTC
Labels: needinfo, mu4e
